<!-- Start Top Navigation -->
<div id="top_nav">
    <!-- Start Drop Down Menu -->
    <ul class="sf-menu">

        <!-- Dash board -->
        <li>
            <a class="m" href="<?php echo ADMIN_PROJECT_BASEPATH;?>">Dashboard</a>

        </li>
        <li>
            <a class="m" href="<?php echo ADMIN_PROJECT_BASEPATH;?>page">Content</a>
            <ul>
                <li>
                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>page">Pages</a>
                    <ul>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>page">View All Pages </a></li>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>page/create">Create New Page </a></li>
                    </ul>
                </li>
                <li>
                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>language">Languages</a>
                </li>
                <li>
                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>section">Translations</a>
                </li>
            </ul>

        </li>
        <!-- products -->
        <li>

            <a class="m" href="<?php echo ADMIN_PROJECT_BASEPATH;?>product/view">Site Contents</a>


            <ul>
                <li><a class="m" href="<?php echo ADMIN_PROJECT_BASEPATH;?>product/view/tab/tab-all">All Content</a>
                            <ul>
                                
                                <li>
                                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>product/view/tab/tab-not-approved">Non Approved Content</a>
                                </li>
                                <li>
                                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>product/view/tab/tab-under-review">Content Under Review</a>
                                </li>
                                <li>
                                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>product/view/tab/tab-approved">Approved Content</a>
                                </li>
                                <li>
                                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>product/view/tab/tab-rejected">Rejected Content</a>
                                </li>
                            </ul>
                    </li>

                    
                    <li><a class="m" href="<?php echo ADMIN_PROJECT_BASEPATH;?>product/listfeatured">Featured Content</a></li>
              </ul>
                
            



        </li>
        <!-- Sales -->

        <!-- Affilication -->

        <!-- Banners -->

        <!-- Users -->
        <li>
            <a class="m" href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/list/">Users</a>
            <ul>
                <li>
                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/list/tab/tab-customers">Customers</a>
                </li>
                <li>
                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/list/tab/tab-cps">Content Providers(CPs)</a>
                </li>
                <li>
                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/list/tab/tab-chaps">CHAPS</a>
                    <ul>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/list/tab/tab-chaps">All CHAPS</a></li>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/create-chap">New CHAP</a></li>
                    </ul>
                    
                </li>

                <li>
                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/list/tab/tab-resellers">Resellers</a>
                    <ul>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/list/tab/tab-resellers">All Resellers</a></li>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/create-reseller">New Reseller</a></li>
                    </ul>

                </li>
            </ul>

        </li>
        <!-- Configurations -->
        <li>
            <a class="m" >Configurations</a>
            <ul>
                <li>
                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>country">Country</a>
                </li>
                <li>
                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>currency/">Currency</a>
                </li>
                <li>
                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>category">Category</a>
                    <ul>

                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>category/create">Create New Category</a></li>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>category/">View</a></li>
                    </ul>
                </li>
                    

                <li>
                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>platform/list">Product Platform</a>
                    <ul>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>platform/create">Create New Platform</a></li>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>platform">View All Platforms</a></li>
                    </ul>
                </li>
                
                <li>
                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>payout/list">Payout Schemes</a>
                    <ul>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>payout/create">Create Payout Scheme</a></li>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>payout/list">View All Payout Schemes</a></li>
                    </ul>
                </li>
                
                <li>
                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>paymentgateway/list">Payment Gateways</a>
                    <ul>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>paymentgateway/create">Create Payment Gateway</a></li>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>paymentgateway/list">View All Payment Gateways</a></li>
                    </ul>
                </li>
                <li>
                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>pricepoint/list">Price Points</a>
                    <ul>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>pricepoint/create">Add Price Point</a></li>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>pricepoint/list">View All Price Points</a></li>
                    </ul>
                </li>
                
                <li>
                    <a href="#">Translations</a>
                    <ul>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>translation/categories-translations-list">Categories</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        
        <li>    
            <a class="m" href="<?php echo ADMIN_PROJECT_BASEPATH;?>promotions/">Promotions</a>
             <ul>
                <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>promotions/create">Create Codes</a></li>
                <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>promotion-campaign">All Campaigns</a></li>
                <li>
                    <a href="#">Reports</a>
                    <ul>
                        <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>promotion-reports/usage">Usage Reports</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        
        <li>
            <a class="m" href="#">Analytics</a>
            <ul>
                <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>analytics/summary">Analytics Overview</a></li>
                <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>analytics/dashboard">Detail Analytics</a></li>
                <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>analytics/chapanalytics">CHAP Analytics</a></li>
                <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>analytics/inapp-payments">Inapp Payment</a></li>
            </ul>
        </li>

        <li>
            <a class="m" href="<?php echo ADMIN_PROJECT_BASEPATH;?>review/list">Reviews</a>
            <ul>
                <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>review/index/type/eva">Eva's Reviews</a>
                <!--<li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>review/approved">Approved</a></li>
                <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>review/un-approved">UnApproved</a></li>-->
            </ul>
        </li>
        <li>
            <a class="m" href="<?php echo ADMIN_PROJECT_BASEPATH;?>announcement/list">Announcements</a>
            <ul>
                <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>announcement/create/">New Announcement</a>
                <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>announcement/list">View All Announcements</a></li>
            </ul>
        </li>
        
         <li>
             <a class="m" href="#" onclick="return false;">Accounting</a>
             <ul>
                 <li> <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>account">Received Payments</a> </li>
                 <li> <li><a href="<?php echo ADMIN_PROJECT_BASEPATH;?>account/makepayment">Manual Credit/Debit</a> </li>
             </ul>
        </li>
        <li>
            <a class='m' href='/cache'>Cache</a>
        </li>
        <!-- My Account -->
        <li>
            <a class="m" href="<?php echo ADMIN_PROJECT_BASEPATH;?>profile">My Account</a>
        </li>

        <li>
            <a class="m" href="<?php echo ADMIN_PROJECT_BASEPATH;?>ticket">Tickets</a>
        </li>
        
    </ul>
    <!-- End Drop Down Menu -->
</div>
<!-- End Top Navigation -->
