<div class="title">

    <h3>Handsets</h3>

    
</div>
<div class="box">
    <div class="txt">

        <div id="content_box">
            <!-- Start tab tab-handsets -->
            
            <div class="tab-handsets">
                <!-- Start Table -->
                <table cellpadding="0" cellspacing="0">
                    <thead>
                        <tr>
                            <!--<th><input type="checkbox" name="check" /></th>-->
                            <th>Name</th>
                            <th>Useragent</th>
                            <th>&nbsp;</th>
                            <th>&nbsp;</th>
                            
                        </tr>
                    </thead>
                    <tbody>

                        <? foreach($this->handsets as $handset): ?>
                        <tr>
                            <!--<td><input type="checkbox" name="check" /></td>-->
                            <td><?= $handset['brand']."-".$handset['model']; ?></td>
                            <td><?= $handset['useragent']; ?></td>
                            <td>&nbsp;</td>
                            
                            
                        </tr>
                        <?endforeach; ?>
                    </tbody>
                </table>
                 <!-- End Table -->
                 <?= $this->paginationControl($this->handsets, 'Sliding', 'partials/paginator.phtml'); ?>
            </div>
            <!-- End handsets -->
        </div>
    </div>
</div>