
<script type="text/javascript">

    $().ready(function(){
        //alert( "You are running jQuery version: " + $.fn.jquery );
        if (window.location.hash && window.location.hash == '#_=_') {
            if (window.history && history.pushState) {
                window.history.pushState("", document.title, window.location.pathname);
            } else {
                // Prevent scrolling by storing the page's current scroll offset
                var scroll = {
                    top: document.body.scrollTop,
                    left: document.body.scrollLeft
                };
                window.location.hash = '';
                // Restore the scroll offset, should be flicker free
                document.body.scrollTop = scroll.top;
                document.body.scrollLeft = scroll.left;
            }
        }
    });

</script>

<?php
$headerColour="";
$cpauth = Zend_Auth::getInstance();
$user   = NULL;
if ($cpauth->getIdentity()) {
    $user     =   new Cpbo_Model_UserMeta();
    $user->setEntityId($cpauth->getIdentity()->id);
}

        $chapSessionNs = new Zend_Session_Namespace('chap');
        //Zend_Debug::dump($chapSessionNs->chap);die();
        $userName ='';
        $logout = '/user/logout';

                //Default logo - nexva logo
        	$logo = PROJECT_BASEPATH.'/cp/assets/img/global/logo.png';
                //Default URL
                $url = '/';
                //Default Div class=
        	$divClass = 'logo';
                
                if(!empty($chapSessionNs->chap->username))
                {
                   if($chapSessionNs->chap->username == 'nexva.mobi')	
                   {
                       $userName = ''; 
                   }                       
                   else 
                   {
                       
                        $logout = 'user/logout/r/'.$chapSessionNs->chap->username;

                        //Check if Chap logo exists
                        //if( file_exists(APPLICATION_PATH."/../public/cp/".$chapSessionNs->chap->username."/img/logo.png") )  
                        //{        	
                            //override default logo with custom logo
                        $logo =  !empty($this->cpLogo) ? '/cp/assets/logos/'.$this->cpLogo : "/cp/".$chapSessionNs->chap->username."/img/logo.png";                        
                        $url = '/r/'.$chapSessionNs->chap->username;
                        $divClass = 'chap_logo';
                        //}                    
                       $headerColour =  !empty($this->cpHeaderColour) ? 'background:'.$this->cpHeaderColour : 'background:#A5A5A5';
                       $userName = $chapSessionNs->chap->username;
                   }
                }    
                else 
                {
                	
                   $userName = ''; 
                }	
        ?>

 <!-- Start Header -->
<?php //echo $this->customCss; die();?>
<div id="header" class="inner_cp" style="<?= $headerColour; ?>" >   
    <div class="<?= $divClass ?>">
        <a href="<?= $url ?>">
            <img src="<?= $logo ?>" alt="logo"/>
        </a>
    </div>
    
    <?php /*print_r($chapSessionNs->chap);*/?>
    <? if(!empty($chapSessionNs->chap->username)) : ?>
     
        <? if($chapSessionNs->chap->username != 'nexva.mobi') : ?>
    
            <div id="div_heading">
                      <h1><?php echo $this->cpTitle;?></h1>
            </div>
    
        <? endif;?>
        
    <? else :?>
          
    <? endif;?>
                
    
    
    <?php

    $locale  =   Zend_Registry::get('Zend_Locale');

    $date   =   new Zend_Date(Zend_Date::DATETIME_FULL,$locale);

    ?>
    <?php 
    	if ($user) :    	
    ?>
    <div class="info">
        <div>
            <h2><?php echo $this->translate("Welcome back");?> <span><?php echo ucfirst($user->FIRST_NAME);?></span></h2>
            <small><?=$date;?> <?php echo $this->translate("GMT. Last login");?> : <?=$user->LAST_LOGIN;?></small>
            <small><a href="http://www.nexva.com" target="_blank"><?php echo $this->translate("View Website");?></a>  | <a href="<?= PROJECT_BASEPATH.$logout;?>"><?php echo $this->translate("Log out");?></a></small>
        </div>
    </div>
    <?php endif;?>
    
    <? if(!empty($chapSessionNs->chap->username)) : ?>
     
        <? if($chapSessionNs->chap->username == 'nexva.mobi') : ?>
    
                <div id="nexva_logo"></div>
                
        <? endif;?>
        
    <? else :?>
          
    <? endif;?>
        
    <!-- End Info -->
</div>
<!-- End Header -->