<div class="blkCenter innerPage containerGap">
    <!-- product list page start -->
    <div class="prodListPage">
        <div class="container">
            <div class="contContent">
                <div class="blockContent">
                    <div class="blkHead">
                        <h2 id="pageTitle">This app has been removed</h2>
                        <p>&nbsp</p><p>&nbsp</p>
                        <p>We're sorry, this app is no longer avaialble on neXva.</p>
                        <p>&nbsp</p><p>&nbsp</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>