<div class="blkCenter innerPage">
    <!-- product list page start -->
    <div class="prodListPage">
        <div class="container">
            <div class="contTop"></div>
            <div class="contContent">
                <div class="blockContent">
                    <div class="blkHead">
                        <h2 id="pageTitle"><?=$this->productInfo['name']?></h2>

                        <ul id="breadcrumbs">
                            <?foreach($this->categoryBreadcrumbs as $breadcrumb): ?>
                            <li><a href="/category/<?=$this->slug($breadcrumb['name'])."/".$breadcrumb['id']?>"><?=$breadcrumb['name']?></a></li>
                            <?endforeach;?>

                        </ul>
                    </div>
                    <div class="blkList">
                        <div class="prodView">
                            <div class="leftCol">
                                <div class="posterImg"><img name="prod_poster" src="<?=$this->productImages()?><?=$this->productInfo['screenshots'][0]?>" width="200" height="270" border="0" id="prod_poster" alt="" /></div>
                            </div>
                            <div class="rightCol">
                                <div class="specsheet">

                                    <div><label>Price</label>
                                        <?if($this->productInfo['cost']==0): ?>
                                        <span id="prod_price">Free</span>
                                        <?else: ?>
                                        <span id="prod_price">$<?=$this->productInfo['cost']?></span>
                                        <?endif;?>
                                    </div>
                                    <div><label>Platform</label><span id="prod_platform"><?=$this->productInfo['platform_name']?></span></div>
                                    <div><label>Vendor</label><span id="prod_vendor"><?=$this->productInfo['user_meta']->COMPANY_NAME?></span></div>
                                    <!-- <div><label>Rating</label><span id="prod_rating"><img src="images/star.gif" alt="star" width="11" height="12" /><img src="images/star.gif" alt="star" width="11" height="12" /><img src="images/star.gif" alt="star" width="11" height="12" /></span></div>-->
                                </div>

                                <div class="qrCode">
                                    <?$config = Zend_Registry::get("config");?>

                                    <img name="qr_code" src="<?=$this->qr("http://".$config->nexva->application->mobile->url."/app/show/id/".$this->productInfo['id'], 80, 80)?>" width="80" height="80" border="0" id="qr_code" alt="Generating QR code.." />

                                </div>
                                <div class="buttons">
                                    <ul class="btn">
                                        <?if($this->productInfo['content_type'] == 'URL'):?>
                                        <li>
                                                <?
                                                $download = '';
                                                if(is_array($this->productInfo['file'])):?>
                                                    <?

                                                    foreach($this->productInfo['file'] as $url): ?>
                                                        <? if(preg_match('|^http(s)?://[a-z0-9-]+(.[a-z0-9-]+)*(:[0-9]+)?(/.*)?$|i', $url)): ?>
                                                            <? $download = $url;?>
                                                        <? else: ?>
                                                            <? $download = $this->S3Url($this->productInfo['id'] . '/' . $url); ?>

                                                        <? endif; ?>
                                                    <? endforeach; ?>
                                                <? endif; ?>
                                                <? $qrCode = $this->qr($download, 150, 150)?>
                                                <? $url = "http://".$config->nexva->application->mobile->url."/app/show/id/".$this->productInfo['id']?>
                                                <?=$this->partial('partials/download.phtml', array('or_code'=>$qrCode, 'uri'=>$url, 'id'=>$this->productInfo['id']));?>
                                            <a href="javascript:viewDownload ('Download <?=$this->trim(str_replace("'", "", $this->productInfo['name']), 50)?> (for <?=$this->productInfo['platform_name']?>)', '<?=$this->productInfo['id']?>');" id="prod_demo">Download </a>
                                        </li>
                                        <?elseif($this->productInfo['cost']==0 || $this->productInfo['is_purchased']): ?>
                                            <?$config = Zend_Registry::get("config");?>                                       <li>
                                            <a href="javascript:viewDownload ('Download <?=$this->trim(str_replace("'", "", $this->productInfo['name']), 50)?> (for <?=$this->productInfo['platform_name']?>)', '<?=$this->productInfo['id']?>');" id="prod_demo">Download </a>
                                                <? $qrCode = $this->qr("http://".$config->nexva->application->mobile->url."/app/show/id/".$this->productInfo['id'], 150, 150)?>
                                                <? $url = "http://".$config->nexva->application->mobile->url."/app/show/id/".$this->productInfo['id']?>
                                                <?=$this->partial('partials/download.phtml', array('or_code'=>$qrCode, 'uri'=>$url, 'id'=>$this->productInfo['id']));?>
                                        </li>
                                        <?else: ?>
                                        <li><a href="<?php echo PROJECT_BASEPATH;?>app/buy/id/<?=$this->productInfo['id']?>" class="buy">Buy</a></li>
                                        <?endif;?>
                                        <li><a name="fb_share" type="icon_link" href="http://www.facebook.com/sharer.php">Share</a><script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script></li>
                                        
                                    </ul>
                                </div>
                                <div class="screenShots">
                                    <h3>Screenshots</h3>
                                    <ul>
                                        <? foreach($this->productInfo['screenshots'] as $screenshot): ?>
                                        <li><a href="javascript:viewScreenShot('<?=$screenshot?>');"><img src="<?=$this->productImages()?><?=$screenshot?>" width="80" height="80" border="0" alt="" /></a></li>
                                        <?endforeach;?>
                                    </ul>
                                </div>

                            </div>
                            <div class="description">
                                <p><?=$this->FacebookLike("http://".$config->nexva->application->base->url. $_SERVER['REQUEST_URI'])?></p>
                                <h3>Description</h3>
                                <p><?=$this->productInfo['desc']?></p>      
                            </div>









                            

                            <div class="">
                                <div class="table reviews">
                                 
                                <? foreach($this->reviews as $review): ?>
                                <div class="review">
                                  <h4><?= $review['LAST_NAME']; ?></h4>
                                  <ul class="rating">
                                        <li>
                                            <label>Rating</label>
                                            <? for($count=0;$count<$review['rating'];$count++){ ?>
                                          <img src="<?=$this->cdn('site_assets')?>/web/images/star.gif" alt="star" width="11" height="12" />

                                          <?}?>
                                        </li>
                                    <li>
                                    	<label>Date</label>
                                    	<p><?= $review['date']; ?></p>
                                    </li>
                                  </ul>
                                  
                                      <div class="comments">
                                        <p><?= $review['review']; ?></p>
                                      </div>
         						</div>

                                <?endforeach; ?>

                                <ul class="btn">
                                	<li><a href="more" class="buy">more</a></li>
                                </ul>
                              </div>
                            </div>












                            <div>
                                <h3>Compatible Devices</h3>

                                <div class="table">
                                    <?
                                    $i = 0;
                                    $count = count($this->productCompatibleDevices);
                                    $currentDeviceBrand = "";
                                    $models = "";
                                    ?>

                                    <table>
                                        <?foreach($this->productCompatibleDevices as $device): ?>
                                        <tr class="<?if( 0 == $i ) echo 'first'?> <?if($i==$count-1) echo 'last'?>"><th><?=$device->brand?></th><td><?=$device->models?></td></tr>
                                            <? $i++; ?>
                                        <?endforeach; ?>
                                    </table>

                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="contBottom"></div>
        </div>
    </div>
    <!-- product list page end -->
</div>

