<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="en-us" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

        <?= $this->headTitle($this->title); ?>

        <!-- Core Stylesheet -->
        <link href="/cp/assets/css/core.css" media="screen" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" type="text/css" href="/cp/assets/css/yellow.css" title="styles2" media="screen" />

        <!-- Javascript Files -->
        <script type="text/javascript" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/js/jquery.min.js"></script>
        <style>
            #contentWrap {
                padding: 0 15px;
            }
        </style>
      
   

        <?php
        echo $this->headMeta();
        echo $this->headScript();
        echo $this->headStyle();
        echo $this->headLink();
        ?>
        <!--[if IE 6]>
        <link href="/cp/assets/css/ie6.css" media="screen" rel="stylesheet" type="text/css" />
        <script src="/cp/assets/js/DD_belatedPNG_0.0.8a-min.js"></script>
        <script>
          /* EXAMPLE */
          DD_belatedPNG.fix('.logo img, .message, table img');

          /* string argument can be any CSS selector */
        </script>
        <![endif]-->

    </head>
    <body>
        
        <!-- Start Wrap -->

        <div id="content">


            <noscript>
                <!-- Show message when javascript is not enabled -->
                <div class="message error">
                    <p>Javascript is needed for this template to work properly. <br />Please <a href="http://browsehappy.com/" title="Upgrade to a better browser">upgrade</a> your browser or <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Enable Javascript in your browser">enable</a> Javascript to navigate the interface properly.</p>
                </div>
            </noscript>
            <div id='contentWrap'>
                <?php echo $this->layout()->content ?>
            </div>
            
        </div>
        
        <?php echo $this->partial('/parts/analytics.phtml')?>      
    </body>
    
</html>