<?php $t = $this->t();//translator?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="content-type"
    	content="application/xhtml+xml;charset=utf-8" />
    <meta name="viewport"
    	content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />
    <meta content="en" http-equiv="content-language" />
    <meta content="no-cache" http-equiv="Cache-Control" />
    <title><?= isset($this->pageTitle) ? $this->pageTitle . ' | ' : '' ?><?= $this->title ?>
    | Mobile</title>
    <link href="<?=$this->cdn('site_assets')?>/mobile/css/style.css<?=$this->VER?>" rel="stylesheet" type="text/css"></link>
    <link href="<?=$this->cdn('site_assets')?>/mobile/css/nexpage.css<?=$this->VER?>" rel="stylesheet" type="text/css"></link>
    
    <?php 
    $ns = new Zend_Session_Namespace('translation'); //include this only if the translation utility is enabled
    if (isset($ns->translatorEnabled) && $ns->translatorEnabled === true) : ?>
        <?php 
        
        /**
         * Ignore the weird script includes. This code should only ever run on a 
         * non mobile device. -JP
         */ 
        ?>
        <link type="text/css" rel="stylesheet" href="<?=$this->cdn('site_assets')?>/web/css/translator.css">
        <link type="text/css" rel="stylesheet" href="<?=$this->cdn('site_assets')?>/web/jquery-ui.nexva.css">
        <script type="text/javascript" src="<?=$this->cdn('jquirymin')?>"></script>
        <script type="text/javascript" src="<?=$this->cdn('jquiryui')?>"></script>
        <script type="text/javascript">
           var __SECTION = '<?php echo $t->getSection()?>';
           var __PHRASE_TAGS    = {};
           <?php foreach ($t->getPhraseTags() as $key => $tag) : ?>
                 __PHRASE_TAGS.<?=$key?> = '<?=addslashes($tag)?>';
           <?php endforeach;?>
        </script>
        <script type="text/javascript" src="<?=$this->cdn('site_assets')?>/web/js/translateutil.js"></script>
                 
    <?php endif; ?>
    
    <!-- Add JS and CSS dynamically -->
    <?php
    echo $this->headMeta();
    echo $this->headScript();
    echo $this->headStyle();
    echo $this->headLink();
    ?>
</head>
<body>

        <div class="header padding-all">
            <h1 class='company-name'>
                <a href="/">
                    <?=$this->cpName;?>
                </a>
            </h1>

            <div class='device_note'>
                <a class="device_name" href="/device">Android <?//= $this->phone ?></a>
                <a href="/device"><small class="orange">  (<?php //$t->_('not_device');?>)</small></a>
            </div>
        </div>
    <div id="content" class="content rounded">
        <?= $this->layout()->content ?>
    </div>
    <div id='sitelangs' class='content rounded'>
    <?php $t->_h('current_lang');?>
        <div class='app'>
         <form action='/nexpage/changelang/<?=$this->cpid;?>' method='post'>
         
            <?php $t->_('current_lang', true);?> : 
            <select name='langid' id='langlist'>
                 <? foreach ($this->language as $language ): ?>
                    <option value="<?=$language->id ?>" <?= ($language->id == $this->selectedLanguage) ? 'selected' : '' ?>>
                        <?=$language->common_name ?> <?=(!empty($language->common_name)) ?  ' &mdash; ' . $language->name : $language->name?>
                    </option>
                 <? endforeach; ?>
            </select>
            <?php if ($this->appId) : ?>
                <input type='hidden' value='<?=$this->appId;?>' name='appid'>
            <?php endif; ?>
            <input type='hidden' value='<?=$this->cpid;?>' name='cpid'>
            <button style='padding:5px' type='submit'  class='button'><?php $t->_('change_lang', true);?></button>
            <?php $t->_h('change_lang');?>
        </form>
    </div>
    </div>
    <!-- content ends -->
</body>
</html>
