<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 6/12/13
 * Time: 4:08 PM
 * To change this template use File | Settings | File Templates.
 */
?>

<div class="title">
    <h3>Assign Payout | neXva.com</h3>
</div>

<div class="box">
    <div class="txt">
        <?php if(count($this->messages) > 0 ){?>
        <div class="message info">
            <p><?php foreach($this->messages as $message)
                {
                    echo $this->escape($message);
                } ?>
            </p>
        </div>
        <?php } ?>
        <div class="content-box-content">
            <table cellpadding="0" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th valign="top" style="text-align: center">Default</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->payouts as $payout) { ?>
                        <tr>
                            <td><?php echo $payout->name;?></td>
                            <td><?php echo $payout->description;?></td>
                            <td valign="top" style="text-align: center">
                                <?php if(isset($this->user[0]->payout_id) && ($payout->id == $this->user[0]->payout_id)){ ?>
                                    <img style="border: none" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/icon/icon-default.png"/>
                                <?php } else { ?>
                                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/set-default-payout/user/<?php echo $this->user[0]->id;?>/id/<?php echo $payout->id;?>" title="Set Default">
                                        <img style="border: none" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/icon/icon-notdefault.png"/>
                                    </a>
                                <?php } ?>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
            <?= $this->paginationControl($this->payouts, 'Sliding', 'partials/paginator.phtml'); ?>
        </div>
    </div>
</div>