<?php $user = $this->user?>
<div class="title">
    <h3 style="cursor: s-resize;">Create CHAP</h3>
</div>

<div class="box">
    <div class="txt">
        <div class="content_box">
            <?php if(isset($this->errors) && !empty($this->errors)) : ?>
                <?php foreach ($this->errors as $message) : ?>
                <div class="message error" style="display: block;">
                    <p><?=$message ?></p>
                </div>
                <?php endforeach; ?>
            <?php endif; ?>
            
            <?php //$this->placeholder('formHeadline')->set($this->getTranslation('Create New User'));?>
            <fieldset>
                <form class='form_validate' method="post" action="/user/create-chap">
                 <p>
                    <label for='username'>Username</label>
                    <input value='<?=$user->username?>' type='text' id='username' name='username' class='txt-input medium validate(required, rangelength(1,80))'>
                 </p>
                 
                 <p>
                    <label for='email'>Email</label>
                    <input value='<?=$user->email?>' autocomplete='off' type='text' id='email' name='email' class='txt-input medium validate(required, email, rangelength(5,80))'>
                 </p>
                 
                 <p>
                    <label for='password'>Password</label>
                    <input autocomplete='off' value='<?=$user->password?>' type='password' id='password' name='password' class='txt-input medium validate(required, rangelength(5,32))'>
                 </p>
                 
                 <p><input type="submit" class="txt-input small" value="Create CHAP" id="submit" name="submit"></p>
                 </form>
                 
                 
            </fieldset>
        </div>
    </div>
</div>
