<?php $user = $this->user?>
<div class="title">
    <h3 style="cursor: s-resize;">Edit CHAP Contacts</h3>
</div>

<div class="box">
    <div class="txt">
        <div class="content_box">
            <?php if(isset($this->errors) && !empty($this->errors)) : ?>
                <?php foreach ($this->errors as $message) : ?>
                <div class="message error" style="display: block;">
                    <p><?=$message ?></p>
                </div>
                <?php endforeach; ?>
            <?php endif; ?>
            
            <?php //$this->placeholder('formHeadline')->set($this->getTranslation('Create New User'));?>
            <fieldset>
                <form class='form_validate' method="post" action="/user/edit-contact-chap/id/<?=$this->userId;?>">
                 <p>
                    <label for='username'>Admin contact name</label>
                    <input value='<?=$user->CHAP_ADMIN_CONTACT_NAME?>' type='text' id='admin_contact_name' name='admin_contact_name' class='txt-input medium validate(required)' style="width: 250px">
                 </p>
                 
                 <p>
                    <label for='email'>Admin contact email</label>
                    <input value='<?=$user->CHAP_ADMIN_CONTACT_EMAIL?>' autocomplete='off' type='text' id='admin_contact_email' name='admin_contact_email' class='txt-input medium validate(required, email)'  style="width: 250px">
                 </p>
                 
                 <p>
                    <label for='email'>Admin contact phone</label>
                    <input value='<?=$user->CHAP_ADMIN_CONTACT_PHONE?>' autocomplete='off' type='text' id='admin_contact_phone' name='admin_contact_phone' class='txt-input medium '  style="width: 250px">
                 </p>
                 
                   <p>
                    <label for='username'>Technical contact name</label>
                    <input value='<?=$user->CHAP_TECHNICAL_CONTACT_NAME?>' type='text' id='technical_contact_name' name='technical_contact_name' class='txt-input medium validate(required)'  style="width: 250px">
                 </p>
                 
                 <p>
                    <label for='email'>Technical contact email</label>
                    <input value='<?=$user->CHAP_TECHNICAL_CONTACT_EMAIL?>' autocomplete='off' type='text' id='technical_contact_email' name='technical_contact_email' class='txt-input medium validate(required, email)'  style="width: 250px">
                 </p>
                 
                 <p>
                    <label for='password'>Technical contact phone</label>
                    <input  value='<?=$user->CHAP_TECHNICAL_CONTACT_PHONE?>' type='text' id='technical_contact_phone' name='technical_contact_phone' class='txt-input medium)' style="width: 250px">
                 </p>
                 
                 
                 <p><input type="submit" class="txt-input small" value=" &nbsp;  Add &nbsp;  " id="submit" name="submit"></p>
                 </form>
                 
                 
            </fieldset>
        </div>
    </div>
</div>
