<div class="title">
    <h3 style="cursor: s-resize;">Filter User</h3>
    <div title="content_box" class="selector">
        <!-- <a class="tab active" href="tab-table">List All</a>-->
        <a href="tab-forms" class="tab active">Filter Users</a>
        <!--<a class="tab" href="tab-forms">Create a Page</a>-->
    </div>
</div>

<div class="box">
    <div class="txt">
        <div class="content_box">

            <!-- Messsage -->
            <?php
            if(isset($this->message)) {
                ?>
            <div class="message <?=$this->message[1] ?>" style="display: block;">
                <p><?=$this->message[0] ?></p>
            </div>
                <?php
            }
            ?>

            <!-- Filters -->
            <table>
                <tbody>
                    <tr>
                        <td>
                            <p>
                                <?= $this->filter ?>
                            </p>
                        </td>
                        <td class="alt">
                            <p>
                                <?= $this->updateOptions ?>
                            </p>
                        </td>
                    </tr>
                </tbody>
            </table>

            <!-- Contents -->
            <form method="post">
                <table>
                    <thead>
                        <tr>
                            <th><input type="checkbox" name="check" class="selectall"></th>
                            <th>ID</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>Type</th>
                            <th>Operations</th>
                        </tr>
                    </thead>
                    <?php
                    foreach($this->users as $user) {
                        echo $this->partial('partials/row.phtml', array("user" => $user));
                    }
                    ?>
                </table>
            </form>
        </div>
    </div>
</div>
