<div class="title">

    <h3>Users | neXva.com</h3>

    <div class="selector" title="content_box">
        <a class="tab <? if($this->selected_tab == '' or $this->selected_tab == 'tab-cps'){echo ' active';}?>" href="tab-cps">CPs</a>
        <a class="tab <? if($this->selected_tab == 'tab-customers' ){echo ' active';}?>" href="tab-customers">Customers</a>
        <!--<a class="tab <? if($this->selected_tab == 'tab-administrators' ){echo ' active';}?>" href="tab-administrators">Administrators</a>-->
        <a class="tab <? if($this->selected_tab == 'tab-chaps' ){echo ' active';}?>" href="tab-chaps">CHAPS</a>
        <a class="tab <? if($this->selected_tab == 'tab-resellers' ){echo ' active';}?>" href="tab-resellers">Resellers</a>
        <a class="tab <? if($this->selected_tab == 'tab-nexpager' ){echo ' active';}?>" href="tab-nexpager">neXpager</a>
    </div>
</div>

    <div class="txt">
        <div style="padding:20px 0px" align="center">
            <form method="POST" name="frmsearch" id="frmsearch" action="<?=$this->form_submit;?>">
                <input type="text"  value="<?=$this->search;?>"name="search" id="search" class="txt-input medium" style="width:300px" />
                <select class="select-input small" name="tab" id="tab"  >
                    <option value="tab-cps">CP</option>
                    <option value="tab-customers" <? if($this->selected_tab == 'tab-customers' )echo 'selected=selected';?>>Customers</option>
                    <option value="tab-chaps" <? if($this->selected_tab == 'tab-chaps' )echo 'selected=selected';?>>CHAPS</option>
                    <option value="tab-resellers" <? if($this->selected_tab == 'tab-resellers' )echo 'selected=selected';?>>Resellers</option>
                    <option value="tab-nexpager" <? if($this->selected_tab == 'tab-nexpager' )echo 'selected=selected';?>>neXpager</option>
                </select>
                <select class="select-input small" name="status" id="status"  >
                    <option value="1">Active</option>
                    <option value="0" <? if($this->status == 'nonactive' )echo 'selected=selected';?>>Non Active</option>

                </select>
                <input type="submit" class="button" name="submit" value="Search" />
                <small>Remove the search value and hit search to get the full list.</small>
            </form>
        </div>
        <div class="box">

            
            	<?php
        if(is_array($this->flashMessenger->getMessages())):
            foreach ($this->flashMessenger->getMessages() as $class => $value):
                ?>
            <?php if (is_array($value)) : ?>
                <?php $key = key($value); ?>       
                <div class="message <?=key($value)?>">
                    <?=$this->partial('partials/itemlist.phtml', array("item" => $value[$key]));?>
                </div>
            <?php endif;?>
            <?php
            endforeach;
        endif;
        ?>
            
        

        <div id="content_box">
        
       
        
            <div class="tab-cps">
                <!-- Start Table -->
                <table cellpadding="0" cellspacing="0">
                    
                    <thead>
                        <tr>
                            <!--<th><input type="checkbox" name="check" /></th>-->
                           
<!--                            <th>ID <?=$this->message[1] ?></th>-->
                            <th>ID </th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>Verified</th>
                            <th>Type</th>
                            <th>Created date</th>
                            <th>Operations</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        
                        <? foreach($this->cps_list as $user): ?>
                             <?= $this->partial('partials/row-cps.phtml',array('user'=>$user,'show_app_icons'=>$this->show_app_icons)); ?>
                        <?endforeach; ?>
                        <?if($this->is_cplist_empty  == true):?>
                        <tr>
                            <td colspan="5">
                                <small>
                                    <i>Cp list is empty.
                                    </i>
                                </small>
                            </td>
                        </tr>
                        <?endif; ?>
                    </tbody>
                </table>
                 <!-- End Table -->
                 <?= $this->paginationControl($this->cps_list, 'Sliding', 'partials/paginator.phtml',array("tab"=>"tab-cps","page_name" =>"page_cps","search_caption" =>"search","search_value" => $this->search)); ?>
            </div>

            <div class="tab-customers">
                <!-- Start Table -->
                <table cellpadding="0" cellspacing="0">
                    <thead>
                        <tr>
                            <!--<th><input type="checkbox" name="check" /></th>-->
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>Type</th>
                            <th>Created date</th>
                            <th>Operations</th>
                        </tr>
                    </thead>
                    <tbody>

                        <? foreach($this->customers_list as $user): ?>
                         <?= $this->partial('partials/row.phtml',array('user'=>$user,'show_app_icons'=>$this->show_app_icons)); ?>
                        <?endforeach; ?>
                        <?if($this->is_customerlist_empty  == true):?>
                        <tr>
                            <td colspan="5">
                                <small>
                                    <i>Customer list is empty.
                                    </i>
                                </small>
                            </td>
                        </tr>
                        <?endif; ?>
                    </tbody>
                </table>
                 <!-- End Table -->
                 <?= $this->paginationControl($this->customers_list, 'Sliding', 'partials/paginator.phtml',array("tab"=>"tab-customers","page_name" =>"page_customers","search_caption" =>"search","search_value"=>$this->search)); ?>
            </div>
            <!-- tab -->

            <!-- tab chaps -->
            <div class="tab-chaps">
                <!-- Start Table -->
                <table cellpadding="0" cellspacing="0">
                    <thead>
                        <tr>
                            <!--<th><input type="checkbox" name="check" /></th>-->
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>Type</th>
                            <th>Created date</th>
                            <th>Operations</th>
                        </tr>
                    </thead>
                    <tbody>

                        <? foreach($this->chaps_list as $user): ?>
                        <?= $this->partial('partials/row-chaps.phtml',array('user'=>$user)); ?>
                        <?endforeach; ?>

                        <?if($this->is_adminlist_empty  == true):?>
                        <tr>
                            <td colspan="5">
                                <small>
                                    <i>CHAPS list is empty
                                    </i>
                                </small>
                            </td>
                        </tr>
                        <?endif; ?>
                    </tbody>
                </table>
                 <!-- End Table -->
                 <?= $this->paginationControl($this->chaps_list, 'Sliding', 'partials/paginator.phtml',array("tab=tab-chaps","page_name" =>"page_chaps","search_caption" =>"search","search_value" =>$this->search)); ?>
            </div>
            <!-- tab -->
            

            <!-- tab resellers -->
            <div class="tab-resellers">
                <!-- Start Table -->
                <table cellpadding="0" cellspacing="0">
                    <thead>
                        <tr>
                            <!--<th><input type="checkbox" name="check" /></th>-->
                            <th>ID</th>
                            <th>Email</th>
                            <th>Name</th>                           
                            <th>Company Name</th>
                            <th>Operations</th>
                        </tr>
                    </thead>
                    <tbody>

                        <? foreach($this->reseller_list as $user): $userMeta = new Model_UserMeta(); $userMeta->setEntityId($user->id) ?>
                         <?= $this->partial('partials/row-reseller.phtml',array('user'=>$user, 'userMeta' => $userMeta)); ?>
                        <?endforeach; ?>

                    </tbody>
                </table>
                 <!-- End Table -->
                 <?= $this->paginationControl($this->chaps_list, 'Sliding', 'partials/paginator.phtml',array("tab=tab-resellers","page_name" =>"page_resellers","search_caption" =>"search","search_value" =>$this->search)); ?>
            </div>
            <!-- tab -->

            <!-- tab nexpager -->
            <div class="tab-nexpager">
                <!-- Start Table -->
                <table cellpadding="0" cellspacing="0">
                    <thead>
                        <tr>
                            <!--<th><input type="checkbox" name="check" /></th>-->
                            <th>ID</th>
                            <th>Company Name</th>
                            <th>Email</th>
                            <th>neXpager URL</th>

                        </tr>
                    </thead>
                    <tbody>

                        <? foreach($this->nexpagerCpList as $user): ?>
                         <?= $this->partial('partials/row-nexpager.phtml',array('user'=>$user)); ?>
                        <?endforeach; ?>

                        <?if($this->is_nexpagerListEmpty  == true):?>
                        <tr>
                            <td colspan="4">
                                <small>
                                    <i>neXpager list is empty
                                    </i>
                                </small>
                            </td>
                        </tr>
                        <?endif; ?>
                    </tbody>
                </table>
                 <!-- End Table -->
                 <?= $this->paginationControl($this->nexpagerCpList, 'Sliding', 'partials/paginator.phtml',array("tab" => "tab-nexpager","page_name" =>"page_nexpager","search_caption" =>"search","search_value" =>$this->search)); ?>
            </div>
            <!-- tab -->

            

        </div>
    </div>
</div>