                    <!-- Start Content Box #1 -->
                    <div class="title">

                        <h3>Back Office Admin Login | neXva.com</h3>

                        <div class="selector" title="content_box">
                            <a class="tab active" href="tab-login">Login</a>
                            <!--<a class="tab" href="tab-password">Forgotten Password</a>-->
                        </div>
                    </div>
                    <div class="box">
                        <div class="txt">

                            <div id="content_box">
                                <div class="tab-login">

                                    <!-- Start Message -->
                                    <div class="message info">
                                        <p>Please enter your username & password for admin access.</p>
                                    </div>
                                    <!-- End Message -->

                                    <? if( $this->error != '') //prob would be better to render a view partial here
                                    {
                                    ?>
                                        <div class="message error">
                                            <p><?=$this->error?></p>
                                        </div>

                                    <?
                                    }
                                    ?>

                                    <!-- Start Login Form -->
                                    <form method="post" action="<?php echo ADMIN_PROJECT_BASEPATH;?>user/login">
                                        <fieldset>
                                            <p><label>Username</label>
                                                <input type="text" id="username" name="username" class="txt-input large" />
                                            </p>


                                            <p><label>Password</label>
                                                <input type="password" id="password" name="password" class="txt-input large" />
                                            </p>

                                            <p style="float:left;"><input type="submit" class="button" name="submit" value="Login" />
                                                <input type="reset" class="reset" name="reset" value="Reset" /></p>
                                            <!--<p  class="remember"><input type="checkbox" /> Remember Me</p>-->
                                        </fieldset>

                                    </form>
                                    <!-- End Login Form -->

                                </div>
                                <div class="tab-password">
                                    <!-- Start Password Form -->
                                    <form method="post" action="index.html">
                                        <fieldset>
                                            <p><label>Email</label>
                                                <input type="text" class="txt-input large" />
                                                <small>Please enter the email address of your account</small></p>

                                            <input type="submit" class="button" name="submit" value="Request Password" />
                                        </fieldset>

                                    </form>
                                    <!-- End Password Form -->
                                </div>
                            </div>

                        </div>
                    </div>
                    <!-- End Content Box #1 -->


