<div class="title">
    <h3 style="cursor: s-resize;">Manually Credit / Debit</h3>
</div>

<div class="box">
    
<?php if(!empty($this->messagesSuccess))
{
?>
<br /> 
<div style="display: block;" class="message success">
                <p><?php echo $this->messagesSuccess; ?></p>
</div>
<?php

unset($this->messagesSuccess);
}
?>



    <div class="txt" style="font-size: 14px;">  
        
               
         <?php
        switch($this->type)
        {
            case "cp":
                $partner = "Channel Partner";
                break;
            
             case "resell":
                 $partner = "Reseller";
                 break;
        }
        ?>
        <h1><span style=" font-weight: bold">Type :</span> <?php echo $partner; ?></h1>
        <h1><span style=" font-weight: bold">Name :</span> <?php echo $this->userName; ?></h1>       
        <h1><span style=" font-weight: bold">Total :</span> <?php echo $this->totalAmount; ?></h1>
        
    </div>    

</div>

<div class="box">
    <div class="txt">
        <div class="content_box">       
            
            <fieldset>
                
                    <form class='form_validate' method="post" action="/user/manual-pay/id/<?=$this->userId;?>/type/<?=$this->type;?>">
                 
                        
                         <div class = "div_single_row">
                             <label for='payAction'>Action <span style = "color : #FF0000">*</span></label>

                            <select id="pay_manual_action" name="pay_manual_action" class="select-input small">
                                <option value="credit">Credit</option>
                                <option value="debit">Debit</option>                        
                            </select>

                         </div>


                         <div class = "div_space"></div> 
                         <div class = "div_single_row">
                            <label for='amount'>Amount <span style = "color: #FF0000">*</span></label>
                            <input value='' autocomplete='off' type='text' id='pay_manual_amount' name='pay_manual_amount' class='txt-input medium validate(required, number)'  style="width: 250px">
                         </div>


                         <div class = "div_space"></div> 
                         <div class = "div_single_row">
                            <label for='description'>Description <span style = "color : #FF0000">*</span></label>
                            <input value='' autocomplete='off' type='text' id='pay_manual_description' name='pay_manual_description' class='txt-input medium validate(required)'  style="width: 250px">
                         </div>                 


                         <div class = "div_space"></div> 
                         <div class = "div_space"></div> 

                         <div class = "div_single_row">
                             <input type="submit" class="txt-input small" value="Manually Credit / Debit" id="submit" name="submit">
                         </div>                  
                 
                 </form>
                 
            </fieldset>
        </div>
    </div>
</div>