<script type="text/javascript" language="javascript">

    $(document).ready(function()
    {
        //Auto complete for search user emails
        $('#regusers').autocomplete({
            //source:availableTags
            source: function( request, response ) {
                $.ajax({
                    url: "/user/get-serialised-user-emails",
                    dataType: "json",
                    data: {q: $('#regusers').val(),fromDate: $('#fromDate').val(),toDate: $('#toDate').val(),chkUserFilter: $('#chkUserFilter').val()},
                    success: function(data) {
                        if(data.length == 0)
                        {  
                            $('#regusers').val('No Mobile Number found');
                            $('#regusers').removeClass('ui-autocomplete-loading');
                            //$('.ui-autocomplete').hide();
                            return false                                
                        }
                        else
                        {
                            response($.map(data, function(item) {
                                return {
                                    label: item.mobile_no,
                                    id: item.id
                                };
                            }));
                        }
                        
                    }
                });
            },
            minLength: 1
        });
        
        //When Filter dropdown value changes
        $('#chkUserFilter').change(function()
        {

            $('#frmUsers').submit();
        });

        //When button clicks, submit the form
        $('#btnSubmit').click(function()
        {
            $('#frmUsers').submit();
        });

        $("#fromDate").datepicker({ dateFormat: 'yy-mm-dd'});
        $("#toDate").datepicker({ dateFormat: 'yy-mm-dd'});



        /* making a dynamic url for excel-report*/
        $('#excel-report').click(function(){

            var from = $('#fromDate').val();
            var to = $('#toDate').val();
            var email = $('#regusers').val();
            var type = $('#chkUserFilter').val();

            if(from){
                from = '/from/'+from;
            }
            if(to){
                to = '/to/'+to;
            }
            if(email){
                email = '/email/'+email;
            }
            if(type){
                type = '/type/'+type;
            }

            $(this).attr("href", "/user/excel-report"+from+to+email+type);

        });
    });

    function get_user_apps(contentId, userType)
    {
        $("#apps").html('');
        $("#preloader").removeClass('display_none');

        $.getJSON("/app/get-app-details",
            {
                id : contentId,
                usertype : userType
            },
            function(data)
            {
                if(data.length >0)
                {
                    var apps = '';

                    $.each(data, function()
                    {
                        apps += "<p>"+this['date']+" - "+this['name']+"</p>";

                    });

                }
                else
                {
                    apps = "<p>No records found.</p>";
                }

                $("#preloader").addClass('display_none');
                $("#apps").html(apps);
            });

    }

    function load_poup_box(contentId)
    {

        $("#apps_"+contentId).fancybox({
            'titleShow'     : false,
            'padding'	: 0,
            'transitionIn'	: 'elastic',
            'transitionOut'	: 'elastic',
            'autoDimensions': false,
            'width'		: 300,
            'height'	: 350,
            'showCloseButton' : true,
            'hideOnOverlayClick' : false
        });
    }
    
    function confirmDelete()
    {
        var confirmation = false;
        var answer = confirm("Are sure you want to delete this user?")
        if (answer){
            confirmation = true;

        }
        else{
            confirmation = false;
        }
        return confirmation;
    }

</script>

<?php
if($this->flashMessagesSuccess)
{  foreach($this->flashMessagesSuccess as $message)
{ ?>
    <div class="notification success png_bg">
        <div>
            <li><?php echo $this->escape($message); ?></li>
        </div>
    </div>
<?php }
} ?>

<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>

<?php if ($flashMessenger->setNamespace('error')->hasMessages()){ ?>
    <div class="notification error png_bg">
        <div>
            <?php foreach ($flashMessenger->getMessages() as $msg){
                echo $msg;
            } ?>
        </div>
    </div>
<?php } ?>

<!-- Pop-up window for displaying apps downloaded by the users -->
<?=$this->partial('partials/downloaded_apps_user.phtml')?>

<div class="content-box"><!-- Start Content Box -->
    <div class="content-box-header">
        <h3 style="cursor: s-resize;"><?= $this->title; ?></h3>
        <div id="icon_wrapper" style="margin-right:-20px;">
            <a alt="Excel Report" id="excel-report" href="#"> <img style="border: none" src="<?php echo PBO_PROJECT_BASEPATH;?>images/icons/excel_report.png" alt="Excel Report" /><br />
                Excel Report</a>
        </div>
    </div> <!-- End .content-box-header -->

    <div class="content-box-content">

        <div style="width:90%;float: left;">
            <form id="frmUsers" name="frmUsers" action="<?php echo PBO_PROJECT_BASEPATH;?>user/" method="post">

                <div style="float:left; width:50px; position: relative; left: 40px">
                    <label style="position: relative; top: 30px">Filter:</label>
                </div>

                <div style="float:left; width:120px; position: relative; left: 40px">
                    <label style="position: relative; left: 10px; width: 60px">From :</label>
                    <input style="width: 70px !important; left: 50px" type="text" class="text-input small-input" id="fromDate" name="fromDate" value="<?= (isset($this->fromDate) && $this->fromDate != 'all') ? $this->fromDate : '' ?>" />
                </div>

                <div style="float:left; width:120px; position: relative; left: 40px">
                    <label style="position: relative; left: 10px; width: 60px">To :</label>
                    <input style="width: 70px !important; left: 150px" type="text" class="text-input small-input" id="toDate" name="toDate" value="<?= (isset($this->toDate) && $this->toDate != 'all') ? $this->toDate : '' ?>" />
                </div>

                <div style="float:left; width:360px; position: relative; left: 40px">
                    <label style="position: relative; left: 10px; width: 100px">Mobile Number :</label>
                    <input style="width: 250px !important" type="text" class="text-input small-input" id="regusers" name="regusers" value="<?= (isset($this->searchKey) && $this->searchKey != 'all') ? $this->searchKey : '' ?>" />

                    <input style="margin-left: 15px" type="button" value="Search" name="btnSubmit" id="btnSubmit" class="button" />
                </div>

                <div style="float:left; width:100px; position: relative; left: 60px">
                    <label style="position: relative; left: 40px; width: 60px">Type :</label>
                    <select style="float: left" name="chkUserFilter" id="chkUserFilter" class="chkbox">
                        <option value="all" <?= ($this->userFilterVal == 'all') ? 'selected= "selected"' : '' ?> >All</option>
                        <option value="cp" <?= ($this->userFilterVal == 'cp' || empty($this->userFilterVal)) ? 'selected= "selected"' : '' ?> >Developer</option>
                        <option value="user" <?= ($this->userFilterVal == 'user') ? 'selected= "selected"' : '' ?> >User</option>
                    </select>
                </div>

            </form>
        </div>

        <div class="clear"></div>
        <br /><br />


        <? if($this->showResults == 'true' ) : ?>

            <table cellpadding="0" cellspacing="0" style="width: 90%">

                <thead>
                <tr>
                    <th>ID</th>
                    <th>E-Mail</th>
                    <th>Mobile</th>
                    <th>Type</th>
                    <th style="text-align:center;">Status</th>
                    <th>Activation Code</th>
                    <th style="text-align: left">
                        <?php
                     switch ($this->userFilterVal){
                         case 'cp':?>
                            Upload
                        <?php     break;
                         case'user'?>
                            Download
                        <?php     break;
                         case 'all':?>
                           Downloads / Uploads 
                      <?php       break;
                         default:?>
                           Upload
                <?php
                     }
                        ?>
                        </th>
                    <th style="text-align: center">Resend Verification</th>
                    <th style="text-align: center">Date Registered</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($this->regUsers as $regUsers) : ?>
                    <?php $dates = Date('Y-m-d', strtotime($regUsers->created_date)) ?>

                    <tr>
                        <td><?= $regUsers->id; ?></td>
                        <td><?= $regUsers->email; ?></td>
                        <td>
                            <?= $regUsers->mobile_no; ?>
                        </td>
                        <td><?= ($regUsers->type == 'CP') ? 'Developer' : ucfirst(strtolower($regUsers->type)); ?></td>
                        <td style="text-align:center;"><?php if($regUsers->type == 'CP')
                            {
                                if($this->verified($regUsers->id) == 1)
                                { ?>
                                    <img alt="verified" src="<?php echo PBO_PROJECT_BASEPATH;?>images/icons/yes.png" title="Verified"/>
                                <?php } else { ?>
                                    <img alt="not-verified" src="<?php echo PBO_PROJECT_BASEPATH;?>images/icons/no.png" title="Not-Verified"/>
                                <?php }
                            } else {
                                if($regUsers->status == 1)
                                { ?>
                                    <img alt="verified" src="<?php echo PBO_PROJECT_BASEPATH;?>images/icons/yes.png" title="Verified"/>
                                <?php } else { ?>
                                    <img alt="not-verified" src="<?php echo PBO_PROJECT_BASEPATH;?>images/icons/no.png" title="Not-Verified"/>
                                <?php }
                            } ?>
                        </td>
                        <!--<td style="text-align:center;"><?php
/*                            if($regUsers->status == 1)
                            { */?>
                                <img alt="verified" src="<?php echo PBO_PROJECT_BASEPATH;?>images/icons/yes.png" title="Verified"/>
                            <?php /*}else{ */?>
                                <img alt="not-verified" src="<?php echo PBO_PROJECT_BASEPATH;?>images/icons/no.png" title="Not-Verified"/>
                            <?php /*} */?>
                        </td>-->
                        <td><?php echo $regUsers->activation_code; ?></td>
                        <td style="text-align: left">
                            <img style="position: relative; top: 3px" <?= ($regUsers->type == 'CP' || empty($regUsers->type)) ? 'title="Uploads" src="'.PROJECT_BASEPATH.'/pbo/images/icons/upload.png"' : 'title="Downloads" src="'.PROJECT_BASEPATH.'/pbo/images/icons/download.png""'; ?> /> (<?= $this->userDownload($regUsers->id,$regUsers->type)?>)
                            &nbsp;
                            <?php if($this->userDownload($regUsers->id,$regUsers->type)>0) : ?>

                                <a title="View Apps" href="#app_view" id="apps_<?= $regUsers->id ?>">
                                    <img alt="View Apps" style="position: relative; top: 4px" src="<?php echo PBO_PROJECT_BASEPATH;?>images/icons/view-details.png" onClick="get_user_apps(<?= $regUsers->id ?>,'<?=$regUsers->type ?>');load_poup_box(<?= $regUsers->id ?>)"/>
                                </a>
                            <?php endif; ?>
                        </td>
                        <td style="text-align: center"><?php echo ($regUsers->type == 'USER') ? '<a href="'.PROJECT_BASEPATH.'user/resend-verification/user_id/'.$regUsers->id.'"><img src="'.PROJECT_BASEPATH.'pbo/images/icons/resend-verification.png" title="Resend Verification" alt="Resend Verification"/></a>':'N/A';?></td>
                        <td style="text-align: center"><?= $dates; ?></td>

                        <td valign="top" style="text-align:center">
                            <a href="<?php echo PBO_PROJECT_BASEPATH;?>user/delete-user/id/<?= $regUsers->id ?>" title="Delete ?" onclick="return confirmDelete()" >
                                <img style="border: none" src="<?php echo PBO_PROJECT_BASEPATH;?>images/icons/cross_circle.png" alt="Delete?" />
                            </a>
                        </td>
                    
                    </tr>
                <?php endforeach; ?>

                </tbody>

            </table>
            <br /> <?php

            $data = array(
                "user_filter" => ($this->userFilterVal) ? $this->userFilterVal : 'all',
                "search_key" => ($this->searchKey) ? $this->searchKey : 'all',
                "from_date" => ($this->fromDate) ? $this->fromDate : 'all',
                "to_date" => ($this->toDate) ? $this->toDate : 'all',
            );

            ?>
            <div style ="width : 90%">
                <?= $this->paginationControl($this->regUsers, 'Sliding', 'partials/pagination-user.phtml', $data); ?>
            </div>


            <br />

        <? else : ?>

            <p>No Records Found. </p>
            <br /><br />

        <? endif ; ?>

    </div>
</div>

<script type="text/javascript">
    $('#3').addClass('current');
    $('#31').addClass('current');
</script>