<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 5/12/14
 * Time: 6:46 PM
 * To change this template use File | Settings | File Templates.
 */
?>

<?php if (count($this->successMessages)) { ?>
    <div class="notification success png_bg">
        <div>

            <?php foreach ($this->successMessages as $message) { ?>

                <li><?php echo $this->escape($message); ?></li>

            <?php } ?>

        </div>
    </div>
<?php } ?>

<div class="content-box">
    <div class="content-box-header">
        <h3 style="cursor: s-resize;"><?php echo $this->title;?></h3>
        <div id="icon_wrapper">
            <a href="/category/add-qelasy-grade" alt=" Add Qelasy Grade" class="button">Add Grade</a>
        </div>
    </div>
    <div class="content-box-content">
        <div style="width:99%;float: right;">
            <form method="post" action="/category/qelasy-grades" id="qelasy-grades" name="qelasy-grades" class="pbo-admin-form">
                <?php if(count($this->grades)) { ?>
                <table style="width:97%; margin-left: 15px;" border="0">
                    <thead>
                        <tr>
                            <th style="width:25%;">Grade</th>
                            <th style="width:70%;">Description</th>
                            <th style="width:5%;">Action</th>
                        </tr>
                    </thead>
                    <tbody id="qelasy-grade-table">
                        <?php foreach ($this->grades as $grade) { ?>
                            <tr>
                                <td><a href="/category/edit-qelasy-grade/id/<?php echo $grade->id;?>"><?php echo $grade->name; ?></a></td>
                                <td><?php echo $grade->description; ?></td>
                                <td>
                                    <a href="/category/edit-qelasy-grade/id/<?php echo $grade->id;?>" title="Edit"><img alt="Edit" src="/pbo/images/icons/pencil.png" style="border: none"></a>
                                    <a href="/category/delete-qelasy-grade/id/<?php echo $grade->id;?>" title="Delete"><img alt="Delete" src="/pbo/images/icons/cross_circle.png" style="border: none"></a>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
                <br />
                <div style ="width : 99%">
                    <?php /*Zend_Debug::dump($this->paginationControl());die();*/?>
                    <?echo $this->paginationControl($this->grades, 'Sliding', 'partials/pagination-grades.phtml');?>
                </div>
                <?php } else { ?>
                    <p>No Records Found.</p>
                <?php } ?>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#1').addClass('current');
</script>