<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 11/19/13
 * Time: 11:50 AM
 * To change this template use File | Settings | File Templates.
 */
?>
<style type="text/css">
    #action-bar{
        height:50px;
    }
    /*.ticket{
        height:80px;
    }*/
    /*.wrapper-right{
        float:right;
    }*/
</style>
<script type="text/javascript">
    $().ready(function(){
        $('#check-all').click(function(){
            $('.ticket').find("input[type='checkbox']").attr('checked', $(this).is(':checked'));
        });

        $('#delete').click(function(){
            $('#ticket-list').attr('action','/ticket/delete');
            $('#ticket-list').submit();
        });

        $('#test').click(function(){
            $('#ticket-list').attr('action','/ticket/create');
            $('#ticket-list').submit();
        });
    });
</script>

<!-- Displays Success Message/s -->
<?php if(count($this->successMessages)) { ?>
    <div class="message info">
        <p>
            <?php foreach ($this->successMessages as $message) {
                echo  $this->translate($this->escape($message));
            } ?>
        </p>
    </div>
<?php } ?>

<!-- Displays Error Message/s -->
<?php if (count($this->errorMessages)) { ?>
    <div class="message error" style="display: block;">
        <p>
            <?php foreach($this->errorMessages as $message) {
                 echo  $this->translate($this->escape($message));
            } ?>
        </p>
    </div>
<?php } ?>

<div id="wrap" class="fixed" style="margin-top:20px;">
    <div id="content">
        <div class="title">
            <h3><?php echo $this->translate("My Tickets");?></h3>
        </div>
        <div class="box">
            <div class="txt">
                <div id="action-bar">
                    <input type="checkbox" id="check-all" />
                    <input type="submit" id="delete" value="<?php echo $this->translate("My Tickets");?>" class="submit button" />
                    <!--<input type="submit" id="close" value="Close" class="submit button" />-->
                </div>
                <?php echo $this->paginationControl($this->tickets, 'Sliding', 'partials/paginator.phtml'); ?>
                <form id="ticket-list" name="ticket-list" method="post" action="/ticket/delete">
                    <?php
                    //date_default_timezone_set('Asia/Colombo');
                    if(count($this->tickets) > 0){
                    foreach($this->tickets as $ticket) { ?>
                        <div class="ticket-row curve ticket">
                            <input style="float:left;" type="checkbox" name="tickets[]" id="tickets" value="<?php echo $ticket->id; ?>"/>
                            <div class="span2">
                                <span class="ticket-date">Created :
                                    <?php /*echo date("M jS Y", strtotime($ticket->created_date)); */
                                        $createdDate = new DateTime($ticket->created_date);
                                        $now = new DateTime();
                                        $interval = $createdDate->diff($now);
                                        if(($interval->days) > 0)
                                        {
                                            echo $interval->days,' days';
                                        }
                                        elseif(($interval->h) > 0)
                                        {
                                            echo $interval->h,' hours';
                                        }
                                        elseif(($interval->i) > 0)
                                        {
                                            echo $interval->i,' minutes';
                                        }
                                        elseif(($interval->s) > 0)
                                        {
                                            echo $interval->s,' seconds';
                                        }
                                    ?> ago.
                                </span>
                                </br>
                                <span class="ticket-id curve">#<?php echo $ticket->id; ?></span></br>

                                <span class="ticket-response-count"><?php echo $ticket->responses;?></span></br><span class="grey"><?php echo $this->translate("Responses");?></span>
                            </div>
                            <div class="span8">
                                <div class="ticket-title"><?php echo $ticket->subject;?></div>
                                <div class="ticket-description curve"><?php echo ($this->LimitWords($ticket->description,60)) ? $this->LimitWords($ticket->description,60).'...' : $ticket->description; ?></div>
                                <div class="misc">
                                    <div class="misc-left">
                                        <!--<span class="attachment"><a href="<?php /*echo '/tickets/attachment/'.$ticket->attachment_name;*/?>" target="_blank"><?php /*echo $ticket->attachment_name; */?></a></span>-->
                                        <span class="attachment"><a href="<?php echo '/ticket/download-attachement/file/'.$ticket->attachment_name;?>" ><?php echo $ticket->attachment_name; ?></a></span>
                                        </br>
                                        <span class="status <?php echo strtolower($ticket->status);?>"><?php echo $this->translate($ticket->status);?></span>
                                        <span class="type <?php echo strtolower($ticket->type);?>"><?php echo $this->translate($ticket->type);?></span>
                                        <span class="priority <?php echo strtolower($ticket->priority);?>"><?php echo $this->translate($ticket->priority);?></span>
                                    </div>
                                    <div class="misc-right">
                                        <span class="ticket-more"><a href="<?php echo PROJECT_BASEPATH;?>ticket/single-ticket/id/<?php echo $ticket->id; ?>"><?php echo $this->translate('Details');?> </a></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } } else {
                        echo $this->translate('No Tickets Found');
                    } ?>
                </form>
                <?php echo $this->paginationControl($this->tickets, 'Sliding', 'partials/paginator.phtml'); ?>
            </div>
        </div>
    </div>
</div>