<center>
    <h1> :( An application error has occured.  </h1>
    <h2> Don't worry - our code monkeys have been woken up and are scrambling to fix this problem. </h2>
    <br/>
    <h4> You can try clicking your browser's back button, cross your fingers and try again or go back to the <a href="/">homepage</a></h4>   
    <br/>
    <h5> Boring technical information:
    <br/>    
        <?=$this->layout()->content ?>
    </h5>
    

    
</center>
