<!-- Start Top Navigation -->
        <div id="top_nav">
            <!-- Start Drop Down Menu -->
            <ul class="sf-menu">
                <li>
                        <a class="m" href="/">Dashboard</a>
                </li>
               
                <li><a class="m" href="#">Account</a>
                    <ul>
                        <li><a href="/user/account/#technical">My Account</a></li>
                        <li><a href="/user/logout">Logout</a></li>
                    </ul>
                </li>
                <li>
                    <a class="m" href="#">Settings</a>
                    <ul>
                        <li><a href="/settings">Web Settings</a></li>
                        <li><a href="#">CP Panel Settings</a>
                            <ul>
                                <li><a href="/settings/cp-home-customize">Home Page Customize</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
               <li><a class="m" href="#">Customization</a>
                    <ul>
                        <li><a href="/category/customize/">Category</a></li>
                        <li><a href="/featured-product/filter/">App Feature</a></li>
                    </ul>
                </li>                
                <li><a class="m" href="#">Banners</a>
                    <ul>
                        <li><a href="/banner/create/">New Banner</a></li>
                        <li><a href="/banner/">All Banners</a></li>
                    </ul>
                </li>
                <li><a class="m" href="#">Users</a>
                    <ul>
                        <li><a href="/user/registerd-users/">Registered Users</a></li>
                    </ul>
                </li>
                <li><a class="m" href="/product">Apps</a>                    
                </li>
            </ul>
            </ul>
            <!-- End Drop Down Menu -->
            <!--  support / contacts link -->
            <ul class="support_nav">
              <li>
                <a rel="facebox" href="/index/help">
                  Have a Question ?
                </a>
              </li>
            </ul>
            </div>
            <!-- End Top Navigation -->