 <div id="main_right_pane">
  <?=$this->paginationControl($this->paginator, 'Sliding', 'partials/product_category_block.phtml', array('baseUrl' => $this->baseUrl)); ?>
 
 
 	<?=$this->partial('partials/product.phtml', array('products' => $this->products,  'partnerId' => $this->partnerId, 'appStoreAppid' => $this->appStoreAppid, 'nexLinkerUrl' => $this->nexLinkerUrl, 'loggedUser' => $this->loggedUser ,'chap_id' => $this->chap_id, 'showPlatformIcons' => $this->showPlatformIcons) );?>
 
	
	<div style="clear: both;"></div>
	
	<?=$this->paginationControl($this->paginator, 'Sliding', 'partials/product_category_block.phtml', array('baseUrl' => $this->baseUrl)); ?>
	
 <?php if(32034211 == $this->chap_id ): ?>
    
<a href="http://c.afftrx.com/?s=1736129&cr=2414875" target="_blank">
<img src="http://r.mobpartner.mobi?s=1736129&cr=2414875" />
</a>

<?php endif; ?>


 <?php if(21134111 == $this->chap_id ): ?>
    

<a href="http://c.afftrx.com/?s=1736105&cr=2479685">
<img src="http://r.mobpartner.mobi?s=1736105&cr=2479685" />
</a>
 

<?php endif; ?>



<script type="text/javascript"
src="http://ads.appia.com/v2/getAds.jsp?siteId=1111&placementId=1&adTypeId=4&t=1426864310&androidId=&idfa=&aaid=">
</script>

</div>
