<script type="text/javascript">
    
var $form_validation = jQuery.noConflict();

$form_validation(document).ready(function(){
	//global vars	
	
	var form = $form_validation("#frm_feedback");
	var name = $form_validation("#txtName");
	var nameInfo = $form_validation("#nameInfo");	
	var email = $form_validation("#txtEmail");
	var emailInfo = $form_validation("#emailInfo");
	var comment = $form_validation("#txtMessage");
	var commentInfo = $form_validation("#messageInfo");
	
	//On blur
	name.blur(validateName);
	email.blur(validateEmail);
	comment.blur(validateComment);
	
	//On key press
	name.keyup(validateName);
	email.keyup(validateEmail);
	comment.keyup(validateComment);

	//On Submitting
	form.submit(function(){					 
					
		if(validateName() & validateEmail() & validateComment())
		{			
			return true;
		}
		else
		{
			return false;
		}
	});
	
	//validation functions
	function validateEmail(){
		//testing regular expression
		var a = $form_validation("#txtEmail").val();
		var filter = /^[a-zA-Z0-9]+[a-zA-Z0-9_.-]+[a-zA-Z0-9_-]+@[a-zA-Z0-9]+[a-zA-Z0-9.-]+[a-zA-Z0-9]+.[a-z]{2,4}$/;
		//if it's valid email
		if(filter.test(a)){
			email.removeClass("error");
			emailInfo.text("");
			emailInfo.removeClass("error");
			return true;
		}
		//if it's NOT valid
		else{
			email.addClass("error");
			emailInfo.text("Plaes enter Valid E-mail!");
			emailInfo.addClass("error");
			return false;
		}
	}
	function validateName(){
		//if it's NOT valid
		if(name.val().length < 4){
			name.addClass("error");
			nameInfo.text("Please fill the Name!");
			nameInfo.addClass("error");
			return false;
		}
		//if it's valid
		else{
			name.removeClass("error");
			nameInfo.text("");
			nameInfo.removeClass("error");
			return true;
		}
	}
		
	function validateComment(){
		//if it's NOT valid
		if(comment.val().length < 10){
			comment.addClass("error");
			commentInfo.text("Please add your Commenst with more than 10 letters!");
			commentInfo.addClass("error");
			return false;
		}
		//if it's valid
		else{
			comment.removeClass("error");
			commentInfo.text("");
			commentInfo.removeClass("error");
			return true;
		}
	}
	
});
</script>

<div id="main_right_pane">


    <div class="inr_tabs_wrapper">
        <div class="inr_tab_bar"><span class="inr_brdcrtxt_pur">+</span> 
            <span class="inr_brdcrtxt_grey"><?php echo $this->translate("Add a Ticket");?></span>
        </div>
        <div class="box_content_top"></div>
        <div class="box_content_middle">
            <div class="inrtab_selection_top inner_content" >

                <div id="form_wrapper">
                    
                    <?php if(!empty($this->messages_sent)) : ?>
                        <div class="text_bg"> 
                            <p><?= $this->messages_sent ?></p>
                        </div> 
                    <?php endif; ?>
                    <form name="frm_ticketing" id="frm_ticketing" method="post" action="/ticketing/">
                        <!-- form col3-->	
                        

                            <div align="right" class="required_wrapper">
                                <span class="required_txt_style"><?php echo $this->translate("Required Information");?> (</span><span class="form_font_red">*</span><span class="required_txt_style">)</span>
                            </div>

                            <br /><br />
                            <div class="form_col3_class1">
                                <div class="form_col3_class1_left">
                                    <span class="form_font_tel"><?php echo $this->translate("Subject");?></span>
                                    <span class="form_font_red">*</span>
                                </div>

                                <div class="form_col3_class1_right">
                                    <input type="text" id="txtSubject" name="txtSubject" class="input_smallresult_form" style="width:90%">
                                    <br />
                                    <span id="nameInfo"></span>
                                </div>
                            </div>

                            <div class="form_col3_class1">
                                <div class="form_col3_class1_left">
                                    <span class="form_font_tel"><?php echo $this->translate("Type");?></span>
                                    <span class="form_font_red">*</span>
                                </div>

                                <div class="form_col3_class1_right">
                                    <select name="selectType">
                                        <option>-- Select Type --</option>
                                        <option value="Question">Question</option>
                                        <option value="Incident">Incident</option>
                                        <option value="Problem">Problem</option>
                                        <option value="Feature">Feature</option>
                                    </select>
                                    <br />
                                    <span id="nameInfo"></span>
                                </div>
                            </div>	

                            <div class="form_col3_class1">
                                <div class="form_col3_class1_left">
                                    <span class="form_font_tel"><?php echo $this->translate("Priority");?></span>
                                    <span class="form_font_red">*</span>
                                </div>

                                <div class="form_col3_class1_right">
                                    <select name="selectPriority">
                                        <option>-- Select Priority --</option>
                                        <option value="Low">Low</option>
                                        <option value="Medium">Medium</option>
                                        <option value="High">High</option>
                                        <option value="Urgent">Urgent</option>
                                    </select>
                                    <br />
                                    <span id="nameInfo"></span>
                                </div>
                            </div>
                           
                            <div class="form_col3_class1">
                                <div class="form_col3_class1_left">
                                    <span class="form_font_tel"><?php echo $this->translate("Description");?></span>
                                    <span class="form_font_red">*</span>
                                </div>

                                <div class="form_col3_class1_right">
                                    <textarea id="txtDescrition" name="txtDescrition" cols="35" rows="7" class="txt_area_innerform_calvalthe" style="width:90%"></textarea>
                                    <br />
                                    <span id="messageInfo"></span>
                                </div>
                            </div>	

                            <div class="form_col3_class1">
                                <div class="form_col3_class1_left">
                                    <span class="form_font_tel"><?php echo $this->translate("Attachment");?></span>
                                    <span class="form_font_red">*</span>
                                </div>

                                <div class="form_col3_class1_right">
                                    <input type="file" name="txtAttachment"/>
                                    
                                    <br />
                                    <span id="nameInfo"></span>
                                </div>
                            </div>

                            
                            <div align="right" class="submit_btn_wrapper">

                                <input type="submit" id="btn_submit" name="btn_submit" value="<?php echo $this->translate("SEND");?>" class="partner_btn">
                                <input type="reset" id="btn_reset" name="btn_reset" value="<?php echo $this->translate("RESET");?>" class="partner_btn">
                                
                           </div>

                        
                    </form>	<!-- form col6-->	

                </div>



            </div>



        </div>

    </div>
    <!-- box one-->


    <div style="clear: both;"></div>

</div>

