<?php echo $this->translate("Please enter First Name");?>
<?php echo $this->translate("Please enter Last Name");?>
<?php echo $this->translate("Please enter your Email address");?>
<?php echo $this->translate("Please enter a valid Email address for your Email");?>
<?php echo $this->translate("Please enter your Phone Number");?>
<?php echo $this->translate("Mobile Number cannot be less than 10 digits");?>
<?php echo $this->translate("Please enter your Password");?>
<?php echo $this->translate("Please confirm your Password");?>
<?php echo $this->translate("Password not Matching");?>
<?php echo $this->translate("This Email already exists");?>
<?php echo $this->translate("You have completed your registration successfully");?>
<?php echo $this->translate("This Phone Number already exists");?>
<?php echo $this->translate("A verification SMS has been sent to your mobile. Please use the given verification code to complete your registration");?>
<?php echo $this->translate("Verification failed. verification code is incorrect");?>
<?php echo $this->translate("You successfully completed the registration process");?>
<?php echo $this->translate("Already Verified User");?>
<?php echo $this->translate("The username or password you entered is incorrect");?>
<?php echo $this->translate("You have not verified your account. A verification SMS has been sent to your mobile . Please use the given verification code or get it resent by clicking below \"Resend verification code\" to verify your account");?>
<?php echo $this->translate("Please enter a valid username");?>
<?php echo $this->translate("Please enter your username and password");?>
<?php echo $this->translate("Please enter your Mobile Number");?>
<?php echo $this->translate("Mobile Number not Matching");?>
<?php echo $this->translate("This number has already been used. Please try another");?>
<?php echo $this->translate("Mobile number changed successfully");?>
<?php echo $this->translate("Please confirm your Mobile Number");?>
<?php echo $this->translate("Password reset successfully");?>
<?php echo $this->translate("Please enter your Email");?>
<?php echo $this->translate("User not found registered with this email");?>
<?php echo $this->translate("Mobile number not registered");?>
<?php echo $this->translate("You have requested to change password. A verification SMS has been sent to your mobile. Please use the given verification code to verify");?>
<?php echo $this->translate("Please enter your Verification Code");?>
<?php echo $this->translate("Verification code is incorrect");?>
<?php echo $this->translate("Mobile Number not found for this user");?>
<?php echo $this->translate("Email not found for this user");?>
<?php echo $this->translate("You have requested to resend verification code. A verification SMS has been sent to your mobile. Please use the given verification code to verify your account");?>
<?php echo $this->translate("Newest");?>
<?php echo $this->translate("Top Free");?>
<?php echo $this->translate("Top Paid");?>
<?php echo $this->translate("Top Downloads");?>
<?php echo $this->translate("Free");?>
<?php echo $this->translate("Download");?>
<?php echo $this->translate("Description");?>
<?php echo $this->translate("Screenshots");?>
<?php echo $this->translate("Account");?>
<?php echo $this->translate("Updates");?>
<?php echo $this->translate("Help");?>
<?php echo $this->translate(" HOME");?>
<?php echo $this->translate("Premium");?>
<?php echo $this->translate("Login");?>
<?php echo $this->translate("Email");?>
<?php echo $this->translate("Password");?>
<?php echo $this->translate("Sign Up");?>
<?php echo $this->translate("Sign In");?>
<?php echo $this->translate("Forgot Password?");?>
<?php echo $this->translate("Downloaded Apps");?>
<?php echo $this->translate("Reset Password");?>
<?php echo $this->translate("Sorry! Couldn't find Apps matching your search criteria");?>

<?php echo $this->translate("Change Mobile");?>
<?php echo $this->translate("Terms & Conditions");?>
<?php echo $this->translate("Mobile Number");?>
<?php echo $this->translate("New Password");?>
<?php echo $this->translate("Confirm Password");?>
<?php echo $this->translate("Confirm Mobile Number");?>
<?php echo $this->translate("Staff Picks");?>
<?php echo $this->translate("Top Premium");?>
<?php echo $this->translate("Buy");?>
<?php echo $this->translate("Download Started");?>
<?php echo $this->translate("Later");?>
<?php echo $this->translate("Updates are apps that have a newer version. This is either added functionalities, bug fixes or improvements");?>
<?php echo $this->translate("Please use this verification code 888555 to complete your registration. \"MTN CONGO APP STORE\"");?>
<?php echo $this->translate("Please use this verification code 888666 to verify your mobile number. \"MTN CONGO APP STORE\"");?>
<?php echo $this->translate("Please use this verification code 8886656 to complete the password resetting process. \"MTN CONGO APP STORE\"");?>
<?php echo $this->translate("Please use this verification code 7878778 as you requested. \"MTN CONGO APP STORE\"");?>
<?php echo $this->translate("Next");?>
<?php echo $this->translate("Previous");?>
<?php echo $this->translate("For any customer service issues, bugs in the app downloaded, difficulty downloading or purchases made by mistake please contact us at this email :");?>
<?php echo $this->translate("We will get back to you within 48 hours.");?>
<?php echo $this->translate("Verify");?>
<?php echo $this->translate("Resend Verification Code");?>
<?php echo $this->translate("First Name");?>
<?php echo $this->translate("Last Name");?>
<?php echo $this->translate("Phone Number");?>
<?php echo $this->translate("Register");?>
<?php echo $this->translate("Verification Code");?>
<?php echo $this->translate("Change Mobile Number");?>
<?php echo $this->translate("Forgot Password");?>
<?php echo $this->translate("Request");?>
<?php echo $this->translate("Please use this verification code");?>
<?php echo $this->translate("to complete your registration.");?>
<?php echo $this->translate("to verify your mobile number.");?>
<?php echo $this->translate("to complete the password resetting process.");?>
<?php echo $this->translate("as you requested.");?>
<?php echo $this->translate("Payment was unsuceessful");?>
<?php echo $this->translate("Have an Issue?");?>
<?php echo $this->translate("Featured Apps");?>
<?php echo $this->translate("BOOKS & REFERENCE");?>
<?php echo $this->translate("eBooks");?>
<?php echo $this->translate("Audio books");?>
<?php echo $this->translate("Reference/Dictionaries");?>
<?php echo $this->translate("Religion");?>
<?php echo $this->translate("Comics/Manga");?>
<?php echo $this->translate("GAMES");?>
<?php echo $this->translate("Arcade");?>
<?php echo $this->translate("Cards");?>
<?php echo $this->translate("Action/Strategy");?>
<?php echo $this->translate("Role Playing/Multiplayer");?>
<?php echo $this->translate("Logic/Puzzle/Trivia");?>
<?php echo $this->translate("Casino/Cards/Betting");?>
<?php echo $this->translate("Sports");?>
<?php echo $this->translate("TOOLS & PRODUCTIVITY");?>
<?php echo $this->translate("Utilities/Synchronization");?>
<?php echo $this->translate("Organizers/Clocks/Desktop");?>
<?php echo $this->translate("Internet/WAP");?>
<?php echo $this->translate("Device Tools");?>
<?php echo $this->translate("Security/Backup");?>
<?php echo $this->translate("Developers/DB");?>
<?php echo $this->translate("Office Productivity");?>
<?php echo $this->translate("Graphic Tools");?>
<?php echo $this->translate("BUSINESS & FINANCE");?>
<?php echo $this->translate("Accounts/Tax");?>
<?php echo $this->translate("Stocks/Finance");?>
<?php echo $this->translate("Inventory/Sales");?>
<?php echo $this->translate("Currency/Convertors");?>
<?php echo $this->translate("TRAVEL & GPS");?>
<?php echo $this->translate("GPS/Maps");?>
<?php echo $this->translate("Weather");?>
<?php echo $this->translate("Search");?>
<?php echo $this->translate("Translation/Language");?>
<?php echo $this->translate("NEWS & SPORTS");?>
<?php echo $this->translate("News/Magazines");?>
<?php echo $this->translate("Sports/Teams");?>
<?php echo $this->translate("RSS");?>
<?php echo $this->translate("SOCIAL NETWORKS & MESSAGING");?>
<?php echo $this->translate("IM/SMS/Email/VOIP");?>
<?php echo $this->translate("Social Networks");?>
<?php echo $this->translate("Dating");?>
<?php echo $this->translate("Blogs/Images");?>
<?php echo $this->translate("MUSIC & AUDIO");?>
<?php echo $this->translate("Podcasts");?>
<?php echo $this->translate("MP3/Music");?>
<?php echo $this->translate("Radios/Players");?>
<?php echo $this->translate("Lyrics/Bands");?>
<?php echo $this->translate("VIDEO & TV");?>
<?php echo $this->translate("TV/Shows");?>
<?php echo $this->translate("Movies/Trailers");?>
<?php echo $this->translate("players/Converters");?>
<?php echo $this->translate("LIFESTYLE & WELLNESS");?>
<?php echo $this->translate("Astro");?>
<?php echo $this->translate("Food/Recipes");?>
<?php echo $this->translate("Art/Fashion");?>
<?php echo $this->translate("Hobbies/Pets");?>
<?php echo $this->translate("Health/Diet/Fitness");?>
<?php echo $this->translate("Shopping/Brands");?>
<?php echo $this->translate("EDUCATION & ELEARNING");?>
<?php echo $this->translate("Medical");?>
<?php echo $this->translate("Language");?>
<?php echo $this->translate("Kids/Early learning");?>
<?php echo $this->translate("University");?>
<?php echo $this->translate("Law");?>
<?php echo $this->translate("GOODIES & ENTERTAINMENT");?>
<?php echo $this->translate("Wallpaper/Screensavers");?>
<?php echo $this->translate("Personlization/Skins");?>
<?php echo $this->translate("Humor/Jokes");?>
<?php echo $this->translate("Ringtones");?>
<?php echo $this->translate("THEMES");?>
<?php echo $this->translate("Techno");?>
<?php echo $this->translate("Rock");?>
<?php echo $this->translate("Calm");?>
<?php echo $this->translate("Arts & Crafts");?>
<?php echo $this->translate("Animation");?>
<?php echo $this->translate("Category  Not Found");?>
<?php echo $this->translate("You are not signed in yet");?>
<?php echo $this->translate("No Match Found");?>
<?php echo $this->translate("Ok");?>
<?php echo $this->translate("You haven't log in yet ? Please log in.");?>
<?php echo $this->translate("Apps");?>
<?php echo $this->translate("No Data Found");?>
<?php echo $this->translate("Downloading");?>
<?php echo $this->translate("You are here");?>
<?php echo $this->translate("Have an Issue?");?>
<?php echo $this->translate("Login to add a ticket");?>
<?php echo $this->translate("Please add a valid email");?>
<?php echo $this->translate("Please add a valid password");?>
<?php echo $this->translate("Click here to reset it");?>
<?php echo $this->translate("Home");?>
<?php echo $this->translate("Products, Logos and Companies mentioned herein are trademarks or trade names of their respective owners and therefore copyrighted.");?>
<?php echo $this->translate("Add your own review");?>
<?php echo $this->translate("MTN Iran App Store");?>
<?php echo $this->translate("IRR");?>
<?php echo $this->translate(" APP");?>
<?php echo $this->translate("Paid");?>
<?php echo $this->translate("Mobile Number or password is incorrect");?>
<?php echo $this->translate("Mobile");?>
<?php echo $this->translate("Newest Apps");?>
<?php echo $this->translate("Search Results for");?>
<?php echo $this->translate("Enter the email address you signed up with and we'll email you a link to reset your password");?>
<?php echo $this->translate("Reset your password");?>
<?php echo $this->translate("Required infromation");?>
<?php echo $this->translate("Enter Captcha");?>
<?php echo $this->translate("Powered by");?>
<?php echo $this->translate("The security key wasn't entered correctly");?>
<?php echo $this->translate("Please try again");?>
<?php echo $this->translate("Reset");?>
<?php echo $this->translate("Info");?>
<?php echo $this->translate("The email you supplied was not found");?>
<?php echo $this->translate("Username or password is incorrect");?>
<?php echo $this->translate("Add a ticket");?>
<?php echo $this->translate("View my ticket");?>
<?php echo $this->translate("Subject");?>
<?php echo $this->translate("Type");?>
<?php echo $this->translate("Priority");?>
<?php echo $this->translate("Select Type");?>
<?php echo $this->translate("Question");?>
<?php echo $this->translate("Incident");?>
<?php echo $this->translate("Problem");?>
<?php echo $this->translate("Feature");?>
<?php echo $this->translate("Select Priority");?>
<?php echo $this->translate("Low");?>
<?php echo $this->translate("Medium");?>
<?php echo $this->translate("High");?>
<?php echo $this->translate("Urgent");?>
<?php echo $this->translate("Your ticket submitted successfully");?>
<?php echo $this->translate("Your response submitted successfully");?>
<?php echo $this->translate("Responces");?>
<?php echo $this->translate("No Response found");?>
<?php echo $this->translate("Reply");?>
<?php echo $this->translate("Submit");?>
<?php echo $this->translate("Platforms");?>
<?php echo $this->translate("PLEASE SELECT YOUR PLATFORM");?>
<?php echo $this->translate("Register on");?>
<?php echo $this->translate("PLEASE SELECT");?>
<?php echo $this->translate("Android App");?>
<?php echo $this->translate("Mobile Web");?>
<?php echo $this->translate("Sorry! Couldn't find Apps matching your search criteria");?>
<?php echo $this->translate("The mobile number or password you entered is incorrect");?>
<?php echo $this->translate("Open");?>
<?php echo $this->translate("View my Tickets");?>
<?php echo $this->translate("ticket");?>
<?php echo $this->translate("Please add a subject");?>
<?php echo $this->translate("Please select a type");?>
<?php echo $this->translate("Please select a priority");?>
<?php echo $this->translate("dashboard");?>
<?php echo $this->translate("Please add your Commenst with more than 10 letters");?>
<?php echo $this->translate("Page not found. (404 - Not Found)");?>
<?php echo $this->translate("No apps found under this category");?>
<?php echo $this->translate("For any customer service issues, bugs in the app downloaded, difficulty downloading or purchases made by mistake please add a ticket. We will get back to you within 48 hours.");?>
<?php echo $this->translate("Please enter your Mobile Number and password");?>
<?php echo $this->translate("This app is only available in the following languages ");?>
<?php echo $this->translate("This app-store will be supported for <<MTN Iran>> subscribers only ");?>
<?php echo $this->translate("The MTN Iran App Store has a rich selection of the best iranian and global apps just for you. Each app is tested for quality, malware and scams. For convenience, Paid apps can be purchased using your phone credit.");?>
<?php echo $this->translate("Selected Device");?>
<?php echo $this->translate("To download this app you need to install <<MTN Iran App Store>> on your Android device and sign in. ");?>
<?php echo $this->translate("If you want to install <<MTN Iran App Store>> on your phone use following methods. ");?>
<?php echo $this->translate("Type in your email address and we will email it to you");?>
<?php echo $this->translate("Point your mobile browser to the following link");?>
<?php echo $this->translate("Scan the QR code using your phone to be directly taken to the app page");?>
<?php echo $this->translate("Do not have a QR code reader? Get one free ");?>
<?php echo $this->translate("To download this app you need to visit the following URL ");?>
<?php echo $this->translate("User ID is blocked ");?>
<?php echo $this->translate("User ID not found ");?>
<?php echo $this->translate("User ID is blocked ");?>
<?php echo $this->translate("Authentication failed ");?>
<?php echo $this->translate("Failed to get MSISDN Status ");?>
<?php echo $this->translate("App Store");?>
<?php echo $this->translate("Responses");?>
<?php echo $this->translate("User ID is blocked");?>
<?php echo $this->translate("User ID not found");?>
<?php echo $this->translate("User ID is blocked");?>
<?php echo $this->translate("Authentication failed");?>
<?php echo $this->translate("Failed to get MSISDN Status");?>
<?php echo $this->translate("Invalid MSISDN or password");?>
<?php echo $this->translate("Please enter a prepaid MSISDN");?>
<?php echo $this->translate("My Tickets");?>
<?php echo $this->translate("View Tickets");?>
<?php echo $this->translate("Premium app download restricted to post paid users");?>