<div class='home_info_block' style="width:87%">
<div class="title"><h3>Administration Options</h3></div>
<div class="box">
  <div class="txt">
    <ul class="icon_list">

      <li>
        <p><a href="/user/account/#technical"><img src="/chap/assets/img/content/icon_list/cp_myaccont.png" alt=""/>
                <br />My Account</a></p>
      </li>
      <li>
        <p><a href="/settings"><img src="/chap/assets/img/content/icon_list/cp_settings.png" alt=""  />
                <br />Settings</a></p>
      </li>
      <li>
        <p><a href="/category/customize"><img src="/chap/assets/img/content/icon_list/cp_cat.png" alt="" />
                <br />Categories </a></p>
      </li>
      <li>
        <p> <a href="/featured-product/filter"><img src="/chap/assets/img/content/icon_list/cp_featured.png" alt="" />
                <br />Featured </a></p>
      </li>
      <li>
        <p><a href="/user/registerd-users"><img src="/chap/assets/img/content/icon_list/cp_reg_users.png" alt=""/>
                <br />Users</a></p>
      </li>
      <li>
        <p><a href="/banner"><img src="/chap/assets/img/content/icon_list/banners.png" alt=""/>
                <br />Banners</a></p>
      </li>

      <li>
        <p><a href="/product"><img src="/chap/assets/img/content/icon_list/cp_apps.png" alt=""/>
                <br />Apps</a></p>
      </li>
    </ul>
    <div class="clear"></div>
        </div>
      </div>

      