<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 5/22/14
 * Time: 1:13 PM
 * To change this template use File | Settings | File Templates.
 */

$chapId = Zend_Auth::getInstance()->getIdentity()->id;

?>
<script type="text/javascript" language="javascript">
    //Validation
    $(document).ready(function() {
        $("#qelasy-grades").validate();
        $('#accordion-category').accordion({
            collapsible: true,
            heightStyle: "content",
            active : 'none'
        });

        $('.category-chk').click(function(e){
            var sub_chk = $(this).parent().next('div').find('.category-chk-sub');
            if(this.checked) {                              //
                sub_chk.each(function(){                    //
                    this.checked = true;                    //
                });                                         //
            } else {                                        //  adds check all & deselect all functionality for parent category selector
                sub_chk.each(function(){                    //
                    this.checked = false;                   //
                });                                         //
            }
            e.stopPropagation();
        });

        $('.category-chk-sub').click(function(e){
            var parent_chk = $(this).parent().prev('h3').find('.category-chk');
            if(this.checked) {                              //
                parent_chk.each(function(){                 //
                    this.checked = true;                    //  check the parent category selector if any of the sub-category is checked
                });                                         //
            }                                               //
        });
    });
</script>

<?php
/*
$categoryModel = new Pbo_Model_QelasyGradeCategories();
foreach($this->categories as $category){
    $subCategories = $categoryModel->getSubCategoriesForParentCategory($category->id,($this->grade)?$this->grade->id:null);
    Zend_Debug::dump($subCategories);
}

die('END');
*/?>

<?php if (count($this->successMessages)) { ?>
    <div class="notification success png_bg">
        <div>

            <?php foreach ($this->successMessages as $message) { ?>

                <li><?php echo $this->escape($message); ?></li>

            <?php } ?>

        </div>
    </div>
<?php } ?>

<div class="content-box">
    <div class="content-box-header">
        <h3 style="cursor: s-resize;"><?php echo $this->title; ?></h3>
        <div id="icon_wrapper">
            <a href="/qelasy/qelasy-grades" alt="List Qelasy Grade" class="button">List Grades</a>
        </div>
    </div>
    <div class="content-box-content">
        <div style="width:99%;float: right;">
            <?php
                $id = '';if($this->grade) { $id = '/id/'.$this->grade->id; }
                //$page = '';if($this->pageNumber) { $page = '/page/'.$this->page; }
            ?>
            <form method="post" action="/qelasy/<?php echo $this->action.$id;?>" id="qelasy-grades" name="qelasy-grades" class="pbo-admin-form">

                <!--<p>
                    <label>Grade Name<span class="mendatory_fileds">*</span></label>
                    <input id="grade-name" name="grade-name" class="text-input small-input required" type="text" value="<?php /*echo isset($this->grade->name) ? utf8_decode($this->grade->name) : '' ; */?>" />
                </p>-->

                <!--<p>
                    <label>Grade Description<span class="mendatory_fileds">*</span></label>
                    <input id="grade-description" name="grade-description" class="text-input small-input required" type="text" value="<?php /*echo isset($this->grade->description) ? $this->grade->description : ''; */?>" />
                </p>-->
                <?php

                if($this->action == 'add-qelasy-grade'){ ?>
                    <div id="accordion-category">
                        <?php
                        $categoryModel = new Pbo_Model_Categories();
                        foreach($this->categories as $category){ ?>
                            <h3 class="category-header"><input name="category[]" class="category-chk" value="<?php echo $category->id;?>" type="checkbox" /><?php echo $category->name;?></h3>
                            <div class="sub-category">
                                <?php
                                $subCategories = $categoryModel->getSubCategoriesForParentCategory($category->id);
                                foreach($subCategories as $subCategory){ ?>
                                    <input name="category[]" class="category-chk-sub" value="<?php echo $subCategory->id;?>" type="checkbox" /><?php echo $subCategory->name;?><br/>
                                <?php } ?>
                            </div>
                        <?php } ?>
                    </div>
                <?php } elseif($this->action == 'edit-qelasy-grade'){ ?>
                    <div id="accordion-category">
                        <?php
                        $categoryModel = new Pbo_Model_QelasyGradeCategories();
                        foreach($this->categories as $category){  ?>
                            <h3 class="category-header"><input name="category[]" class="category-chk" value="<?php echo $category->id;?>" type="checkbox" <?php if(isset($category['grade_category_status']) && ($category['grade_category_status'] == 1)){ echo 'checked'; }?> /><?php echo $category->name;?></h3>
                            <div class="sub-category">
                                <?php
                                $subCategories = $categoryModel->getSubCategoriesForParentCategory($category->id, $this->grade->id, $chapId,1);
                                foreach($subCategories as $subCategory){
                                    if($subCategory->status){ ?>
                                        <input name="category[]" class="category-chk-sub" value="<?php echo $subCategory->id;?>" type="checkbox" <?php if($subCategory->grade_category_status == 1){ echo 'checked'; } ?>/><?php echo $subCategory->name;?><br/>
                                    <?php }
                                } ?>
                            </div>
                        <?php } ?>
                    </div>
                <?php } ?>

                <div style="float:left; width:60px; position: relative; left: 15px">
                    <input style="position: relative; top: 5px" type="submit" value="Submit" class="button" name="add-all" id="add-all"/>
                </div>

            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#1').addClass('current');
</script>