<?php 
    $this->headLink()->appendStylesheet( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/css/jquery.ketchup.css');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.js');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.messages.js');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.validations.basic.js');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'admin/assets/js/admin.js');
?>

<?php $rule  = $this->rule;?>
<div class="title">
    <h3>Create Product Rule</h3>
</div>

<div class="box">
    <div class="txt">
        <div class="content_box">
            <?php if(isset($this->errors) && !empty($this->errors)) : ?>
                <?php foreach ($this->errors as $message) : ?>
                <div class="message error" style="display: block;">
                    <p><?=$message ?></p>
                </div>
                <?php endforeach; ?>
            <?php endif; ?>
            
            <fieldset>
                 <form class='form_validate' method="post" accept-charset="UTF-8" action="/product-user-rule/index/chapId/<?=$this->chapId?>">
                 <p>
                    <label for='name'>Name</label>
                    <input value='<?=$rule->name?>' type='text' id='name' name='name' class='txt-input medium validate(required, rangelength(1,300))'>
                 </p>
                 
                 <p>
                    <label for='note'>Note</label>
                    <textarea name="note" id="note" class="txt-input medium"><?=$rule->note?></textarea>
                 </p>
                 
                 <p>
                    <label for='type'>Filter</label>
                    <select name='filter' id='filter'>
                        <?php $opts = array('CP', 'CUSTOM', 'PLATFORM', 'PRICE', 'CATEGORY');?>
                        <?php foreach ($opts as $opt) : ?>
                            <option <?php if ($rule->filter == $opt):?>selected='selected'<?php endif;?> value='<?=$opt?>'><?=$opt?></option>
                        <?php endforeach; ?>                    
                        
                    </select>
                 </p>
                 
                  <p>
                    <label for='type'>Type</label>
                    <select name='type' id='type'>
                        <option <?php if ($rule->type == 'INCLUSION'):?>selected='selected'<?php endif;?> value='INCLUSION'>Inclusion</option>
                        <option <?php if ($rule->type == 'EXCLUSION'):?>selected='selected'<?php endif;?> value='EXCLUSION'>Exclusion</option>
                    </select>
                 </p>
 
                 <input type='hidden' value='<?php echo $rule->id ?>' name='id'>
                 <input type='hidden' value='<?php echo $this->chapId ?>' name='user_id'>
                 <p><input type="submit" class="txt-input small" value="Save Rule" id="submit" name="submit"></p>
                 </form>
            </fieldset>
        </div>
        </div>
</div>    


        <div class="title">
            <h3 style="cursor: s-resize;">Current Rules</h3>
        </div>
        <div class="box">
    <div class="txt">
        <table cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Filter</th>
                    <th>Value</th>
                    <th>&nbsp</th>
                </tr>
            </thead>
        <?php if (count($this->rules)): $class = '';?>
            <tbody>
        <?php foreach ($this->rules as $item): $class = ($class == 'alt') ? '' : 'alt' ;?>
            <tr>
                <td class='<?=$class?>'><?=$item->id?></td>
                <td class='<?=$class?>'><a href='/product-user-rule/index/chapId/<?=$this->chapId?>/ruleId/<?=$item->id?>'><?=$item->name?></a></td>
                <td class='<?=$class?>'><?=$item->type?></td>
                <td class='<?=$class?>'><?=$item->filter?></td>
                <td class='<?=$class?>'><?=$item->value?></td>
                <td class='<?=$class?>'>
                    &nbsp;&nbsp;&nbsp; 
                    <a href='/product-user-rule/delete/chapId/<?=$this->chapId ?>/ruleId/<?=$item->id ?>' class='del_conf'>Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
            </tbody>
        <?php endif; ?>
        </table>
    </div>
</div>


