<div id='analytics_menu'>
    <div class="title">
        <h3><?php echo $this->translate("Filters");?></h3>
    </div>
    <div class="box">
        <div class="txt">
            <form class='date_filter'  method='post'>
                <input type='text' size='12' class='date txt-input texthint' data-hint='from' name='from_view' id='from_view' value='<?=$this->startTimeView?>'> 
                <input type='text' size='12' class='date txt-input texthint' data-hint='until' name='to_view' id='to_view' value='<?=$this->endTimeView?>'>
                <select class='select-input' id='date-range'>
                    <option selected="selected" value=''>[<?php echo $this->translate("SELECT RANGE");?>]</option>
                    <option value='604800'><?php echo $this->translate("Last Week");?></option>
                    <option value='2678400'><?php echo $this->translate("Last Month");?></option>
                    <option value='15768000'><?php echo $this->translate("Last 6 Months");?></option>
                </select>
                <button class='button'><?php echo $this->translate("Filter");?></button>
            </form>
        </div>
    </div>
    
 
    <div class="box">
        <div class="txt">
          <!--   <input type='text' class='txt-input texthint' data-hint="type in an app name for filtering" id='app_search' name='app_search' size='33'>  -->
            <ul class="icon_list">
                <li>
                    <p>
                        <a href="<?php echo CP_PROJECT_BASEPATH;?>analytics/dashboard/<?php echo $this->queryString?>">
                            <img width='32' height='32' src="<?php echo PROJECT_BASEPATH;?>cp/assets/img/content/icon_list/dashboard.png" alt="dashboard"/>
                            <br><?php echo $this->translate("Dashboard");?>
                        </a>
                    </p>
                </li>
           
                <li>
                    <p>
                        <a href="<?php echo CP_PROJECT_BASEPATH;?>analytics/downloads/<?php echo $this->queryString?>">
                            <img width='32' height='32' src="<?php echo PROJECT_BASEPATH;?>cp/assets/img/content/icon_list/download.png" alt="downloads"/>
                            <br><?php echo $this->translate("Downloads");?>
                        </a>
                    </p>
                </li>
            
                <li>
                    <p>
                        <a href="<?php echo CP_PROJECT_BASEPATH;?>analytics/devices/<?php echo $this->queryString?>">
                            <img width='32' height='32' src="<?php echo PROJECT_BASEPATH;?>cp/assets/img/content/icon_list/phone_touch.png" alt="mobile device"/>
                            <br><?php echo $this->translate("Devices");?>
                        </a>
                    </p>
                </li>
                
                <li>
                    <p>
                        <a href="<?php echo CP_PROJECT_BASEPATH;?>analytics/builds/<?php echo $this->queryString?>">
                            <img width='32' height='32' src="<?php echo PROJECT_BASEPATH;?>cp/assets/img/content/icon_list/ico_software.gif" alt="operating system"/>
                            <br><?php echo $this->translate("OS");?>
                        </a>
                    </p>
                </li>
                
                
                <li>
                    <p>
                        <a href="<?php echo CP_PROJECT_BASEPATH;?>analytics/views/<?php echo $this->queryString?>">
                            <img width='32' height='32' src="<?php echo PROJECT_BASEPATH;?>cp/assets/img/content/icon_list/view_icon.png" alt="downloads"/>
                            <br><?php echo $this->translate("Views");?>
                        </a>
                    </p>
                </li>
        
                  <li>
                    <p>
                        <a href="<?php echo CP_PROJECT_BASEPATH;?>sanalytics/revenue/<?php echo $this->queryString?>">
                            <img width='32' height='32' src="<?php echo PROJECT_BASEPATH;?>cp/assets/img/content/icon_list/revenue.png" alt="revenue"/>
                            <br><?php echo $this->translate("Revenue");?>
                        </a>
                    </p>
                </li>
                
                <li class='coming_soon'>
                    <p>
                        <a href="/#<?php echo $this->queryString?>">
                            <img width='32' height='32' src="<?php echo PROJECT_BASEPATH;?>/cp/assets/img/content/icon_list/nexpage.jpg" alt="neXpager"/>
                            <br>neXpager
                        </a>
                    </p>
                </li>
                
                <li class='coming_soon'>
                    <p>
                        <a href="/#<?php echo $this->queryString?>">
                            <img width='32' height='32' src="<?php echo PROJECT_BASEPATH;?>/cp/assets/img/content/icon_list/sources.png" alt="traffic sources"/>
                            <br><?php echo $this->translate("Sources");?>
                        </a>
                    </p>
                </li>
            </ul>
            <div class='clear'></div>
        </div>
    </div>
</div>