<tr> 
    <td style="width:25%">
        <?= $this->product->name; ?>
    </td>
    <td>
        $<?= $this->product->price; ?>
    </td>
    <td>
        <?php echo $this->translate($this->product->product_type); ?>
    </td>
    <td>
        <?php 
        
        if ($this->product->status == 'PENDING_APPROVAL' ) {
        	
        	echo $this->translate("Pending Approval");
        	
        }
        else {
        if($this->product->status == 'APPROVED')    {
        	
        	 echo $this->translate("Approved");
        	
        }
        else
        {
            $buildCount = $this->PublishNow($this->product->id);
  
            if(($this->product->status == 'INCOMPLETE') and (count($buildCount) > 0) )
            {

               ?> <div class="txt-input small submit button" style="width: 65px; text-align: center;">
                       <a href="<?php echo PROJECT_BASEPATH;?>product/publish/id/<?=$this->product->id;?>" 
                       title="<?php echo $this->translate("Click on Publish Now,  if you have completed uploading your application. So neXva content managers get notification about your application to review and publish.");?>" style="color:#ffffff"> <?php echo $this->translate("Publish Now");?> </a>
                      </div>
        
            <?php 

        
            }
            else
            {
            	
                echo $this->translate("Incomplete");
            	
            }
        
        
        } 
        
        }
        ?>
    </td>
    <td>
    <?//=$this->GetCreatedDate($this->product->id, $this->product->created_date);?>
    <?=(isset($this->product->updated_date) && !empty($this->product->updated_date))?$this->product->created_date.'/ '.$this->product->updated_date:$this->product->created_date?>
    </td>

    <td>
    <?php
        $session = new Zend_Session_Namespace('chap');

        if(('ycoins' == $session->chap->username) && ($this->product->inapp == 1)) {  ?>
        <a href="<?php echo PROJECT_BASEPATH;?>product/edit/id/<?= $this->product->id ?>" ><img alt="<?php echo $this->translate("Edit");?>" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/edit.png" title="<?php echo $this->translate("Edit");?>"></a>
        <a href="<?php echo PROJECT_BASEPATH;?>product/display/id/<?= $this->product->id ?>"><img alt="<?php echo $this->translate("View");?>" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/view.png" title="<?php echo $this->translate("View");?>"></a>
        <a href="/build/show/id/<?= $this->product->id ?>"><img alt="Add <?php echo $this->translate("Add Build");?>" src="/cp/assets/img/global/icons/plugin_add.png" title="<?php echo $this->translate("Add Builds");?>"></a>
        <a href="<?php echo PROJECT_BASEPATH;?>product/translate/id/<?= $this->product->id ?>" ><img alt="<?php echo $this->translate("Add Translation");?>" src="/cp/assets/img/global/icons/font_add.png" title="<?php echo $this->translate("Add Translations");?>"></a>
        <a onclick="return confirm('Are you sure you want to delete?')" href="<?php echo PROJECT_BASEPATH;?>product/delete/id/<?= $this->product->id ?>"><img alt="Delete" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/delete.png" title="<?php echo $this->translate("Delete");?>"></a>
        <a href="<?php echo PROJECT_BASEPATH;?>product/embeded/id/<?= $this->product->id ?>" rel='facebox'><img alt="Share" src="/cp/assets/img/global/icons/transmit_go.png" title="<?php echo $this->translate("Share");?>"></a>
        <a href="<?php echo PROJECT_BASEPATH;?>product/edit/id/<?php echo $this->product->id; ?>/6/4"><img src="/cp/assets/img/global/icons/channel-icon.png" alt="Support Channel" title="<?php echo $this->translate("Support Channel");?>"/></a>
    <?php } elseif($this->product->inapp != 1) { ?>
        <a href="<?php echo PROJECT_BASEPATH;?>product/edit/id/<?= $this->product->id ?>" ><img alt="<?php echo $this->translate("Edit");?>" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/edit.png" title="<?php echo $this->translate("Edit");?>"></a>
        <a href="<?php echo PROJECT_BASEPATH;?>product/display/id/<?= $this->product->id ?>"><img alt="<?php echo $this->translate("View");?>" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/view.png" title="<?php echo $this->translate("View");?>"></a>
        <a href="/build/show/id/<?= $this->product->id ?>"><img alt="<?php echo $this->translate("Add Build");?>" src="/cp/assets/img/global/icons/plugin_add.png" title="<?php echo $this->translate("Add Builds");?>"></a>
        <a href="<?php echo PROJECT_BASEPATH;?>product/translate/id/<?= $this->product->id ?>" ><img alt="<?php echo $this->translate("Add Translation");?>" src="/cp/assets/img/global/icons/font_add.png" title="<?php echo $this->translate("Add Translations");?>"></a>
        <a onclick="return confirm('Are you sure you want to delete?')" href="<?php echo PROJECT_BASEPATH;?>product/delete/id/<?= $this->product->id ?>"><img alt="Delete" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/delete.png" title="<?php echo $this->translate("Delete");?>"></a>
        <a href="<?php echo PROJECT_BASEPATH;?>product/embeded/id/<?= $this->product->id ?>" rel='facebox'><img alt="Share" src="/cp/assets/img/global/icons/transmit_go.png" title="<?php echo $this->translate("Share");?>"></a>
        <a href="<?php echo PROJECT_BASEPATH;?>product/edit/id/<?php echo $this->product->id; ?>/6/4"><img src="/cp/assets/img/global/icons/channel-icon.png" alt="Support Channel" title="<?php echo $this->translate("Support Channel");?>"/></a>
    <?php } else { ?>
        <a href="<?php echo PROJECT_BASEPATH;?>product/selectedit/id/<?= $this->product->id ?>" ><img alt="<?php echo $this->translate("Edit");?>" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/edit.png" title="<?php echo $this->translate("Edit");?>"></a>
        <a href="<?php echo PROJECT_BASEPATH;?>product/display/id/<?= $this->product->id ?>/inapp/1"><img alt="<?php echo $this->translate("View");?>" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/view.png" title="<?php echo $this->translate("View");?>"></a>
        <a href="<?php echo PROJECT_BASEPATH;?>product/translate/id/<?= $this->product->id ?>" ><img alt="Add Translation" src="/cp/assets/img/global/icons/font_add.png" title="<?php echo $this->translate("Add Translations");?>"></a>
        <a onclick="return confirm('Are you sure you want to delete?')" href="<?php echo PROJECT_BASEPATH;?>product/delete/id/<?= $this->product->id ?>"><img alt="Delete" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/delete.png" title="<?php echo $this->translate("Delete");?>"></a>    
    <?php } ?>
    <?php if (isset($this->nexpagerState) && $this->nexpagerState == 1) : ?>
        <?php
            $url    = 'http://' . Zend_Registry::get('config')->nexva->application->mobile->url . "/nexpage/app/id/{$this->product->user_id}/appid/{$this->product->id}/";
        ?>
        <a href="<?=$url?>" onclick='prompt(<?php echo $this->translate("This URL is your neXpager mobile app page for this content.")?>, this.href); return false;'>
            <img alt="neXpager app page" src="/cp/assets/img/global/icons/arrow_in.png" title="<?php echo $this->translate("neXpager app page");?>">
        </a>
    <?php endif?>
    </td>

    <td>
      <?php  if($this->product->inapp != 1 ):  ?>
        <!--
        <div style="float:left;padding-left:20px;">
                <a style='padding: 0 5px;' href='/analytics/views/pro_id/<?= $this->product->id ?>'>
                    <img src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/viewed_stats.png"  alt="Product views" title="Product views"/>
                </a>
        </div>
         -->
        <div style="float:left;">
            <div style="float:left;padding-top:5px;padding-left:35px;"><img src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/viewed_stats.png"  alt="Product views" title="<?php echo $this->translate("Product views");?>"/></div><div style="float:left;width:40px;padding:4px;"><?= $this->ViewStats($this->product->id);?></div>
            <div style="float:left;padding-top:5px;"><img src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/download_stats.png" alt="Downloads count" title="<?php echo $this->translate("Downloads count");?>"/> </div><div style="float:left;width:40px;padding:4px;"><?= $this->DownloadStats($this->product->id);?></div>
        </div>
        
        
      <?php else:?>
       
        <div style="float:left;padding-left:20px;">
        
        N/A
        
        </div>
        
      <?php endif;?>   
    </td>
</tr>