<!-- Start Wrap -->
<div id="wrap" class="fixed" style="margin-top:20px;">
    <div id="content">
        <div class="title">
            <h3><?php echo $this->translate($this->window_title);?></h3>
        </div>
        <div class="box">
            <div class="txt">

                <div class="tab-table">


                    <div class="tab-forms">

                        <!-- Start Form -->
                        <form method="POST" action="" name="user_register" id="user_register">
                            <fieldset>
                              <?= $this->render('/partials/message.phtml'); ?>
                               
                                <p>
                                    <label><?php echo $this->translate("White-label name");?></label>
                                    <small><?php echo $this->translate("This would be your white-label name.eg: yourname.nexva.com");?></small>
                                    <input name="username" autocomplete="off" id="username"  type="text" class="txt-input small" value="<?php echo $this->user['username']; ?>"     />
                                </p>
                                
                                <p>
                                    <label><?php echo $this->translate("E-mail");?></label>
                                    <input autocomplete="off" name="email" id="email" type="text" class="txt-input small validate(required(Email field),email)" value="<?php echo $this->user['email']; ?>"/>
                                </p>

                                <p>
                                    <label><?php echo $this->translate("password");?></label>
                                    <input autocomplete="off" name="password" id="password"   type="password" class="txt-input small " value=""/>
                                </p>


                                <p>
                                    <label><?php echo $this->translate("Retype password");?></label>
                                    <input autocomplete="off" name="retypepassword" id="retypepassword" type="password" class="txt-input small" value="" />
                                </p>


                                <?if($this->captcha != ''): ?>
                                <p>
                                    
                                   <img src="/captcha/<?=$this->captcha?>.png" alt="Please refresh this page if you don't see a valid secirity code" />
                                  <br />
                                  <label><?php echo $this->translate("Enter the security key you see inside the image");?></label>
                                  <input autocomplete="off" name="captchaval" id="captchaval" type="text" class="txt-input small validate(required(Security code))" value="" style="width:200px;"/>
                                   <input type="hidden" name="captcha_id" value="<?=$this->captcha?>" />
                                </p>
                                <?endif; ?>

                                <span style="float:left;">
                                    <input type="submit" class="button submit" name="submit" id="submit" value="<?php echo $this->translate($this->button_value);?>" />
                                </span>
                            </fieldset>
                        </form>
                        <!-- End Form -->
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>