<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 7/8/14
 * Time: 4:30 PM
 * To change this template use File | Settings | File Templates.
 */
?>

<form method="post" action="https://www.pagali.cv/pagali_app/index.php?r=pgPaymentInterface/ecommercePayment" id="api-form" name="api-form" >
<!--<form method="post" action="http://api.nexva-v2-dev.com/testone/cb" id="api-form" name="api-form" >-->
    <p>
        <label>id_ent</label>
        <input id="id_ent" name="id_ent" type="text" />
    </p>

    <p>
        <label>id_temp</label>
        <input id="id_temp" name="id_temp" type="text" />
    </p>

    <p>
        <label>order_id</label>
        <input id="order_id" name="order_id" type="text" />
    </p>

    <p>
        <label>currency code</label>
        <input id="currency code" name="currency code" type="text" />
    </p>

    <p>
        <label>total</label>
        <input id="total" name="total" type="text" />
    </p>

    <p>
        <label>return</label>
        <input id="return" name="return" type="text" />
    </p>

    <p>
        <label>notify</label>
        <input id="notify" name="notify" type="text" />
    </p>

    <p>
        <label>item_name</label>
        <input id="item_name" name="item_name" type="text" />
    </p>

    <p>
        <label>quantity</label>
        <input id="quantity" name="quantity" type="text" />
    </p>

    <p>
        <label>item_number</label>
        <input id="item_number" name="item_number" type="text" />
    </p>

    <p>
        <label>amount</label>
        <input id="amount" name="amount" type="text" />
    </p>

    <p>
        <label>total_item</label>
        <input id="total_item" name="total_item" type="text" />
    </p>

    <input type="submit" value="Submit" class="button" name="add-all" id="add-all"/>

</form>