<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="en-us" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

        <?= $this->headTitle($this->title); ?>

        <!-- Core Stylesheet -->
        <link href="/cp/assets/css/core.css" media="screen" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" type="text/css" href="/cp/assets/css/red.css" title="styles3" media="screen" />

        <!-- Javascript Files -->
        <script type="text/javascript" src="/cp/assets/js/jquery-1.3.2.min.js"></script>
        <script type="text/javascript" src="/cp/assets/js/jquery-ui-1.7.2.custom.min.js"></script>
        <script type="text/javascript" src="/cp/assets/js/hoverIntent.js"></script>
        <script type="text/javascript" src="/cp/assets/js/superfish.js"></script>
        <script type="text/javascript" src="/cp/assets/js/jquery.wysiwyg.js"></script>
        <script type="text/javascript" src="/cp/assets/js/jquery-stylesheetToggle.js"></script>
        <script type="text/javascript" src="/cp/assets/js/forestcp.js"></script>

        <link href="<?php echo PROJECT_BASEPATH;?>common/js/jquery/plugins/ketchup-plugin/css/jquery.ketchup.css" media="screen" rel="stylesheet" type="text/css"/>
        <script type="text/javascript" src="<?php echo PROJECT_BASEPATH;?>common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.js"></script>
        <script type="text/javascript" src="<?php echo PROJECT_BASEPATH;?>common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.messages.js"></script>
        <script type="text/javascript" src="<?php echo PROJECT_BASEPATH;?>common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.validations.basic.js"></script>




        <!--[if IE 6]>
        <link href="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/css/ie6.css" media="screen" rel="stylesheet" type="text/css" />
        <script src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/js/DD_belatedPNG_0.0.8a-min.js"></script>
        <script>
          /* EXAMPLE */
          DD_belatedPNG.fix('.logo img, .message, table img');

          /* string argument can be any CSS selector */
        </script>
        <![endif]-->

    </head>
    <body>

        <!-- Start Wrap -->
        <div id="wrap" class="login">
            <div id="content">
                <div class="inner">

                    <noscript>
                        <!-- Show message when javascript is not enabled -->
                        <div class="message error">
                            <p>Javascript is needed for this site work properly. <br />Please <a href="http://browsehappy.com/" title="Upgrade to a better browser">upgrade</a> your browser or <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Enable Javascript in your browser">enable</a> Javascript to navigate the interface properly.</p>
                        </div>
                    </noscript>

                    <?php echo $this->layout()->content ?>

                </div>
            </div>
        </div>
        <!-- End Wrap -->
    </body>
</html>

