<div id="main_right_pane">


    <div class="inr_tabs_wrapper">
        <div class="inr_tab_bar"><span class="inr_brdcrtxt_pur">+</span> 
            <span class="inr_brdcrtxt_grey">  <?= isset($this->pageDetails->title) ? $this->pageDetails->title: ''; ?> </span>
        </div>
        <div class="box_content_top"></div>
        <div class="box_content_middle">
            <div class="inrtab_selection_top inner_content">

                <?= isset($this->pageDetails->page_text) ? $this->pageDetails->page_text: ''; ?>

            </div>

        </div>

    </div>
    <!-- box one-->

    <div style="clear: both;"></div>


</div>

