 <div id="main_right_pane">
 
  <?=$this->paginationControl($this->paginator, 'Sliding', 'partials/product_category_block.phtml', array('baseUrl' => $this->baseUrl)); ?>
 
	<?=$this->partial('partials/product.phtml', array('products' => $this->products,  'partnerId' => $this->partnerId, 'appStoreAppid' => $this->appStoreAppid, 'nexLinkerUrl' => $this->nexLinkerUrl, 'loggedUser' => $this->loggedUser,'chap_id' => $this->chap_id, 'showPlatformIcons' => $this->showPlatformIcons) );?>
	
	<div style="clear: both;"></div>
	
	<?=$this->paginationControl($this->paginator, 'Sliding', 'partials/product_category_block.phtml', array('baseUrl' => $this->baseUrl)); ?>
	
</div>

