<?php 
    $this->headLink()->appendStylesheet( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/css/jquery.ketchup.css');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.js');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.messages.js');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.validations.basic.js');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'admin/assets/js/admin.js');
?>
<?php $this->headScript()->appendFile($this->Cdn('site_assets').'/web/nexlinker/shadowbox/shadowbox.js');?>
<?php $this->headLink()->appendStylesheet($this->Cdn('site_assets').'/web/nexlinker/shadowbox/shadowbox.css'); ?>
<?php $this->headScript()->captureStart();?>
    $(function() {
        Shadowbox.init({
            'troubleElements' : ["select", "object", "embed"]
        });
    });
<?php $this->headScript()->captureEnd();?>
<?php 
    $section  = $this->section;
    $phrase  = $this->phrase;
?>
<div class="title">
    <h3 style="cursor: s-resize;">Phrases for <?php echo $section->name?></h3>
</div>

<div class="box">
    <div class="txt">
        <div class="content_box">
            <?php if(isset($this->errors) && !empty($this->errors)) : ?>
                <?php foreach ($this->errors as $message) : ?>
                <div class="message error" style="display: block;">
                    <p><?=$message ?></p>
                </div>
                <?php endforeach; ?>
            <?php endif; ?>
            
            <fieldset>
                 <form class='form_validate' method="post" accept-charset="UTF-8" action="/section/save-phrase">
                 <p>
                    <label for='name'>Phrase Name</label>
                    <input value='<?=$phrase->name?>' type='text' id='name' name='name' class='txt-input medium validate(required, rangelength(1,128))'>
                 </p>
                 
                 
                 <input type='hidden' value='<?php echo $phrase->id ?>' name='id'>
                 <input type='hidden' value='<?php echo $section->id ?>' name='section_id'>
                 <p><input type="submit" class="txt-input small" value="Save Phrase" id="submit" name="submit"></p>
                 </form>
            </fieldset>
        </div>
        </div>
</div>    


        <div class="title">
            <h3>Phrases</h3>
        </div>
        <div class="box">
    <div class="txt">
        <table cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Default</th>
                    <th>Last Updated</th>
                    <th>&nbsp</th>
                </tr>
            </thead>
        <?php if (count($this->phrases)): $class = '';?>
            <tbody>
        <?php foreach ($this->phrases as $item): $class = ($class == 'alt') ? '' : 'alt' ;?>
            <tr>
                <td class='<?=$class?>'><?=$item->id?></td>
                <td class='<?=$class?>'><a href='<?php echo ADMIN_PROJECT_BASEPATH;?>section/add-language/id/<?php echo $item->id ?>' rel='shadowbox;height=530;width=600'><?=$item->name?></a></td>
                <td class='<?=$class?>'><?=substr(strip_tags($item->value), 0, 100)?></td>
                <td class='<?=$class?>'><?=$item->updated?></td>
                <td class='<?=$class?>'>
                    <a href='<?php echo ADMIN_PROJECT_BASEPATH;?>section/view/id/<?php echo $section->id ?>/phraseid/<?php echo $item->id ?>'>Edit</a>
                    &nbsp;&nbsp;&nbsp; 
                    <a href='<?php echo ADMIN_PROJECT_BASEPATH;?>section/delete-phrase/sectionid/<?php echo $section->id?>/id/<?php echo $item->id ?>' class='del_conf'>Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
            </tbody>
        <?php endif; ?>
        </table>
    </div>
</div>
 