<div class="title">
    <h3><?php echo $this->translate("Oops! Well this is embarassing");?></h3>
</div>
<div class='box'>
    <div class='txt'>
    <p>
        <strong><?php echo $this->translate("Looks like something is broken.");?> </strong>
    </p>
    
    <p>
        <?php echo $this->translate("Click on the back button on your browser and try to continue");?>
        <?php echo $this->translate("what you were doing.");?> <br> <br>
        <?php echo $this->translate("If this error happens again, please click on the link below to report this issue.");?>
    </p>
    <p><a href='/user/report'><?php echo $this->translate("Report this issue");?></a></p>
    </div>
    
    <?php if (APPLICATION_ENV != 'production') : ?>
    <div class='txt'>
            <br><br>
                <hr>
                
                  <h2><?php echo $this->translate($this->message) ?></h2>
                
                  <?php if (isset($this->exception)): ?>
                
                  <h3><?php echo $this->translate("Exception information:");?></h3>
                  <p>
                      <b><?php echo $this->translate("Messages");?>:</b> <?php echo $this->translate($this->exception->getMessage()) ?>
                  </p>
                
                  <h3><?php echo $this->translate("Stack trace");?>:</h3>
                  <pre><?php echo $this->exception->getTraceAsString() ?>
                  </pre>
                
                  <h3><?php echo $this->translate("Request Parameters");?>:</h3>
                  <pre><?php echo var_export($this->request->getParams(), true) ?>
                  </pre>
                  <?php endif ?>
          </div>
    <?php endif;?>
</div>

