<div class="title">
    <h3 style="cursor: s-resize;">Create Content</h3>
    <div title="content_box" class="selector">
    </div>
</div>

<div class="box">
    <div class="txt">
        <!--
        Showing error/info messages
        TODO : add UL to display statys/ error and info messages.
        -->
              <div id="content_box">
            <!-- Basic product details -->
            <div class="tab-basic">
                <?=$this->form_basic_inapp?>
            </div>
        </div>
    </div>
</div>
