<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>neXva - Mobile. Reloaded</title>
    <link href="<?=$this->cdn('site_assets')?>/web/css/clean.css" rel="stylesheet" type="text/css" />
    <!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <?php echo $this->headStyle() ?>
</head>
<body id="home">
    <?=$this->layout()->content?>
</body>
</html>