<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
        <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
        <meta http-equiv="Pragma" content="no-cache">
        <meta http-equiv="Expires" content="0">
<link rel="shortcut icon" href="<?=$this->cdn('site_assets')?>/images/favicon.ico" />
<meta http-equiv="Content-Script-Type" content="text/javascript" /> 
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<?php if ($this->headTitle() != '<title></title>') : ?>
    <?=$this->headTitle();?>
<?php else : ?>
    <title>neXva.com - neXlinker</title>
<?php endif; ?>
<?=$this->headMeta()?>


<link rel="shortcut icon" href="<?=$this->cdn('site_assets')?>/images/favicon.ico" />
<!-- ////////////////////////////////// -->
<!-- //      Start Stylesheets       // -->
<!-- ////////////////////////////////// -->
<?php if($this->chapId == 23045){ //MTN Iran need a different styles for RTL ?> 
<link href="<?=$this->cdn('site_assets')?>/web/css/popup-iran.css" rel="stylesheet" type="text/css" />
<?php } else { ?>
<link href="<?=$this->cdn('site_assets')?>/web/css/popup.css" rel="stylesheet" type="text/css" />
<?php } ?>

<!-- ////////////////////////////////// -->
<!-- //      Javascript Files        // -->
<!-- ////////////////////////////////// -->
<script type="text/javascript" src="<?=$this->cdn('jquiry')?>"></script>

<?php echo $this->headLink() ?>
<?php echo $this->headScript() ?>


        <script type='text/javascript'>
        $(document).ready(function(){
            $('a.del_conf').click(function(){
                return confirm('Are you sure you want to delete this item?');
            })
        });
            
        </script>
</head>
<body>
<div id="wrapper">
    <div id="container">
             <?php if (isset($this->flashMessages) && !empty($this->flashMessages)) : ?>
                <div id='messageContainer'>
                    <ul id='messages_top' class='messages'>
                        <?php
                        //$flashMessenger = $this->_helper->FlashMessenger->getMessages();;
                        
                        if(isset($messages) && is_array($messages)) :
                            foreach ($messages as $key=>$value): ?>
                                <li><?=$value?></li>
                            <?endforeach;?>
                        <?endif;?>
                    </ul>
                </div>
            <?php endif; ?>
            <?=$this->layout()->content?>
    </div><!-- end #container-->    
</div>

</body>
</html>
