<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!--
*****************************************************************************************************
Are you a UI engineer?

Think you can improve what you see here? (Yes, we know there is a lot here that can be improved).

Drop us a line: jahufar+htmlsrc@nexva.com with a portfolio of your best work and we'll talk.
*****************************************************************************************************
-->
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        
        <?php if ($this->headTitle() != '<title></title>') : ?>
            <?=$this->headTitle();?>
        <?php else : ?>
            <title>neXva.com - mobile reloaded</title>
        <?php endif; ?>
        
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">

       <?=$this->headMeta()?>
       <?php $this->siteVersion()->appendVersion(); //versioning resources?>

        <link href="http://nexva.com/oembed/?url=http%3A//nexva.com/1121" rel="alternate" type="text/xml+oembed" />
        <link href="http://nexva.com/nexlinker/oembed/?url=http%3A//nexva.com/1121" rel="alternate" type="application/json+oembed" />

        <link type="text/css" rel="stylesheet" href="<?=$this->cdn('site_assets')?>/web/nexva.css<?=$this->VER?>">
        <link type="text/css" rel="stylesheet" href="<?=$this->cdn('site_assets')?>/web/css/common.css<?=$this->VER?>">
        <!--[if IE ]>
            <link type="text/css" rel="stylesheet" href="/web/ie_tweaks.css<?=$this->VER?>">
        <![endif]-->  
        
        <link type="text/css" rel="stylesheet" href="<?=$this->cdn('site_assets')?>/web/jquery-ui.nexva.css<?=$this->VER?>">

        <?php echo $this->headLink() ?>
        
        <script type="text/javascript" src="<?=$this->cdn('jquiry')?>"></script> 
        <script type="text/javascript" src="<?=$this->cdn('jquiryui')?>"></script>
        <script type="text/javascript">
            if(!window.jQuery) {
                document.write('<script src="<?=$this->cdn('site_assets')?>/web/js/jquery-1.5.1.min.js">\x3C/script>');
                document.write('<script src="<?=$this->cdn('site_assets')?>/web/js/jquery-ui-1.8.10.min.js">\x3C/script>')
            }
        </script>
        <script type="text/javascript" src="<?=$this->cdn('site_assets')?>/web/nexva.js<?=$this->VER?>"></script>
        <script type="text/javascript" src="<?=$this->cdn('site_assets')?>/web/js/common.js<?=$this->VER?>"></script>
        
        
        <script language="javascript">
            var __FIRST_LOAD    = true;
            $(document).ready(function() {
                searchSgHide ();
                hideOverlays();
                setBackground ();
      
                
                $("#phoneSelect input:button").button();
                //startSession ();

                
                <?php if ($this->showDevicePage) : ?>
                selectUserPhone();
                <?php else:?>
                __FIRST_LOAD    = false;
                <?php endif; ?>
            });
        </script>
        
        
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <div id="background">
            <div id="page">
                <!-- header start -->
                <div id="title">
                    <div id='logo'>
                    <h1 style='margin:0;'>
                        <a href="/">Nexva</a>
                    </h1>
                    </div>
                    <div id="primaryLinks">
                        <ul class="btn" id="primary">
                            <li><a id="primary_about" href="<?php echo CP_PROJECT_BASEPATH;?>">ABOUT</a></li>
                            <li><a id="primary_adv" href="<?php echo CP_PROJECT_BASEPATH;?>content-providers">DEVELOPERS</a></li>
                            <li><a id="primary_signup" href="<?php echo PROJECT_BASEPATH;?>user/login">SIGNUP</a></li>
                            <li><a id="primary_contact" href="<?php echo CP_PROJECT_BASEPATH;?>contact">CONTACT</a></li>
                        </ul>
                    </div>
                     <div id='searchContainer' class='rounded'>
                        <form action='/search/index/q' method="get">
                                <input class='rounded suggest' type="text" id="q" name="q" value="<?=$this->escape($this->keywords)?>" title='search all apps' autocomplete="off">
                                <input type="submit" class='rounded button' value="Search" id="searchBtn" name="search">
                        </form>
                    </div>
                </div>
                <!-- header end -->

                <?php
                    $vars   = array("messages" => $this->flashMessages, 'errors' => $this->flashErrors, 'notices' => $this->flashNotices);
                    echo $this->partial('parts/web/messages.phtml', $vars);  
                ?>


                <div class="blkLeft">
                    <div class="block">
                        <div class="blkContent">
                            <div id="#userBlock">
                                <div class="blockContent">
                                    <?
                                        if( isset (Zend_Auth::getInstance()->getIdentity()->id) ) {
                                            $userMeta = new Model_UserMeta();
                                            $userMeta->setEntityId(Zend_Auth::getInstance()->getIdentity()->id);
                                        }
                                    ?>

                                    <div id="usrGreeting"><h2>Welcome <?=(isset ($userMeta) ? $userMeta->FIRST_NAME : 'to neXva.com.')?></h2></div>
                                    <ul id="usrPhones">
                                        <?if (isset($this->selectedDevices) && count($this->selectedDevices) > 0): ?>
                                            <?foreach($this->selectedDevices as $device): ?>

                                        <li class="usrPhoneBlk">
                                            <a href="javascript:removeUserPhone('<?=$device['id']?>');" class="closeBtn"></a>
                                            <a class="phoneInfo"><img alt="<?=$device['phone']?>" src="<?=$device['image']?>"><?=$device['phone']?></a>
                                        </li>

                                            <?endforeach;?>
                                        <?endif;?>

                                    </ul>
                                   <div id="usrPhoneSelect">
                                        <div id='selDeviceWrap'>
                                        <div id='selDeviceCont'>
                                            <p id='selDeviceText' class='rounded'>
                                                You haven't selected a device yet. Click the link below to select a device.
                                                (Click to dismiss)
                                            </p>
                                            <span></span>
                                       </div>
                                       </div>
                                       
                                        
                                        <p id="usr_phone_str">
                                            <img alt="user phone" src="<?=$this->cdn('site_assets')?>/web/images/unknown_phone_icon.png">
                                            <a id="usr_phone" href='#phoneSelect'>
                                                <?if (isset($this->selectedDevices) && count($this->selectedDevices) > 0): ?>
                                                Filtering apps by <?=count($this->selectedDevices)?> phone(s). Click here to add another phone.
                                                <?else: ?>
                                                <span class='noDeviceNotice ui-state-highlight ui-corner-all'>
                                                    No device selected. Click to select a mobile device
                                                    <script type="text/javascript">
                                                        $(document).ready(function(){
                                                            if (!__FIRST_LOAD) {showNoDeviceSelectedNotice();}
                                                        });
                                                    </script>
                                                </span>
                                                <?endif;?>
                                             </a>   
                                            </p>
                                            <div class='clear'></div>
                                    </div>
                                    <?=$this->partial('parts/web/login_box.phtml', array("item" => array())); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="leftBlock">
                       
                        <?=$this->render('parts/web/category.phtml');?>
                    </div>
                </div>

                <?=$this->layout()->content?>
                
                <div class='clear'></div>
                <div id="footer">&copy; Copyright <?=date('Y'); ?> neXva . All rights reserved .
                    Products, logos and companies mentioned herein are trademarks or trade names of their respective owners and therefore copyright.                     
                    <br/>                    
                </div>
                    
            </div>
        </div>
        <?php echo $this->partial('parts/web/device_selector.phtml')?>        
        <?php echo $this->partial('parts/analytics.phtml')?>    
    </body>
</html><!--