<h2 class="font-size-16"><?php echo $this->translate("Add a ticket");?></h2>

<div class="ui-grid-solo">
    
    <!-- Displays Success Message/s -->
<?php if (count($this->successMessages)) : ?>

    <div class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text" style="white-space: normal">

            <?php foreach ($this->successMessages as $message) : ?>

                <?php echo $this->escape($this->translate($message)); ?>

            <?php endforeach; ?>

      </span></span>
    </div>

<?php endif; ?>


<!-- Displays Error Message/s -->
<?php if (count($this->errorMessages)) : ?>

    <div class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text" style="white-space: normal">

            <?php foreach ($this->errorMessages as $message) : ?>

                <?php echo $this->escape($this->translate($message)); ?>

            <?php endforeach; ?>

        </span></span>
    </div>

<?php endif; ?>

</div>

<div class="ui-body ui-body-c"><?php //echo 'dsdsds'.$this->txtSubject; die();?>
        <form name="frm_ticketing" id="frm_ticketing" method="post" action="/ticket/insert-ticket" data-ajax="false">
    
        <fieldset data-role="fieldcontain">
            <label for="txtSubject"><?php echo $this->translate("Subject");?> <span class="red"> *</span></label>
            <input type="text" name="txtSubject" id="txtSubject" class="required" minlength="" value="<?= (isset($this->txtSubject)) ? $this->txtSubject : ''; ?>" >
        </fieldset>
            
        <fieldset data-role="fieldcontain">
            <label for="selectType"><?php echo $this->translate("Type");?> <span class="red"> *</span></label>
             <select name="selectType" id="selectType" data-theme="d">
                <option value="">- <?php echo $this->translate("Select Type");?> -</option>
                <?php foreach($this->optTypes as $optType) : ?>
                    <option value="<?= $optType ?>" <?= (isset($this->selectType) && ($this->selectType == $optType)) ? 'selected' : ''; ?>><?= $this->translate($optType) ?></option>
                <?php endforeach;?>
            </select>
        </fieldset>
    
         <fieldset data-role="fieldcontain">
            <label for="selectPriority"><?php echo $this->translate("Priority");?> <span class="red"> *</span></label>
            <select name="selectPriority" id="selectPriority" data-theme="d">
                <option value="">- <?php echo $this->translate("Select Priority");?> -</option>
                <?php foreach($this->optPrioritys as $optPriority) : ?>
                    <option value="<?= $optPriority ?>" <?= (isset($this->selectPriority) && ($this->selectPriority == $optPriority)) ? 'selected' : ''; ?>><?= $this->translate($optPriority) ?></option>
                <?php endforeach;?>
            </select>
        </fieldset>
            
        <fieldset data-role="fieldcontain">
            <label for="txtDescription"><?php echo $this->translate("Description");?> <span class="red"> *</span></label>
            <textarea name="txtDescription" id="txtDescription"><?= (isset($this->txtDescription)) ? $this->txtDescription : ''; ?></textarea>
        </fieldset>

        <input type="submit" value="<?php echo $this->translate("Submit");?>">
    
    </form>
</div>