<?php echo $this->translate("Click Here");?>
<?php echo $this->translate("Apps");?>
<?php echo $this->translate("Categories");?>
<?php echo $this->translate("collection");?>
<?php echo $this->translate("Featured");?>
<?php echo $this->translate("Free Collection");?>
<?php echo $this->translate("Most");?>
<?php echo $this->translate("Need Help?");?>
<?php echo $this->translate("Premium Collection");?>
<?php echo $this->translate("Top");?>
<?php echo $this->translate("Top Collection");?>
<?php echo $this->translate("viewed collection");?>

<?php echo $this->translate("Search");?>
<?php echo $this->translate("Select Your Device");?>
<?php echo $this->translate("Selecting a device helps us filter apps that are compatible with your handset.");?>
<?php echo $this->translate("Start typing the name of your device");?>

<?php echo $this->translate("No Device Selected");?>
<?php echo $this->translate("Click To Select A Mobile Device");?>

<?php echo $this->translate("Click on thumbnail to zoom");?>
<?php echo $this->translate("Screenshots");?>

<?php echo $this->translate("Nexva All Rights Reserved.");?>
<?php echo $this->translate("Products, Logos and Companies mentioned herein are trademarks or  trade names of their respective owners and therefore copyrighted.");?>
<?php echo $this->translate("Register");?>
<?php echo $this->translate("Sign In");?>
<?php echo $this->translate("Welcome");?>
<?php echo $this->translate("You Are Here");?>
<?php echo $this->translate("Buy ");?>
<?php echo $this->translate("Buy");?>
<?php echo $this->translate("Description");?>
<?php echo $this->translate("Free");?>
<?php echo $this->translate("Free Download");?>
<?php echo $this->translate("Price :");?>
<?php echo $this->translate("Price : ");?>
<?php echo $this->translate("Rate :");?>
<?php echo $this->translate("Rate : ");?>
<?php echo $this->translate("Vendor");?>
<?php echo $this->translate("Vendor : ");?>
<?php echo $this->translate("Whats new");?>

<?php echo $this->translate("Free Stuff");?>
<?php echo $this->translate("Logout");?>
<?php echo $this->translate("Most Viewed");?>
<?php echo $this->translate("Newest");?>
<?php echo $this->translate("Premium Collection");?>
<?php echo $this->translate("Register");?>
<?php echo $this->translate("SEARCH");?>
<?php echo $this->translate("Staff Picks");?>
<?php echo $this->translate("Price");?>
<?php echo $this->translate("Rating");?>
<?php echo $this->translate("Supported Formats");?>
<?php echo $this->translate("Latest Reviews");?>
<?php echo $this->translate("No user reviews yet..");?>
<?php echo $this->translate("Please login to post a review.");?>
<?php echo $this->translate("Name");?>
<?php echo $this->translate("Title");?>
<?php echo $this->translate("Review");?>
<?php echo $this->translate("Home");?>
<?php echo $this->translate("To download this app you need to install");?>
<?php echo $this->translate("on your Android device and sign in.");?>
<?php echo $this->translate("To register you need to install");?>
<?php echo $this->translate("on your Android device. Registration happens on your device.");?>
<?php echo $this->translate("Please download the App store app using the following methods.");?>
<?php echo $this->translate("The app you have selected has been pushed directly to your device. Be sure to have the");?>
<?php echo $this->translate("installed on your phone first.");?>
<?php echo $this->translate("If you don't have");?>
<?php echo $this->translate("installed on your phone here is how to get it");?>

<?php echo $this->translate("If you want to install");?>
<?php echo $this->translate("on your phone use following methods.");?>

<?php echo $this->translate("Type in your email address and we will email it to you");?>
<?php echo $this->translate("your email");?>
<?php echo $this->translate("send email");?>
<?php echo $this->translate("Point your mobile browser to the following link:");?>
<?php echo $this->translate("Scan the QR code using your phone to be directly taken to the app page");?>
<?php echo $this->translate("Do not have a QR code reader?");?>
<?php echo $this->translate("Get one free");?>

<?php echo $this->translate("Download");?>
<?php echo $this->translate("Buy");?>
<?php echo $this->translate("More Details");?>

<?php echo $this->translate("Login");?>
<?php echo $this->translate("Required infromation");?>
<?php echo $this->translate("User name");?>
<?php echo $this->translate("Password");?>
<?php echo $this->translate("Forgot your password");?>

<?php echo $this->translate("Please enter First Name");?>

<?php echo $this->translate("Top Downloads");?>
<?php echo $this->translate("Top Free");?>
<?php echo $this->translate("Featured Apps");?>
<?php echo $this->translate("Top Premium");?>
<?php echo $this->translate("Top Paid");?>
<?php echo $this->translate("Your Device");?>
<?php echo $this->translate("Sign Up");?>
<?php echo $this->translate("Next");?>
<?php echo $this->translate("Previous");?>

<?php echo $this->translate("Most viewed collection");?>
<?php echo $this->translate("Contact Us");?>
<?php echo $this->translate("Name");?>
<?php echo $this->translate("Email");?>
<?php echo $this->translate("Message");?>
<?php echo $this->translate("SEND");?>
<?php echo $this->translate("RESET");?>

<?php echo $this->translate("Required Information");?>
<?php echo $this->translate("NO DEVICE SELECTED");?>
<?php echo $this->translate("Feedback");?>

<?php echo $this->translate("SUPPORTED FORMATS");?>
<?php echo $this->translate("ADD YOUR OWN REVIEW");?>
<?php echo $this->translate("App");?>
<?php echo $this->translate("Category");?>
<?php echo $this->translate("Newest Apps");?>
<?php echo $this->translate("Free Apps");?>
<?php echo $this->translate("Premium Apps");?>
<?php echo $this->translate("Top Downloaded Apps");?>
<?php echo $this->translate("Most Viewed Apps");?>


<?php echo $this->translate("Please enter your username");?>
<?php echo $this->translate("Please enter your password");?>
<?php echo $this->translate("The username or password you entered is incorrect");?>
<?php echo $this->translate("Please enter a valid username");?>
<?php echo $this->translate("Please enter your username and password");?>
<?php echo $this->translate("Account");?>
<?php echo $this->translate("Updates");?>
<?php echo $this->translate("Help");?>
<?php echo $this->translate("Premium");?>
<?php echo $this->translate("Downloaded Apps");?>
<?php echo $this->translate("Change Mobile");?>
<?php echo $this->translate("Terms & Conditions");?>
<?php echo $this->translate("Download Started");?>
<?php echo $this->translate("Later");?>
<?php echo $this->translate("Updates are apps that have a newer version. This is either added functionalities, bug fixes or improvements");?>
<?php echo $this->translate("For any customer service issues, bugs in the app downloaded, difficulty downloading or purchases made by mistake please contact us at this email :");?>
<?php echo $this->translate("We will get back to you within 48 hours.");?>
<?php echo $this->translate("Payment was unsuceessful");?>
<?php echo $this->translate("Paid");?>
<?php echo $this->translate("Required infromation");?>
<?php echo $this->translate("Info");?>
<?php echo $this->translate("Feature");?>
<?php echo $this->translate("Please download the");?>
<?php echo $this->translate("App store app using the following methods.");?>
<?php echo $this->translate("FEEDBACK");?>
<?php echo $this->translate("LOGIN HERE");?>
<?php echo $this->translate("To download this app you need to visit the following URL");?>
<?php echo $this->translate("App Store All Rights Reserved.");?>
<?php echo $this->translate("See all results for");?>
<?php echo $this->translate("No results found");?>
<?php echo $this->translate("Sorry! Couldn't find Apps matching your search criteria");?>
<?php echo $this->translate("Have an Issue?");?>
<?php echo $this->translate("You are not signed in yet");?>
<?php echo $this->translate("No Match Found");?>
<?php echo $this->translate("Ok");?>
<?php echo $this->translate("You haven't log in yet ? Please log in.");?>
<?php echo $this->translate("No Data Found");?>
<?php echo $this->translate("Downloading");?>
<?php echo $this->translate("Login to add a ticket");?>
<?php echo $this->translate("Search Results for");?>
<?php echo $this->translate("Powered by");?>
<?php echo $this->translate("The security key wasn't entered correctly");?>
<?php echo $this->translate("Please try again");?>
<?php echo $this->translate("Add a ticket");?>
<?php echo $this->translate("View my ticket");?>
<?php echo $this->translate("Subject");?>
<?php echo $this->translate("Type");?>
<?php echo $this->translate("Priority");?>
<?php echo $this->translate("Select Type");?>
<?php echo $this->translate("Question");?>
<?php echo $this->translate("Incident");?>
<?php echo $this->translate("Problem");?>
<?php echo $this->translate("Select Priority");?>
<?php echo $this->translate("Low");?>
<?php echo $this->translate("Medium");?>
<?php echo $this->translate("High");?>
<?php echo $this->translate("Urgent");?>
<?php echo $this->translate("Your ticket submitted successfully");?>
<?php echo $this->translate("Your response submitted successfully");?>
<?php echo $this->translate("Responces");?>
<?php echo $this->translate("No Response found");?>
<?php echo $this->translate("Reply");?>
<?php echo $this->translate("Submit");?>
<?php echo $this->translate("Platforms");?>
<?php echo $this->translate("Please add your Commenst with more than 10 letters");?>
<?php echo $this->translate("No apps found under this category");?>
<?php echo $this->translate("For any customer service issues, bugs in the app downloaded, difficulty downloading or purchases made by mistake please add a ticket. We will get back to you within 48 hours.");?>
<?php echo $this->translate("This app is only available in the following languages");?>
<?php echo $this->translate("This app-store will be supported for subscribers only");?>
<?php echo $this->translate("To download this app you need to install");?>
<?php echo $this->translate("on your Android device and sign in.");?>
<?php echo $this->translate("If you want to install");?>
<?php echo $this->translate("on your phone use following methods.");?>
<?php echo $this->translate("Do not have a QR code reader? Get one free");?>
<?php echo $this->translate("We're sorry, the keyword/s you searched for did not return any results");?>
<?php echo $this->translate("Please fill the Name");?>
<?php echo $this->translate("Page not found. (404 - Not Found)");?>
<?php echo $this->translate("Please select a type");?>
<?php echo $this->translate("ticket");?>
<?php echo $this->translate("open");?>
<?php echo $this->translate("Dashboard");?>
<?php echo $this->translate("Please select a priority");?>
<?php echo $this->translate("Please add a subject");?>
<?php echo $this->translate("COPYRIGHT_TXT");?>
<?php echo $this->translate("About Us");?>
<?php echo $this->translate("Terms of Use");?>
<?php echo $this->translate("Privacy Policy");?>
<?php echo $this->translate("Developer");?>
<?php echo $this->translate("RIGHTS_TXT_QELASY");?>
<?php echo $this->translate("About");?>
<?php echo $this->translate("Press");?>
<?php echo $this->translate("Login here");?>
<?php echo $this->translate("Login type");?>
<?php echo $this->translate("Sign in as parents or university students");?>
<?php echo $this->translate("Sign in as students");?>
<?php echo $this->translate("Pin");?>
<?php echo $this->translate("Student account not found");?>
<?php echo $this->translate("Pin you entered is incorrect");?>
<?php echo $this->translate("The student id or password you entered is incorrect");?>
<?php echo $this->translate("The user name or password you entered is incorrect");?>
<?php echo $this->translate("Add your own review");?>
<?php echo $this->translate("FEATURED_APPS");?>
<?php echo $this->translate("MOSTVIEWED_APPS");?>
<?php echo $this->translate("NEWEST_APPS");?>