<?php echo $this->render('/partials/richeditor.phtml');?>
<!-- Start Content Box #1 -->
<?php if(isset($this->errors)) : ?>
	<div class="message error">
		<?php foreach ($this->errors as $key=>$value): ?>
			<p><?=$value?></p>
		<?endforeach;?>
	</div>
<?endif;?>
<div class="title">

    <h3>Create | Update page details..</h3>


</div>
<div class="box">
    <div class="txt">

        <div id="content_box">
            <div class="tab-login">
                    
                      <!-- Start pagecreate Form -->
                <form method="post" action="/page/create">
                    <fieldset>
            
                        <p><label for='language_id'>Language</label>
                            <select class="select-input small" name="language_id" id="language_id"  >
                                <?foreach($this->languages as $language): ?>
                                <option value="<?=$language['id'];?>" <? if($language['id'] == $this->page['language_id']){echo 'selected=selected';} ?>><?=$language['name'];?></option>
                                <?endforeach;?>
                            </select>
                        </p>

                        <p><label for='title'>Title (*)</label>
                            <input type="text" id="title" name="title" class="txt-input large" value="<?=$this->page['title']; ?>"/>
                        </p>
                        <p><label>Page body (*)</label>
                            <textarea id='editor1' class="txt-input large richeditor" name="content"><?=$this->page['content']; ?></textarea>
                        </p>
                        <p><label for='slug'>Slug</label>
                            <input type="text" id="slug" name="slug" class="txt-input" value="<?=$this->page['slug']; ?>"/>
                        </p>
                        <p><label for="status">Approved </label>
                            <input type="checkbox" name="status" id="status" value="1" 
                                <?=($this->page['status'] == 1) ? 'checked="checked"' : '';?> /> 
                        </p>
                        


                        <p style="float:left;">
							<input type="submit" class="button" name="submit" value="Save" />
							<input type="button" class="button" name="button" value="Cancel" onClick="location.href='/page'"/>
                        </p>
                    </fieldset>
                    <input type="hidden" name="existingPageId" id="existingPageId" value="<?=$this->page['id']; ?>" />
                    <input type="hidden" name="page_id" id="page_id" value="<?=$this->page['page_id']; ?>" />
                </form>
                <!-- End Login Form -->

            </div>

        </div>

    </div>
</div>
<!-- End Content Box #1 -->


