<div class="title">

    <h3>Statistics</h3>

    <div class="selector" title="content_box">
        <a class="tab <? if($this->tab == '' or $this->tab == 'device'){echo ' active';}?>" href="tab-device">Devices</a>
        <a class="tab <? if($this->tab == 'product' ){echo ' active';}?>" href="tab-product">Contents</a>
        

    </div>
</div>
<div class="box">
    <div class="txt">
        <div style="padding:20px 0px" align="center">
            <form method="POST" name="frmsearch" id="frmsearch" action="<?=$this->form_submit;?>">
                <input type="text"  value="<?=$this->search;?>"name="search" id="search" class="txt-input medium" style="width:300px" />
               
                
                <select class="select-input small" name="type" id="type"  >
                <option value="device" <? if($this->active_type == 'device' )echo 'selected=selected';?>>Devices</option>
                    <option value="product" <? if($this->active_type == 'product' )echo 'selected=selected';?>>Contents</option>
               </select>


                <input type="submit" class="button" name="submit" value="Filter Stats By Date" /><input type="button" class="reset" name="reset" value="Reset" onclick="location.href='/statistic/index'" />
                <small>Remove the search value and hit search to get the full list.</small>
            </form>
        </div>
        <div id="content_box">
            <div class="tab-device">
                <!-- Start Table -->
                <table cellpadding="0" cellspacing="0">

                    <thead>
                        <tr>
                            <!--<th><input type="checkbox" name="check" /></th>-->

                            <th>Devices</th>
                            <th><a href="<?= $this->url(array('device_stats_order' => 'hits','device_hits_order_type' => $this->device_hits_order_type,'tab' => 'device'));?>" title="Order by Hits <?=$this->device_hits_order_type;?>">Hits</a></th>
                            <th><a href="<?= $this->url(array('device_stats_order' => 'date','device_date_order_type' => $this->device_date_order_type,'tab' => 'device'));?>" title="Order by Date <?=$this->device_date_order_type;?>">Date</a></th>
                            
                        </tr>
                    </thead>

                        <? foreach ($this->device_statistics as $stat): ?>
                        <tr>
                            <td><?=$stat['brand']."  ".$stat['model'];?></td>
                            <td><?=$stat['hits'];?></td>
                            <td><?=$stat['date'];?></td>
                            
                        </tr>
                        <?endforeach; ?>
                        <?if($this->is_device_empty  == true):?>
                        <tr>
                            <td colspan="5">
                                <small>
                                    <i>Device list is empty
                                    </i>
                                </small>
                            </td>
                        </tr>
                        <?endif; ?>
                </table>
                <div>
                    <div style="float:left;margin-top:8px;" class="select-input small"> 
                        <a title="Download stats as CSV" href="<?php echo ADMIN_PROJECT_BASEPATH;?><?=$this->device_stats_csv;?>"><img src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/page_excel.png" border="0"/> Device stats csv</a></div>
                 <div><?= $this->paginationControl($this->device_statistics,'Sliding','partials/paginator_stats.phtml',array("page_name" => 'page_device','search_caption' => 'search','search_value'=>$this->search_val_for_paginator ,'type_caption' =>'type','type' => $this->active_type)); ?></div>
                </div>
                <!-- End Table -->
            </div>

            
            <!-- tab not-approved -->
            <div class="tab-product">
                <!-- Start Table -->
                <table cellpadding="0" cellspacing="0">
                    <thead>
                        <tr>
                            <!--<th><input type="checkbox" name="check" /></th>-->

                            <th>Contents</th>
                            <th><a href="<?= $this->url(array('product_stats_order' => 'hits','product_hits_order_type' => $this->product_hits_order_type,'tab' => 'product'));?>" title="Order by Hits <?=$this->product_hits_order_type;?>">Hits</a></th>
                            <th><a href="<?= $this->url(array('product_stats_order' => 'date','product_date_order_type' => $this->product_date_order_type,'tab' => 'product'));?>" title="Order by Date <?=$this->product_date_order_type;?>">Date</a></th>

                        </tr>
                    </thead>

                        <? foreach ($this->product_statistics as $stat): ?>
                        <tr>
                            <td><?=$stat['name'];?></td>
                            <td><?=$stat['hits'];?></td>
                            <td><?=$stat['date'];?></td>

                        </tr>
                        <?endforeach; ?>
                        
                        <?if($this->is_product_empty  == true):?>
                        <tr>
                            <td colspan="5">
                                <small>
                                    <i>Content list is empty
                                    </i>
                                </small>
                            </td>
                        </tr>
                        <?endif; ?>
                </table>
                <div>
                    <div style="float:left;margin-top:8px;" class="select-input small">
                        
                        <a href="<?php echo ADMIN_PROJECT_BASEPATH;?><?=$this->product_stats_csv;?>" title="Download stats as CSV"><img src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/page_excel.png" border="0"/> Content stats csv</a>
                    </div>
                    <div > <?= $this->paginationControl($this->product_statistics,'Sliding','partials/paginator_stats.phtml',array("page_name" => 'page_product','search_caption' => 'search','search_value'=>$this->search_val_for_paginator,'type_caption' =>'type','type' => $this->active_type)); ?>
                    </div>
                </div>
                 <!-- End Table -->
                 
            </div>
            <!-- tab -->
           





        </div>
    </div>
</div>