<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 2/19/14
 * Time: 2:04 PM
 * To change this template use File | Settings | File Templates.
 */
?>
<script type="text/javascript">
    $().ready(function(){
       $('#send-option').change(function(){
            alert('jhzfbgksdhg');
       });
    });
</script>
<div style="display: none;">
    <div id="campaign">
        <div class="pop_up_head"><h3>Campaign</h3></div>
        <img id='preloader' class='display_none' width='16'  src="<?= $this->cdn('site_assets') ?>/web/images/loading.gif" border="0" id="seach_loading" alt="loading" />
        <form id="campaign-details" style="overflow: auto"></form>
    </div>
</div>