<script type="text/javascript">
//Tinymice Editor
$().ready(function() {
        $('textarea.tinymce').tinymce({
            // Location of TinyMCE script
            script_url : '<?php echo PBO_PROJECT_BASEPATH;?>'+'js/tiny_mce.js',
            
            // General options
            theme : "advanced",
            plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",
            
            // Theme options
            theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,formatselect,fontsizeselect",
            theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            //theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : true

        });
});
 //End Tinymice Editor      
</script>
<style>    
#main-content table td, #main-content table th {
    line-height: 1.3em;
    padding: 0px;
}
</style>

<div class="tab-content" id="cp_settings"> 
<!--<div id="cp_settings">-->

     <!-- Displays Message/s -->
        <?php if (count($this->cpMessages)) : ?>

        <div class="notification success png_bg">                
                <div>

                    <?php foreach ($this->cpMessages as $message) : ?>

                        <li><?php echo $this->escape($message); ?></li>

                    <?php endforeach; ?>

                </div>
            </div>

        <?php endif; ?>
    
    <form enctype="multipart/form-data" method="post" action="<?php echo PBO_PROJECT_BASEPATH;?>setting/" id="frmCpSettings" name="frmCpSettings">
            
        <p>Settings of the Developer Portal</p>
        
            <p>
                <label>Site Title <span class="mendatory_fileds">*</span></label>
                <input id="txtTitleCp" name="txtTitleCp" class="text-input small-input required" type="text" value="<?= isset($this->cpTitle) ? $this->cpTitle : $this->escape($this->settings->CP_PANEL_TITLE); ?>"></input>
            </p>
           
            <p>
                <label>Home Page Description <span class="mendatory_fileds">*</span></label>
                <textarea rows="15" cols="79" name="txtHomeDes" id="txtHomeDes" style="width:300px !important" class="required tinymce"><?= isset($this->homeDes) ? $this->homeDes : $this->escape($this->settings->CP_HOME_DESCRIPTION); ?></textarea>
            </p>
                       
            <p>
                <label>Logo <span style="font-weight: normal;font-size: 10px">(Max Width - 130px, Max Height - 60px, File Type - .png, .gif)</span></label>
                <input type="file" id="cpLogo" name="cpLogo" class="chkbox"/> 
            </p>
            <? if(!empty($this->settings->CP_HEADER_LOGO)) : ?>
               <p> 
                <label>Current Logo</label>
                <img src="/cp/assets/logos/<?= $this->settings->CP_HEADER_LOGO; ?>" alt="No Image" />
               </p> 
            <? endif; ?>
            <p>
                <label>Header Color <span style="font-weight: normal;font-size: 10px">(Example - #000000)</span></label>
                <input id="txtHeaderColour" name="txtHeaderColour" class="text-input" type="text" value="<?= isset($this->headeColour) ? $this->headeColour : $this->escape($this->settings->CP_HEADER_COLOUR); ?>"></input>
            </p>
            <p>
                <label>Footer</label>
                <textarea id="txtFooter" name="txtFooter"  class="textarea" rows="3" cols="79" style="width:30% !important;"><?= isset($this->footerDes) ? $this->footerDes : $this->escape($this->settings->CP_FOOTER); ?></textarea>
            </p>
<!--            <p>
                <label>Custom Style Sheet <span style="font-weight: normal;font-size: 10px">(No path required)</span></label>
                <input id="txtHeaderColour" name="txtCustomCss" class="text-input" type="text" value="<?= isset($this->customCss) ? $this->customCss : $this->escape($this->settings->CP_CUSTOM_CSS); ?>"></input>
            </p>-->
            <br/>
                <input id="btnSubmit" name="btnSubmit" class="button" type="submit" value="<?= isset($this->menuId) ? 'Save' : 'Submit' ?>">
                <input id="btnReset" name="btnReset" class="button" type="reset" value="Reset">
                <input id="settingType" name="settingType" class="button" type="hidden" value="cp">
                
                <input id="cpHeaderLogo" name="cpHeaderLogo" class="button" type="hidden" value="<?= isset($this->settings->CP_HEADER_LOGO) ? $this->settings->CP_HEADER_LOGO : '' ?>">
            </p>
        </form>
        <br />
    </div>
    

