<?php
/*
 * Search pagination
 */
?>
<?php if ($this->pageCount): ?>

    <div id="paginationControl" class="pagination">
        <!-- Previous page link -->

        <?php if (isset($this->previous)): ?>

            <a href="<?php echo $this->url(array('page' => $this->previous, 'price_filter' => $this->price_filter, 'cat_filter' => $this->cat_filter,'platform' => $this->platform,'language' => $this->language,'search_key' => $this->search_key, 'grade' => $this->grade)); ?>"> &lt;&lt; Previous</a>

        <?php else: ?>

            <span class="disabled">&lt;&lt; Previous</span>

        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>

            <?php if ($page != $this->current): ?>

                <a class="number" href="<?php echo $this->url(array('page' => $page, 'price_filter' => $this->price_filter, 'cat_filter' => $this->cat_filter,'platform' => $this->platform,'language' => $this->language,'search_key' => $this->search_key, 'grade' => $this->grade)); ?>"><?php echo $page; ?></a>

            <?php else: ?>

                <a class="number current"><?php echo $page; ?></a>

            <?php endif; ?>

        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>

            <a href="<?php echo $this->url(array('page' => $this->next, 'price_filter' => $this->price_filter, 'cat_filter' => $this->cat_filter,'platform' => $this->platform,'language' => $this->language,'search_key' => $this->search_key, 'grade' => $this->grade)); ?>">Next &gt;&gt;</a>

        <?php else: ?>

            <span class="disabled">Next &gt;&gt;</span>

        <?php endif; ?>

    </div>
<?php endif; ?>