<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 4/21/14
 * Time: 2:11 PM
 * To change this template use File | Settings | File Templates.
 */
?>

<?php if ($this->pageCount) { ?>
    <div id="paginationControl" class="pagination">
        <!-- Previous page link -->
        <?php if (isset($this->previous)){ ?>
            <!--<a href="<?php /*echo $this->url(array('page' => $this->previous,'appId' => $this->appId , 'fromDate' => $this->fromDate , 'toDate' => $this->toDate)); */?>"> &lt;&lt; Previous</a>-->
            <a href="<?php echo $this->url(array('page' => $this->previous,'appId' => $this->appId , 'fromDate' => $this->fromDate , 'toDate' => $this->toDate)); ?>"> &lt;&lt; Previous</a>
        <?php } else { ?>
            <span class="disabled">&lt;&lt; Previous</span>
        <?php } ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page){ ?>
            <?php if ($page != $this->current){ ?>
                <a class="number" href="<?php echo $this->url(array('page' => $page, 'appId' => $this->appId , 'fromDate' => $this->fromDate , 'toDate' => $this->toDate)); ?>"><?php echo $page; ?></a>
            <?php } else { ?>
                <a class="number current"><?php echo $page; ?></a>
            <?php } ?>
        <?php } ?>
        <!-- Next page link -->
        <?php if (isset($this->next)){ ?>
            <a href="<?php echo $this->url(array('page' => $this->next,'appId' => $this->appId , 'fromDate' => $this->fromDate , 'toDate' => $this->toDate)); ?>">Next &gt;&gt;</a>
        <?php } else { ?>
            <span class="disabled">Next &gt;&gt;</span>
        <?php } ?>
    </div>
<?php } ?>