<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 6/27/14
 * Time: 10:20 AM
 * To change this template use File | Settings | File Templates.
 */
?>

<?php if ($this->pageCount) {
    //$urlData = array('page' => $this->previous, 'from' => $this->from, 'to' => $this->to, 'price' => $this->price, 'mobile' => $this->mobile);
    $urlData = array();
    if($this->from) { $urlData['from'] = $this->from; }
    if($this->to) { $urlData['to'] = $this->to; }
    if($this->price) { $urlData['price'] = $this->price; }
    if($this->mobile) { $urlData['mobile'] = $this->mobile; }
    ?>
    <div id="paginationControl" class="pagination">

        <!-- Previous page link -->
        <?php if (isset($this->previous)) {
            $urlData['page'] = $this->previous;
            ?>
            <a href="<?php echo $this->url($urlData); ?>"> &lt;&lt; Previous</a>

        <?php } else { ?>

            <span class="disabled">&lt;&lt; Previous</span>

        <?php } ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page) { ?>

            <?php if ($page != $this->current) {
                $urlData['page'] = $page;
                ?>

                <a class="number" href="<?php echo $this->url($urlData); ?>"><?php echo $page; ?></a>

            <?php } else { ?>

                <a class="number current"><?php echo $page; ?></a>

            <?php } ?>

        <?php } ?>

        <!-- Next page link -->
        <?php if (isset($this->next)) {
            $urlData['page'] = $this->next;
            ?>
            <a href="<?php echo $this->url($urlData); ?>">Next &gt;&gt;</a>

        <?php } else { ?>

            <span class="disabled">Next &gt;&gt;</span>

        <?php } ?>
    </div>
<?php } ?>