<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 5/22/14
 * Time: 3:51 PM
 * To change this template use File | Settings | File Templates.
 */
?>
<div style="display:none;">
    <div id="qelasy-grade-delete">
        <div class="pop_up_head pop_up_head_custom"><h3>Delete Qelasy Grade</h3></div>
        <img id='preloader_feature' class='display_none' width='16'  src="<?= $this->cdn('site_assets') ?>/web/images/loading.gif" border="0" id="seach_loading" alt="loading" />
        <div  style="overflow: auto">
            Do you want to delete this Qelasy Grade?
            <div>
                <input id="confirm-ok" class="button" type="button" value="Ok">
                <input id="confirm-cancel" class="button" type="button" value="Cancel">
            </div>
        </div>
    </div>
</div>