<tr>
    <td class="alt"><?=$this->telco['siteName'];?> </td>
    <td class="alt"><?=$this->telco['appCount'];?>  </td>
    <td><?=$this->telco['appCountFeatured'];?></td>    
    <td><?=$this->telco['telcoAppDownloadedCount'];?></td>  
    <td><?=$this->telco['views'];?></td>
    <td><?=$this->telco['downloads'];?></td>
    <td>$ <?=number_format($this->telco['revenue'], 2, '.', ''); ?></td>
</tr>
               
     