<?php $currency = $this->ChangeCurrency($this->partnerId);?>

<h2 class="font-size-16"><?php echo $this->translate('Featured Apps');?></h2> 
    <ul data-role="listview" data-inset="true" class="ui-icon-alt">

        <?php
        $x = 0;
        foreach($this->staffPicks as $app) : 
            $x++;
            ?>
        <li id="custom-li">
            <a href="<?php echo PROJECT_BASEPATH;?>app/detail/id/<?=$app['product_id']?>" rel="external">
                <img src="<?= $this->productImages()."/vendors/phpThumb/phpThumb.php?src=/product_visuals/".APPLICATION_ENV."/".basename($app['thumbnail'])."&w=80&h=80&aoe=0&fltr[]=ric|0|0&q=100&f=png" ?>" />
                <h3><?= $app['name'] ?></h3>
                <p><?= $this->trim($app['vendor'],18) ?></p>
                <div id="rating">
                     <?= $this->partial('partials/rating_inner.phtml', array('product_id'=>$app['product_id'], 'avgRating'=>$app['avg_rating'], 'totalRatings'=>$app['total_ratings'], 'productRated'=>$app['product_rated'])); ?>
                </div>
            </a>
                <? if($app['price'] > 0) : ?>
                        
                        <span class="ui-li-count">
                            <?php if($this->mtnIran){ ?>
                                <?php echo (($app['price']) > 0) ? number_format($this->PricePoints(ceil($app['price']*$this->currencyDetails["rate"])),($this->mtnIran == 23045) ? 0 : 2, '.', ',').' '.$this->translate($currency[0]['symbol']) : $this->translate("Free") ;?>  
                            <?php } else { ?>
                                <?php echo (($app['price']) > 0) ? $this->currencyDetails["symbol_web"]. " ".number_format($this->PricePoints(ceil($app['price']*$this->currencyDetails["rate"])),($this->mtnIran == 23045) ? 0 : 2, '.', ',') : $this->translate("Free") ;?>  
                            <?php } ?>
                            
                            <?php /*if(!empty($currency)){ echo $this->translate($currency[0]['symbol']);} else { echo '$';}*/ ?><!-- --><?php /*if(!empty($currency)){ echo number_format(ceil($currency[0]['rate']*$app['price']),2, '.', ',');}else{ echo $app['price']; } */?>
                            <?php /*echo (($app['price']) > 0) ? $this->currencyDetails["symbol_web"]. " ".number_format(ceil($app['price']*$this->currencyDetails["rate"]),2, '.', ',') : $this->translate("Free") ;*/?>
                            
                            
              
                        </span>
            
                    <? else : ?>
                        
                        <span class="ui-li-count">
                            <?php echo $this->translate("Free");?>
                        </span>
                    <? endif; ?>
            <?= (isset($app['updates_available']) && ($app['updates_available'] == 1)) ? '<span class="update-available">!</span>' : ''; ?>
        </li>
        <? endforeach; ?>
    </ul>
<?php
if($_SERVER['REMOTE_ADDR'] == '220.247.236.99'){
    //echo $this->chap_id; die();
}
?>