<div class="codengo-campaign-widget" data-widget="{011db810-85c1-e411-ac1f-d365081551e5}">
    <script type="text/javascript">(function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id; js.src = "http://reporting.codengo.com/Featured/Content/Script/widget/v1.js";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'codengo-campaign-widget'));</script>
</div>