<?php 
    $this->headLink()->appendStylesheet( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/css/jquery.ketchup.css');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.js');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.messages.js');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.validations.basic.js');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'admin/assets/js/admin.js');
?>



<?php $item  = $this->currency;?>
<div class="title">
    <h3>Create Currency</h3>
</div>

<div class="box">
    <div class="txt">
        <div class="content_box">
            <?php if(isset($this->errors) && !empty($this->errors)) : ?>
                <?php foreach ($this->errors as $message) : ?>
                <div class="message error" style="display: block;">
                    <p><?=$message ?></p>
                </div>
                <?php endforeach; ?>
            <?php endif; ?>
            
            <fieldset>
                 <form class='form_validate' method="post" accept-charset="UTF-8" action="/currency/index">
                 
                 <p>
                    <label for='title'>Name</label>
                    <input value='<?=$item->name?>' type='text' id='name' name='name' class='txt-input medium validate(required, rangelength(1,40))'>
                 </p>
                 
                 <p>
                    <label for='code'>Code</label>
                    <input value='<?=$item->code?>' type='text' id='code' name='code' class='txt-input medium validate(required, rangelength(1,10))'>
                 </p>
                 
                 <p>
                    <label for='symbol'>Symbol</label>
                    <input value='<?=$item->symbol?>' type='text' id='symbol' name='symbol' class='txt-input medium validate(required, rangelength(1,10))'>
                 </p>
                 
                 <p>
                    <label for='icon'>Icon</label>
                    <input value='<?=$item->icon?>' type='text' id='icon' name='icon' class='txt-input medium validate(required)'>
                 </p>
                 
                 <p>
                    <label for='rate'>Rate</label>
                    <input value='<?=$item->rate?>' type='text' id='rate' name='rate' class='txt-input medium validate(required, rangelength(1,50))'>
                 </p>
              
                 <input type='hidden' value='<?php echo $item->id ?>' name='id'>
                 <p><input type="submit" class="txt-input small" value="Save Currency" id="submit" name="submit"></p>
                 </form>
            </fieldset>
        </div>
        </div>
</div>    


        <div class="title">
            <h3>All Campaigns</h3>
        </div>
        <div class="box">
    <div class="txt">
        <table cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Code</th>
                    <th>Rate</th>
                    <th>Enabled</th>
                    <th>&nbsp</th>
                </tr>
            </thead>
        
            <tbody>
        <?php if (count($this->currencies)): $class = 'alt';?>    
            <?php foreach ($this->currencies as $item): $class = ($class == 'alt') ? '' : 'alt' ;?>
                <tr>
                    <td class='<?=$class?>'><?=$item->id?></td>
                    <td class='<?=$class?>'><a href='/currency/index/id/<?=$item->id?>'><?=$item->name?></a></td>
                    <td class='<?=$class?>'><?=$item->code?></td>                    
                    <td class='<?=$class?>'><?=$item->rate?></td>
                    <td class='<?=$class?>'><?=$item->enabled?></td>
                    <td class='<?=$class?>'>
                        &nbsp;&nbsp;&nbsp; 
                        <a href='/currency/delete/id/<?php echo $item->id ?>' class='del_conf'>Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
            </tbody>
        
        </table>
    </div>
</div>


