<? if(!isset(Zend_Auth::getInstance()->getIdentity()->id)): ?>
<form name="userForm" id="userForm" action="/user/login" method="post">
    <div >
        <label>E-Mail</label>
        <input type="text" value="" id="email" name="email">
    </div>
    <div >
        <label>Password</label>
        <input type="password" value="" id="password" name="password">
    </div>
    <br />
    <input type="button" id="usr_login" value="Login" />
    <input type="button" id="usr_signup" value="Signup" />
   
</form>
<? else: ?>
<br/><br/>
<ul class="btn">
    <li><a href="/user/logout">Logout</a></li>
    <li><a href="<?php echo PROJECT_BASEPATH;?>app/purchased">Downloads</a></li>
</ul>
<? endif; ?>