<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

?>
  <b>1. <?php echo $this->translate("Get Help via Skype");?> </b><br/>
<!--
Skype 'Skype Me™!' button
http://www.skype.com/go/skypebuttons
-->
<script type="text/javascript" src="http://download.skype.com/share/skypebuttons/js/skypeCheck.js"></script>
<a href="skype:cj19820508?call"><img src="http://download.skype.com/share/skypebuttons/buttons/call_green_white_153x63.png" style="border: none;" width="153" height="63" alt="Skype Me™!" /></a>
<br/>
<b>2. <?php echo $this->translate("Write to us");?> </b><br/>
<a href="mailto:contact@nexva.com">contact@nexva.com</a>