<?php $this->headLink()->appendStylesheet($this->Cdn('site_assets').'/cp/assets/css/analytics.css'); ?>
<?php $this->headLink()->appendStylesheet( PROJECT_BASEPATH.'admin/assets/css/smoothness/jquery-ui.css'); ?>
<?php $this->headScript()->appendFile($this->cdn('site_assets').'/cp/assets/js/analytics/excanvas.min.js'); ?>
<?php $this->headScript()->appendFile($this->cdn('site_assets').'/cp/assets/js/analytics/jquery.flot.js'); ?>
<?php $this->headScript()->appendFile($this->cdn('site_assets').'/cp/assets/js/analytics/jquery.flot.pie.js'); ?>
<?php $this->headScript()->appendFile($this->cdn('site_assets').'/cp/assets/js/analytics/jquery.flot.stack.js'); ?>

<?php $this->headScript()->captureStart();?>
    var __DATA_DATE         = eval(<?php echo $this->appViewDateJson?>); //app views by date
    var __DATA_DOWNLOADS    = eval(<?php echo $this->appDownloadDateJson;?>); //downloads
<?php $this->headScript()->captureEnd();?>
         <?php                
                $chapId = Zend_Auth::getInstance()->getIdentity()->id;
                if(!in_array($chapId, array('585474','585480'))){ ?>
                        <?php $this->headScript()->appendFile($this->cdn('site_assets').'/cp/assets/js/analytics/appview.js'); ?>
                <?php }else{?>
                        <?php $this->headScript()->appendFile('/cp/assets/js/analytics/appview_fr.js'); ?>
                <?php } ?>


     <!-- analytics block -->
        <div id='stats_view_by_date_cont' class="title">
            <h3><?php echo $this->translate("Overall App Views / Downloads");?> - <?php echo $this->translate(date('F'));?>- <?=date('Y')?> </h3>
                <div class='filter'>
                        <a href='/analytics/dashboard' class='button'><?php echo $this->translate("Dashboard");?></a>
                </div>
        </div>
        <div class="box">
            <div class="txt">
                <div class='analytics_trends'>
	                  <ul class="icon_list">
                         <li>
                            <?php 
                            
                                   
                                $trendNow       = max($this->downloadTrends['NOW'], 1);
                                $trendPrevious  = max($this->downloadTrends['PREVIOUS'], 1);
                                $image          = ($trendNow >= $trendPrevious) ? 'arr_down_green.png' : 'arr_down_orange.png';
                                $change         = (($trendNow - $trendPrevious) / $trendPrevious ) * 100;
                                $change         = number_format($change, 2);
                              ?>
                            <p><img width='32' height='32' src="/cp/assets/img/content/icon_list/<?=$image?>" alt=""/>
                              <a href="#"><?php echo $this->translate("Downloads");?> <?=$change?>%</a>
                             <!--   <a href="/analytics/downloads/">Downloads <?=$change?>%</a>  -->   </p>
                          </li>

                          <li>
                          <?php 
                                $trendNow       = max($this->viewTrends['NOW'], 1);
                                $trendPrevious  = max($this->viewTrends['PREVIOUS'], 1);
                               
                                $image          = ($trendNow >= $trendPrevious) ? 'arr_down_green.png' : 'arr_down_orange.png';  
                                $change         = (($trendNow - $trendPrevious) / $trendPrevious) * 100;
                                $change         = (($trendNow - $trendPrevious) / $trendPrevious) * 100;
                                $change         = number_format($change, 2);
                                
                                
                            ?>
                            <p><img width='32' height='32' src="/cp/assets/img/content/icon_list/<?=$image?>" alt=""/>
                              <a href="#"><?php echo $this->translate("Views");?> <br /> <?=$change?>%</a>
                            <!--  <a href="/analytics/views/">Views <br /> <?=$change?>%</a>  --> 
                              
                              </p>
                          </li>

                     </ul>
 
                 </div>
                 
                <div class='full_block' style='width: 820px;' id='stats_view_by_date'>
                        <?php echo $this->translate("Please wait while we load the data.");?>
                 </div>
                 
                 
            </div>
        </div>
       <!-- end of analytics block -->
   
           

 <!-- Start Content Box #1 -->
<div class='home_info_block'>
<div class="title"><h3><?php echo $this->translate("Administration Options");?></h3></div>
<div class="box">
  <div class="txt">
    <ul class="icon_list">
     
      <li>
        <p><img src="/cp/assets/img/content/icon_list/add_product.jpg" alt=""/>
          <a href="<?php echo PROJECT_BASEPATH;?>product/create"><?php echo $this->translate("Add Content");?></a></p>
      </li>
      <li>
        <p><img src="/cp/assets/img/global/icons/box.png" alt=""   style="margin:12px;"/>
          <a href="<?php echo PROJECT_BASEPATH;?>product/view"><?php echo $this->translate("View Content");?> </a></p>
      </li>
      <li>
        <p><img src="/cp/assets/img/content/icon_list/cp.png" alt="" style="margin:4px;"/>
          <a href="/user/profile"><?php echo $this->translate("Profile");?> </a></p>
      </li>
      <li>
          <p><a href="/analytics/downloads/<?php echo $this->queryString ?>">
                  <img width='32' height='32' src="/cp/assets/img/content/icon_list/download.png" alt="downloads"/>
                  <br><?php echo $this->translate("Downloads"); ?>
              </a>
          </p>
      </li>
    </ul>
    <div class="clear"></div>
        </div>
      </div>      
     
</div>    
 <div class='blog_feed'>
      <div class="title"><h3><?php echo $this->translate("Featured Video : neXlinker in 45 seconds");?></h3></div>
        <div class="box">
        <div class="txt">
          <?=$this->featuredVid?>
        <div class="clear"></div>
        </div>
        </div>
 </div>
<!--    <div class='blog_feed'>
     
    
        <div class='title'><h3><?php //echo $this->translate("Latest News");?>  (<a target='_blank' href='http://www.mobilopen.org/'><?php //echo $this->translate("Read All");?></a>)</h3></div>
        <div class="box">
        <div class="txt">
        <?php 
            //$size = min(7, count($this->blogItems)); 
            //for ($i = 0; $i < $size; $i++) : 
            //    $item = $this->blogItems[$i];
        ?>
            <div class='item'>
                <h4><a target='_blank' class='title_link' href='<?//=$item->link?>'><?//=$item->title?></a></h4>
                <p><?//=$this->trim($item->summary, 200, false)?>
                    <a href="<?//=$item->link?>" class="more">[..]</a>
                </p>
                
            </div>
        <?php //endfor;?>
        </div>
        </div>
    </div>      -->
      
      <!-- End Content Block #1 -->
        <div class='clear'></div>



      <!-- Start Content Box #2 -->
      <div class="title">
        <a name="activity" id="activity"></a><h3><?php echo $this->translate("Last ten uploaded content.");?></h3>


      </div>
      <div class="box">
        <div class="txt">

          <div id="content_box">
            <div class="tab-table">

             

              <!-- Start Table -->
              <table cellpadding="0" cellspacing="0">
                <thead>
                  <tr>

                    <th><?php echo $this->translate("Content name");?></th>
                    <th><?php echo $this->translate("Price");?></th>
                    <th><?php echo $this->translate("Type");?></th>
                    <th><?php echo $this->translate("Status");?></th>
                    <th style="text-align: center;"><?php echo $this->translate("Created")," / ".$this->translate("Updated on");?> </th>
                    <th style="width:20%;"><?php echo $this->translate("Operations");?></th>
                    <th style="text-align: center;width:20%;"><?php echo $this->translate("Status");?> <br /> <?php echo $this->translate("views / downloads");?> </th>
                  </tr>
                </thead>
                <tbody>
            <? foreach ($this->products as $product): ?>
            <?= $this->partial('partials/product_simple.phtml', array("product" => $product, 'nexpagerState' => $this->nexpagerState)); ?>
            <? endforeach; ?>

            <? if ($this->show_empty_msg == true): ?>
                <tr>
                  <td colspan="5">
                    <small>
                      <i><?php echo $this->translate("You don't have any content uploaded yet.");?>
                        <a href='<?php echo PROJECT_BASEPATH;?>product/create/'><?php echo $this->translate("Upload a new content now");?></a>
                      </i>
                    </small>
                  </td>
                </tr>
            <? endif; ?>
          </tbody>
        </table>
        <!-- End Table -->

      </div>
    </div>
  </div>
</div>

<!-- End Content Box #2 -->