<div class="content-box"><!-- Start Content Box -->
    <div class="content-box-header">
        <h3 style="cursor: s-resize;"><?= $this->title; ?></h3>

    </div> <!-- End .content-box-header -->


    <div class="content-box-content">
        
        
        <!-- Displays Message/s -->
        <?php if (count($this->messages)) : ?>

        <div class="notification success png_bg">                
                <div>

                    <?php foreach ($this->messages as $message) : ?>

                        <li><?php echo $this->escape($message); ?></li>

                    <?php endforeach; ?>

                </div>
            </div>

        <?php endif; ?>
        
        
        
        <table cellpadding="0" cellspacing="0" style="width:60%">

            <thead>
                <tr>
                    <th>Payment Gateway</th>
                    <th style="text-align: center">Default</th>
                </tr>
            </thead>
            <tbody>

                <?php foreach ($this->gateways as $gateway) : ?>
                   

                    <tr>
                        <td valign="top"><?= $gateway->name;?> </td>
                        <td valign="top" style="text-align: center">
                             <? if (isset($this->chapGateway->payment_gateway_id) && ($gateway->id == $this->chapGateway->payment_gateway_id)): ?>
                            
                                <img style="border: none" src="<?php echo PBO_PROJECT_BASEPATH; ?>images/icons/icon-default.png" alt="Default" title="Default"/>
                            
                            <? else: ?>  
                                <a href="<?php echo PBO_PROJECT_BASEPATH; ?>payment-gateway/set-default/id/<?= $gateway->id ?>" title="Set Default">
                                    <img style="border: none" src="<?php echo PBO_PROJECT_BASEPATH; ?>images/icons/icon-notdefault.png" alt="Set Default" />
                                </a>
                            <? endif; ?>
                        </td>

                    </tr>
                    <?php endforeach; ?>

            </tbody>

        </table>
        
    </div>
    
</div>

<script type="text/javascript">        
   $('#6').addClass('current');  
   $('#61').addClass('current'); 
</script>