<script type="text/javascript">
//Tinymice Editor
$().ready(function() {
        $('textarea.tinymce').tinymce({
            // Location of TinyMCE script
            script_url : '/pbo/js/tiny_mce.js',
            
            // General options
            theme : "advanced",
            plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",
            
            // Theme options
            theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,formatselect,fontsizeselect",
            theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            //theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : true

        });
});
 //End Tinymice Editor      
</script>
<style>    
#main-content table td, #main-content table th {
    line-height: 1.3em;
    padding: 0px;
}
</style>
<div class="content-box"><!-- Start Content Box -->
    <div class="content-box-header">
        <h3 style="cursor: s-resize;"><?= $this->title; ?></h3>

        <div id="icon_wrapper">
            <a href="<?php echo PROJECT_BASEPATH;?>ticket/index" alt="Manage Tickets"> <img style="border: none" src="/pbo/images/icons/add-menu-small.png" alt="Manage Tickets" /><br />
            Manage Tickets</a>
        </div>
    </div>

    <div class="content-box-content">
        
         <!-- Displays Message/s -->
        <?php if (count($this->ticketMessages)) : ?>

        <div class="notification success png_bg">                
                <div>

                    <?php foreach ($this->ticketMessages as $message) : ?>

                        <li><?php echo $this->escape($message); ?></li>

                    <?php endforeach; ?>

                </div>
            </div>

        <?php endif; 
         
      if(count($this->ticketErMessages)) :
    ?>

    <div class="message error_msg">               
        <p>
        <?php foreach ($this->ticketErMessages as $message) : ?>

           <?php echo $this->escape($message); ?>

       <?php endforeach; ?>

           <?php echo $this->escape($this->ticketErMessages) ?>
        </p>
    </div>

   <?php endif; ?>
         
        <div id="inner_wrapper">
            
            <div id="inner_left">
                
                <div id="ticket_wrapper">
                    <h2><?= $this->ticketDetails->subject; ?></h2>
                    <span class="shaded_text">
                        <?= Date('d-m-Y H:i:s', strtotime($this->ticketDetails->created_date)).' Via '.$this->ticketDetails->source; ?>
                    </span>
                    <?= $this->ticketDetails->description; ?>                   
                </div>
                
                
                <?php if(count($this->responses)) :
                    
                        foreach($this->responses as $response) 
                :?>          
                            <div class="verticle_space"></div>
                            
                            <div id="ticket_response_wrapper">
                                
                                    <span class="shaded_text">
                                        <?= Date('d-m-Y H:i:s', strtotime($response->response_date)); ?>
                                    </span>
                                    <?= $response->description; ?>  
                                
                                
                                <?php
                                        if(!is_null($response->attachment_name) && !empty ($response->attachment_name)) :                                           
                               ?>
                                
                                <a class="attachment" href="<?php echo PROJECT_BASEPATH;?>ticket/download-attachment/res_id/<?= $response->id; ?>">
                                    <?= $response->attachment_name; ?>
                                </a>

                                <?php endif; ?>
                                
                                <br/>
                            </div>
                
                            
                    <?php endforeach; 
                    endif;
                    ?>
                
                <div class="verticle_space"></div>
                
                <div id="response_wrapper_send">
                    
                        <form name="frmSendResponse" id="frmSendResponse" action="/ticket/details" method="post" novalidate="novalidate" enctype="multipart/form-data">
                           
                                <p>
                                    <textarea id="textarea" class="tinymce" rows="15" cols="79" name="txtResponse" id="txtResponse" style="width:100px;">                                    
                                    </textarea>
                                </p>
                                <p>
                                    <label>Attachment <span style="font-weight: normal;font-size: 10px">(Max File Size - 2 MB)</span></label>
                                    <input type="file" name="ticketAttachment" id="ticketAttachment" class="chkbox"/> 
                                </p>
                                <p>
                                    <input type="submit" value="Submit" class="button" name="btnSubmit" id="btnSubmit">
                                    <input id="ticketId" name="ticketId" class="button" type="hidden" value="<?= !isset($this->ticketDetails->id) ? '' : $this->ticketDetails->id; ?>">
                                </p>
                                    
                         </form>
                 </div>
            </div>
            
            <div id="inner_right">
                                  
                     <form name="frmTicketProperties" id="frmTicketProperties" action="/ticket/change-status" method="post" novalidate="novalidate">

                          <fieldset>
                                
                                <legend>Ticket Properties</legend>
                                
                                        <label>Type</label>                            
                                        <select class="chkbox" id="chkType" name="chkType">
                                            <option value="Question" <?= (isset($this->ticketDetails->type) && $this->ticketDetails->type == 'Question') ? 'selected="selected"' : ''; ?>>Question</option>     
                                            <option value="Incident" <?= (isset($this->ticketDetails->type) && $this->ticketDetails->type == 'Incident') ? 'selected="selected"' : ''; ?>>Incident</option>     
                                            <option value="Problem" <?= (isset($this->ticketDetails->type) && $this->ticketDetails->type == 'Problem') ? 'selected="selected"' : ''; ?>>Problem</option>     
                                            <option value="Feature" <?= (isset($this->ticketDetails->type) && $this->ticketDetails->type == 'Feature') ? 'selected="selected"' : ''; ?>>Feature</option>
                                        </select>                
                                         </p>
                                         <p class="" id="pageField">
                                                <label>Priority</label>                            
                                                <select class="chkbox" id="chkPriority" name="chkPriority">
                                                    <option value="Low" <?= (isset($this->ticketDetails->priority) && $this->ticketDetails->priority == 'Low') ? 'selected="selected"' : ''; ?>>Low</option>     
                                                    <option value="Medium" <?= (isset($this->ticketDetails->priority) && $this->ticketDetails->priority == 'Medium') ? 'selected="selected"' : ''; ?>>Medium</option>     
                                                    <option value="High" <?= (isset($this->ticketDetails->priority) && $this->ticketDetails->priority == 'High') ? 'selected="selected"' : ''; ?>>High</option>     
                                                    <option value="Urgent" <?= (isset($this->ticketDetails->priority) && $this->ticketDetails->priority == 'Urgent') ? 'selected="selected"' : ''; ?>>Urgent</option>  
                                                </select>                
                                         </p>
                                         <p class="" id="pageField">
                                                <label>Status</label>                            
                                                <select class="chkbox" id="chkStatus" name="chkStatus">
                                                    <option value="Open" <?= (isset($this->ticketDetails->status) && $this->ticketDetails->status == 'Open') ? 'selected="selected"' : ''; ?>>Open</option>     
                                                    <option value="Pending" <?= (isset($this->ticketDetails->status) && $this->ticketDetails->status == 'Pending') ? 'selected="selected"' : ''; ?>>Pending</option>     
                                                    <option value="Resolved" <?= (isset($this->ticketDetails->status) && $this->ticketDetails->status == 'Resolved') ? 'selected="selected"' : ''; ?>>Resolved</option>     
                                                    <option value="Closed" <?= (isset($this->ticketDetails->status) && $this->ticketDetails->status == 'Closed') ? 'selected="selected"' : ''; ?>>Closed</option>   
                                                </select>                
                                         </p>
                                        <p>
                                            <input type="submit" value="Update" class="button" name="btnSubmit" id="btnSubmit">
                                            <input id="ticketId" name="ticketId" class="button" type="hidden" value="<?= !isset($this->ticketDetails->id) ? '' : $this->ticketDetails->id; ?>">
                                        </p>
                             </fieldset>
                     </form>
            </div>
        </div>

    </div>
    
</div>