<?php $t = $this->t();?>
<div class="pagination b-b"><!-- Previous page link -->
    
    <?php
                
                if (isset ( $this->previous )) :
                    ?>
    <?php
                    echo "<a class='p-left' href='http://" . $this->baseUrlfo . "/go/" . $this->previous . "'> Prev</a>";
                    ?>
    
                <?php endif;
                ?>
    <?=$this->current?> <?php $t->_('of')?>  <?=$this->pageCount?>
    <!-- Next page link -->
    <?php
                if (isset ( $this->next )) :
                    ?>
     <?php
                    echo "<a class='p-right' href='http://" . $this->baseUrlfo . "/go/" . $this->next . "'> Next</a>";
                    ?>
    
                <?php endif;
                ?>

    <!--    <a href="#" class="p-left">Prev</a>
        <a href="#" class="p-right">Next </a>
    --> <br clear="all" />
</div>
