<div class="title">

    <h3>Users | neXva.com</h3>

    <div class="selector" title="content_box">
     <a class="tab <? if($this->selected_tab == '' or $this->selected_tab == 'tab-list'){echo ' active';}?>" href="tab-list">List messages</a>
        <a class="tab <? if($this->selected_tab == 'tab-send' ){echo ' active';}?>" href="tab-send">Send Message</a>
       
    </div>
</div>
<div class="box">
    <div class="txt">
        <div style="padding:20px 0px" align="center">
            </div>
        <div id="content_box">
        
      
            <div class="tab-list">
            
       
            
                <!-- Start Table -->
                <table cellpadding="0" cellspacing="0">
                    
                    <thead>
                        <tr>
         
                            <th style="width: 20%">Subject</th>
                            <th style="width: 70%">Message</th>
                            <th style="width: 10%">Sent Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                        <? foreach($this->paginator as $user): ?>
                             <?= $this->partial('partials/row-cps_messages.phtml',array('user'=>$user,'show_app_icons'=>$this->show_app_icons)); ?>
                        <?endforeach; ?>
                        <?if($this->isCpMessageListEmpty  == true):?>
                        <tr>
                            <td colspan="3" style='text-align: center;'>
                                <small>
                                    <i>Cp list is empty.
                                    </i>
                                </small>
                            </td>
                        </tr>
                        <?endif; ?>
                    </tbody>
                </table>
                 <!-- End Table -->
                 <?= $this->paginationControl($this->paginator, 'Sliding', 'partials/paginator.phtml',array( 'tab' => 'tab-list')); ?>
            </div>

            
        <!-- tab not-approved -->
            <div class="tab-send">
                <?= $this->render('partials/message.phtml'); ?>
            
                <!-- Start pagecreate Form -->
                <form method="post" action="">
                    <fieldset>

                        <p><label>Subject</label>
                            <input type="text" id="subject" name="subject" class="txt-input medium" value="<?=$this->subject;?>"/>
                        </p>

                        <p><label>Body</label>
                            <textarea class="txt-input medium" id="wysiwyg" name="body"><?=$this->body;?></textarea>
                        </p>
                                   <input type="hidden" name ="id" value="<?=$this->userId; ?>">
                                   <input type="hidden" name ="tab" value="tab-send">
   
                        
                       
                        <p style="float:left;"><input type="submit" class="button" name="submit" value="Save" /><input type="button" class="button" name="button" value="Cancel" onClick="location.href='/country'"/>
                        </p>
                     <!--<p  class="remember"><input type="checkbox" /> Remember Me</p>-->
                    </fieldset>
                    
                </form>
                <!-- End Login Form -->

               
            </div>
            <!-- tab -->

           

            

        </div>
    </div>
</div>