<tr>
   
    <td>
        <?= $this->user->id ?>
    </td>
    <td>
        <?= $this->user->username ?>
    </td>
    <td>
        <?= $this->user->email ?>
    </td>
    <td>
        <?= ($this->user->status > 0) ? 'Active' : 'Blocked' ?>
    </td>
    <td>
        <?= $this->user->type; ?>
    </td>
     <td>
        <?php        
        $date = new DateTime($this->user->created_date);
        echo $date->format('Y-m-d');
        ?>
    </td>
    <td>
        <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/edit/id/<?=$this->user->id ?>"><img alt="Edit" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/edit.png" title="Edit"></a>
        <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>product-user-rule/index/chapId/<?=$this->user->id ?>"><img alt="Product Filters" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/book_add.png" title="Product Filters"></a>
        <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/chap-details/id/<?=$this->user->id ?>"><img alt="Edit" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/info.png" title="Details"></a>
        <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>chap-statistics/index/id/<?=$this->user->id ?>"><img alt="Stats" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/chart_bar.png" title="Stats"></a>
        <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/impersonate/id/<?=$this->user->id?>/type/chap" target="_blank" onclick="res = confirm('You are about to impersonate this User.\n\nAny action taken during an impersonation session would look as if it was done by the User and not you. If you are already logged into a CHAP account or currently impersonating another CP, your session will automatically end.\n\n*Please proceed with caution* \n\n Press OK to begin impersonating <?=$this->user->email?>');  return res;">
            <img alt="Impersonate" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/user_go.png" title="Impersonate">
        </a>
     	<a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/edit-contact-chap/id/<?=$this->user->id ?>"><img alt="Edit Contact" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/email_edit.png" title="Add / Edit Contact"></a>
     	<a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/assign-payouts/id/<?=$this->user->id ?>"><img alt="Assign Payouts" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/payout.png" title="Assign Payouts"></a>
     	<a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/set-currency/id/<?=$this->user->id ?>"><img alt="Assign Currency" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/money_dollar.png" title="Assign Currency"></a>
        <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/payment-gateway/id/<?=$this->user->id ?>"><img alt="Payment Gateway" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/payment-gateway.png" title="Payment Gateway"></a>
        <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/set-language/id/<?=$this->user->id ?>"><img alt="Language" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/language.png" title="Language"></a>
        <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/home-page-options/id/<?=$this->user->id ?>"><img alt="Language" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/options.png" title="Partner Site Options"></a>
     	<a class='del_conf' href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/delete/id/<?=$this->user->id ?>"><img alt="Delete" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/delete.png" title="Delete"></a>
    </td>
</tr>