<tr>
   
    <td>
        <?= $this->user->id ?>
    </td>
    <td>
        <?= $this->user->username ?>
    </td>
    <td>
        <?= $this->user->email ?>
    </td>
    <td>
        <?= ($this->user->status > 0) ? 'Active' : 'Blocked' ?>
    </td>
    <td>
        <?php 
         $userMeta = new Model_UserMeta();
         $verified  =  $userMeta->getAttributeValue($this->user->id,'VERIFIED_ACCOUNT');


         if($verified != '0'){ ?>
            <img alt="Verified account" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/accept.png" title="Verified account">
         <?php }else{ ?>
            <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/verify/id/<?=$this->user->id ?>"onclick="return confirm('Are you sure you want to verify this account?')"><img alt="Pending verify account" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/stop.png" title="Pending verify account"></a>
         <?php } ?>
 
    </td>
    
    <td>
        <?= $this->user->type; ?>
    </td>
    
    <td>
        <?php        
        $date = new DateTime($this->user->created_date);
        echo $date->format('Y-m-d');
        ?>
    </td>
    <td>
        <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/edit/id/<?=$this->user->id ?>"><img alt="Edit" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/edit.png" title="Edit"></a>
        
        <?php if($this->show_app_icons): ?>
            <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/apps/id/<?=$this->user->id ?>"><img alt="View all content of this CP" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/app.gif" title="View all content of this CP"></a>
        <?php endif; ?>
        <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/impersonate/id/<?=$this->user->id?>" target="_blank" onclick="res = confirm('You are about to impersonate this CP.\n\nAny action taken during an impersonation session would look as if it was done by the CP and not you. If you are already logged into a CP account or currently impersonating another CP, your session will automatically end.\n\n*Please proceed with caution* \n\n Press OK to begin impersonating <?=$this->user->email?>');  return res;">
            <img alt="Impersonate" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/user_go.png" title="Impersonate">
        </a>
        <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/manual-pay/id/<?=$this->user->id ?>/type/cp"><img alt="Manual Credit / Debit" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/money_dollar.png" title="Manual Credit / Debit"></a>
        
        <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/impersonate/id/<?=$this->user->id?>/type/cp-an" target="_blank">
            <img alt="Impersonate" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/chart_bar.png" title="Analytics">
        </a>
        <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>user/delete/id/<?=$this->user->id ?>"onclick="return confirm('Are you sure you want to delete?')"><img alt="Delete" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/delete.png" title="Delete"></a>
       

    </td>
</tr>