    <div class="title">

        <h3><?php echo $this->translate("User Login");?></h3>

        <div class="selector" title="content_box">
            <a class="tab active" href="tab-login"><?php echo $this->translate("Login");?></a>
            <a class="tab" href="tab-password"><?php echo $this->translate("Forgotten Password");?></a>
        </div>
    </div>
    <div class="box">
        <div class="txt">

            <div id="content_box">
                <div class="tab-login" id="login">

                    <?php if($this->error != ''){ ?>
                    <div class="message error">
                         <p><?php echo $this->translate($this->error);?></p>
                    </div>
                    <?php } ?>
                    <!-- Start Login Form -->
                    <form method="post" action="/user/login">
                        <fieldset>
                            <p><label><?php echo $this->translate("Username");?></label>
                                <input name="username" id="username" type="text" class="txt-input large"
                                       value="<?php if(isset($_COOKIE['username'])){echo $_COOKIE['username'];} ?>"/>
                            </p>


                            <p>
                                <label><?php echo $this->translate("password");?></label>
                                <input name="password" id="password" type="password" class="txt-input large"
                                       value="<?php if(isset($_COOKIE['password'])){echo $_COOKIE['password'];} ?>"/>
                            </p>

                            <p style="float:left;">
                                <input type="submit" class="button" name="submit" value="<?php echo $this->translate("Login");?>" />
                                <input type="reset" class="reset" name="reset" value="<?php echo $this->translate("Reset");?>" />
                                <input type="hidden" name="operation" value="login">
                            </p>
                            <p class="remember"><input type="checkbox" name="remember" id="remember" value="1"  checked="checked"/> <?php echo $this->translate("Remember Me");?></p>

                        </fieldset>
                        <p> Trouble logging in? <a href="/user/forgotpassword"> <?php echo $this->translate("Click here to reset your password");?></a> </p>

                    </form>
                    <!-- End Login Form -->

                </div>
                <div class="tab-password" id="forgot_password" onlick="document.location.href='/user/login/forgotpassword'">
                    <!-- Start Password Form -->
                    <form method="post" action="/user/login/forgotpassword">
                        <fieldset>
                            <p>
                                <label><?php echo $this->translate("E-mail");?></label>
                                <input name="email" id="email" type="text" class="txt-input large" />
                                <small><?php echo $this->translate("Enter the email address you signed up with and we'll email you a link to reset your password");?></small>
                            </p>

                            <input type="submit" class="button" name="submit" value="<?php echo $this->translate("Request Password");?>" />
                            <input type="hidden" name="operation" value="forgot_password">
                        </fieldset>

                    </form>
                    <!-- End Password Form -->
                </div>
            </div>

        </div>
    </div>

