<!-- Start Content Box #1 -->
<div class="title">

<h3>Paymet Gateways.. Edit</h3>


</div>
<div class="box">
<div class="txt">

<div id="content_box">
<div class="tab-login">
            <?=$this->render ( 'partials/message.phtml' );?>
                <!-- Start pagecreate Form -->
<form method="post" action="/paymentgateway/edit" id='payout_create'>
<fieldset>

<p><label>Name</label> <input type="text" id="paymetgatewayName"
	name="paymetgatewayName" class="txt-input medium validate(required)"
	value="<?=$this->paymentGateway ['name'];?>" /></p>

<p><label>Charge (%)</label> <input type="text" id="paymetgatewayCharge"
	name="paymetgatewayCharge" class="txt-input medium validate(number)"
	value="<?=$this->paymentGateway ['charge'];?>" /></p>

<p><label>Fixed Cost ($)</label> <input type="text"
	id="paymetgatewayFixedCost" name="paymetgatewayFixedCost"
	class="txt-input medium validate(number)"
	value="<?=$this->paymentGateway ['fixed_cost'];?>" /></p>


<div style="width: 600px;">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td><label>Supports Web</label> <input type="checkbox"
			name="supportsWeb" id="supportsWeb" value="1"
			<?php
			if ($this->paymentGateway ['supports_web'])
				echo "checked='checked'";
			
			?>></td>
		<td><label>Supports Mobile</label> <input
			type="checkbox" name="supportsMobile" id="supportsMobile" value="1"
			<?php
			if ($this->paymentGateway ['supports_mobile'])
				echo "checked='checked'";
			
			?>></td>
		<td><label>Supports Inapp</label> <input type="checkbox"
			name="supportsInapp" id="supportsInapp" value="1"
			<?php
			if ($this->paymentGateway ['supports_inapp'])
				echo "checked='checked'";
			
			?>></td>
		<td><label>Active</label> <input type="checkbox"
			name="status" id="status" value="1"
			<?php
			if ($this->paymentGateway ['status'])
				echo "checked='checked'";
			
			?>></td>
	</tr>
</table>
</div>

<p style="float: left;"><input type="submit" class="button"
	name="submit" value="Save" /></p>
<!--<p  class="remember"><input type="checkbox" /> Remember Me</p>--></fieldset>
<input type="hidden" name="id" id="id"
	value="<?=$this->paymentGateway ['id'];?>" /></form>
<!-- End Login Form --></div>

</div>

</div>
</div>
<!-- End Content Box #1 -->
