<div id="main_right_pane">


    <div class="inr_tabs_wrapper">
        <div class="inr_tab_bar"><span class="inr_brdcrtxt_pur">+</span> 
            <span class="inr_brdcrtxt_grey">   About Us    </span>
        </div>
        <div class="box_content_top"></div>
        <div class="box_content_middle">
            <div class="inrtab_selection_top inner_content" >


                <p><strong>Nex-Tech Wireless</strong><br>
                    Nex-Tech Wireless, a subsidiary of Rural Telephone, Golden Belt Telephone and Mutual Telephone, is a premiere wireless provider offering high-tech wireless solutions to residents in 40 counties of central and western Kansas as well as local coverage to 4 counties in Colorado. Nex-Tech Wireless focuses on providing its customers cutting-edge technology including data and mobile services, as well as the latest wireless equipment and competitive wireless plans that provide nationwide coverage.<br>
                </p>
                <p><strong>Why choose Nex-Tech Wireless?<br></strong>Great coverage! Nex-Tech Wireless has more towers in our local area than any other company. Customer service from the people you've come to know and trust. Access to the largest all digital networks in the United States. Technology that works for you at home, work or play! </p>
                <p><strong>When you choose Nex-Tech Wireless, your money stays at home!</strong><br>
                    Local chapters of charitable organizations like Big Brothers, Big Sisters, United Way and the American Red Cross all benefit from the dollars spent with your local wireless provider, Nex-Tech Wireless. Local schools benefit too. You can have 3% of your monthly service fee donated to a local school of your choice.<a href="http://www.nex-techwireless.com/Forms/SchoolRebateProgram.aspx"> Click here </a>to start giving; it doesn't cost you a thing! <br>
                </p>
                <p><strong>A great variety of calling plans and phone technology!</strong><br>
                    With nationwide and nationwide plus plans, individual rates, family plans and business packages, Nex-Tech Wireless has a plan for anyone! Plus, if you want the latest and greatest wireless phone technology, Nex-Tech Wireless has you covered. <br>
                </p>
                <p><strong>There is always a great deal waiting for you at Nex-Tech Wireless!</strong><br>
                    For more information, visit Nex-Tech Wireless online, any of our 40+ locations, or call Customer Service at <a href="tel:877-621-2600">877-621-2600</a> where a friendly customer care representative is ready to answer your questions!
                </p>
                <p></p>

            </div>

            <!--                                                    <div class="tab_selection_bottom"></div>-->

        </div>

    </div>
    <!-- box one-->


    <div style="clear: both;"></div>


</div>

