 <div id="main_right_pane">

	
	<div class="inr_tabs_wrapper">
		<div class="inr_tab_bar"><span class="inr_brdcrtxt_pur">+</span> 
			<span class="inr_brdcrtxt_grey">   Terms of Use   </span>
		</div>
	<div class="box_content_top"></div>
	<div class="box_content_middle">
	<div class="inrtab_selection_top inner_content" >
	



<p><strong> 1. Terms </strong></p>
<p>By accessing this web site, you are agreeing to be bound by  these web site Terms and Conditions of Use, all applicable laws and  regulations, and agree that you are responsible for compliance with any  applicable local laws. If you do not agree with any of these terms, you are  prohibited from using or accessing this site. The materials contained in this  web site are protected by applicable copyright and  trade mark  law. </p>
<p><strong> 2. Use License </strong></p>

<p> Permission  is granted to temporarily download one copy of the materials (information or  software) on Nex-Tech Wireless's web site for personal, non-commercial  transitory viewing only. This is the grant of a license, not a transfer of  title, and under this license you may not: </p>
  
  <ol>
    <li>modify or copy the materials; </li>
    <li>use the materials for any commercial purpose, or  for any public display (commercial or non-commercial); </li>
    <li>attempt to decompile or reverse engineer any software  contained on Nex-Tech Wireless's web site; </li>
    <li>remove any copyright or other proprietary notations  from the materials; or </li>
    <li>transfer the materials to another person or  &quot;mirror&quot; the materials on any other server. </li>
  </ol>

<p>This  license shall automatically terminate if you violate any of these restrictions  and may be terminated by Nex-Tech Wireless at any time. Upon terminating your  viewing of these materials or upon the termination of this license, you must  destroy any downloaded materials in your possession whether in electronic or  printed format. </p>
<p> <strong>3. Disclaimer</strong></p>

<p>The  materials on Nex-Tech Wireless's web site are provided &quot;as is&quot;.  Nex-Tech Wireless makes no warranties, expressed or implied, and hereby  disclaims and negates all other warranties, including without limitation,  implied warranties or conditions of merchantability, fitness for a particular  purpose, or non-infringement of intellectual property or other violation of  rights. Further, Nex-Tech Wireless does not warrant or make any representations  concerning the accuracy, likely results, or reliability of the use of the  materials on its Internet web site or otherwise relating to such materials or  on any sites linked to this site. </p>

<p> <strong> 4. Limitations </strong></p>
<p> In no event shall Nex-Tech Wireless or its suppliers be liable  for any damages (including, without limitation, damages for loss of data or  profit, or due to business interruption,) arising out of the use or inability  to use the materials on Nex-Tech Wireless's Internet site, even if Nex-Tech  Wireless or a Nex-Tech Wireless authorized representative has been notified  orally or in writing of the possibility of such damage. Because some  jurisdictions do not allow limitations on implied warranties, or limitations of  liability for consequential or incidental damages, these limitations may not  apply to you. </p>
<p> <strong> 5. Revisions and Errata </strong></p>
<p> The materials appearing on Nex-Tech Wireless's web site could  include technical, typographical, or photographic errors. Nex-Tech Wireless  does not warrant that any of the materials on its web site are accurate,  complete, or current. Nex-Tech Wireless may make changes to the materials  contained on its web site at any time without notice. Nex-Tech Wireless does  not, however, make any commitment to update the materials. </p>
<p> <strong> 6. Links </strong></p>
<p> Nex-Tech Wireless has not reviewed all of the sites linked to  its Internet web site and is not responsible for the contents of any such  linked site. The inclusion of any link does not imply endorsement by Nex-Tech  Wireless of the site. Use of any such linked web site is at the user's own  risk. </p>
<p> <strong> 7. Site Terms of Use Modifications </strong></p>
<p> Nex-Tech Wireless may revise these terms of use for its web site  at any time without notice. By using this web site you are agreeing to be bound  by the then current version of these Terms and Conditions of Use. </p>
<p> <strong> 8. Governing Law </strong></p>
<p> Any claim relating to Nex-Tech Wireless's web site shall be  governed by the laws of the State of Missouri without regard to its conflict of  law provisions. </p>
<p> General Terms and Conditions applicable to Use of a Web Site. </p>
	</div>
	
	<!--                                                    <div class="tab_selection_bottom"></div>-->
	
	</div>
	
	</div>
	<!-- box one-->

	
	<div style="clear: both;"></div>

	
</div>

