<div class="title">
    <h3><?php echo $this->translate("Coming soon!");?></h3>
</div>
<div class="box">
        <div class="txt">
            <p><?php echo $this->translate("Looks like you've stumbled across our upcoming analytics page.");?> 
            <?php echo $this->translate("We'll soon be giving you access to a suite of tools to help you get <br> better insight and quickly pinpoint trends about your application.");?>
            </p>
            
            <p><?php echo $this->translate("Check back soon");?></p>
        </div>
</div>