<!-- Start Content Box #2 -->
<div class="title">
</div>
<div class="box">
    <div class="txt">

        <div id="content_box">
            <div class="tab-table">



                <!-- Start Table -->
                <table cellpadding="0" cellspacing="0">
                    
                    <tbody>
                        <tr><td style="background-color:black"><img src="<?php echo PROJECT_BASEPATH;?>/cp/assets/img/global/logo.png" /></td></tr>
                        <tr><td style="padding:15px;"><?=$this->announcement['message'];?></td></tr>
                        
                    </tbody>
                </table>
                <!-- End Table -->

            </div>
        </div>
    </div>
</div>

<!-- End Content Box #2 -->