<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
		
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		
		<title>App Store Admin | Sign In</title>
		
		
		<!--                       CSS                       -->
	  
		<!-- Reset Stylesheet -->
		<link rel="stylesheet" href="<?php echo PROJECT_BASEPATH; ?>/pbo/css/reset.css" type="text/css" media="screen" />
	  
		<!-- Main Stylesheet -->
		<link rel="stylesheet" href="<?php echo PROJECT_BASEPATH; ?>/pbo/css/style.css" type="text/css" media="screen" />
		
		
		
		<!-- Invalid Stylesheet. This makes stuff look pretty. Remove it if you want the CSS completely valid -->
		<link rel="stylesheet" href="<?php echo PROJECT_BASEPATH; ?>pbo/css/invalid.css" type="text/css" media="screen" />	 
		<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" type="text/css" media="screen" />
			
		
		<!--                       Javascripts                       -->
  
		<!-- jQuery -->
		<script type="text/javascript" src="<?php echo PROJECT_BASEPATH; ?>pbo/js/jquery-1.3.2.min.js"></script>
		
		<!-- jQuery Configuration -->
		<script type="text/javascript" src="<?php echo PROJECT_BASEPATH; ?>pbo/js/simpla.jquery.configuration.js"></script>
		
	</head>
  
	<body id="login">
		
		<div id="login-wrapper" class="png_bg">
			<div id="login-top">
			
				
                     <img style="position: relative; top:0px;" src="<?php echo PROJECT_BASEPATH; ?>pbo/images/app_store.png" alt="App Store Admin"/>       
                     <h1 style="position: relative; top:0px;">App Store Admin</h1>
			</div> <!-- End #logn-top -->
			
                        <?= $this->layout()->content ?>    
		</div> <!-- End #login-wrapper -->
		
                <div class="clear"></div>
                                                
                                                 <!-- End .clear -->
			
				<small style="float: right; position: relative; right: 30px; top: 180px"> <!-- Remove this notice or replace it with whatever you want -->
						&#169; Copyright <?php echo date('Y');?>  | <img style="border: none; margin-left: 10px;" src="<?php echo PROJECT_BASEPATH; ?>pbo/images/logo_powered_byw.png" alt="Powered by neXva" /></a>
				</small>
		<div class="clear"></div>
  </body>
  
</html><!-- 
