<div class="content-box"><!-- Start Content Box -->
    <div class="content-box-header">
        <h3 style="cursor: s-resize;"><?= $this->title;?> <?php if(!empty($this->from)){echo ' From ',date('Y-m-d',$this->from);} if(!empty($this->to)) {echo ' To ',date('Y-m-d',$this->to);} if($this->payout > 0){ echo ' (Developer Payout ',$this->payout,' %)';}?></h3>
    </div> <!-- End .content-box-header -->

    <div class="content-box-content">
        <div class="tab-content default-tab">
            <table id="developer_table">
                <thead>
                    <tr>
                        <th>Company</th>
                        <th>No of Downloads</th>
                        <th>Amount</th>
                        <th>Developer Payout</th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach($this->records as $record) { ?>
                        <tr>
                            <td><?php echo $this->developer($record['productIDs']);?> <a id="test" href="/statistic/app-wise/user/<?php echo $record['userID'];if(!empty($this->from) && !empty($this->to)){ echo '/from/'.$this->from.'/to/'.$this->to;}?>/payout/<?php if($this->payout > 0){echo $this->payout;}?>">( View Details )</a></td>
                            <td><?php echo $record['downloads'];?></td>
                            <td><?php echo '$ ',number_format(round((($this->developerRevenue($record['productIDs']))),2),2).' - '.$this->CurrencyConvert($this->developerRevenue($record['productIDs']));?></td>
                            <td><?php
                                if($this->payout > 0)
                                {
                                    echo '$ ',number_format(round((($this->developerRevenue($record['productIDs'])*$this->payout/100)),2),2).' - '.$this->CurrencyConvert(($this->developerRevenue($record['productIDs'])*$this->payout/100));
                                }
                                else
                                {
                                    echo '$ ',number_format(round((($this->developerRevenue($record['productIDs']))),2),2).' - '.$this->CurrencyConvert($this->developerRevenue($record['productIDs']));
                                } ?>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#7').addClass('current');
    $('#74').addClass('current');
</script>