<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 11/12/13
 * Time: 4:39 PM
 * To change this template use File | Settings | File Templates.
 */
?>

<div class="content-box"><!-- Start Content Box -->
    <div class="content-box-header">
        <!--<h3 style="cursor: s-resize;">Statistics : <?php /*echo $this->deviceDetails[0]['brand'],' - ',$this->deviceDetails[0]['model'], ' Apps Downloaded';*/?></h3>-->
        <h3 style="cursor: s-resize;">Statistics : Downloaded apps on <?php echo $this->deviceDetails[0]['brand'],' - ',$this->deviceDetails[0]['model'];?></h3>
        <div id="icon_wrapper">

        </div>

    </div> <!-- End .content-box-header -->
    <div class="content-box-content">
        <table style="width:60%;margin-left: 15px;" border="0">
            <thead>
                <tr>
                    <th style="width:40%;">Downloaded Date</th>
                    <th style="width:40%;">Name</th>
                    <th style="width:20%;text-align:right;">Price</th>
                        <th style="width:20%;text-align:right;">in native currency</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->downloads as $download) { ?>
                    <tr>
                        <td valign="top" ><?php echo $download['date']; ?></td>
                        <td valign="top" ><?php echo $download['name']; ?></td>
                        <td valign="top" style="text-align:right;"><?php echo '$ ',$download['price']; ?></td>
                        <td valign="top" style="text-align:right;"><?php echo $this->CurrencyConvertPricePoints($download['price']); ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>

        <br />
        <div style ="width : 60%">
            <?php echo  $this->paginationControl($this->downloads, 'Sliding', 'partials/pagination-stats-device.phtml'); ?>
        </div>
        <br />

    </div>
</div>

<script type="text/javascript">
    $('#7').addClass('current');
    $('#72').addClass('current');
</script>