<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 4/21/14
 * Time: 11:18 AM
 * To change this template use File | Settings | File Templates.
 */
?>
<script type="text/javascript" >
    $(document).ready(function()
    {
        $("#fromDate").datepicker({ dateFormat: 'yy-mm-dd'});
        $("#toDate").datepicker({ dateFormat: 'yy-mm-dd'});
    });
</script>
<div class="content-box">
    <div class="content-box-header">
        <h3 style="cursor: s-resize;"><?php echo $this->title; ?></h3>
        <div id="icon_wrapper">

        </div>
    </div>
    <div class="content-box-content">
        <div style="width:99%;float: left;">
            <form method="post" action="<?php echo PBO_PROJECT_BASEPATH;?>statistic/downloaded-users/" id="frmManageApps" name="frmManageApps" class="pbo-admin-form">
                        <div style="float:left; width:50px; position: relative; left: 10px">
                            <label style="position: relative; top: 30px">Filter:</label>
                        </div>
                        <div style="float:left; width:140px; position: relative; left: 10px">
                            <label style="position: relative; left: 10px; width: 60px">From :</label>
                            <input style="width: 120px !important; left: 50px" type="text" class="text-input small-input" id="fromDate" name="fromDate" value="<?= (isset($this->fromDate) && $this->fromDate != 'all') ? $this->fromDate : '' ?>" />
                        </div>
                        <div style="float:left; width:140px; position: relative; left: 10px">
                            <label style="position: relative; left: 10px; width: 60px">To :</label>
                            <input style="width: 120px !important; left: 150px" type="text" class="text-input small-input" id="toDate" name="toDate" value="<?= (isset($this->toDate) && $this->toDate != 'all') ? $this->toDate : '' ?>" />
                        </div>
                        <div style="float:left; width:140px; position: relative; left: 10px">
                            <label style="position: relative; left: 10px; width: 60px">App ID :</label>
                            <input style="width: 120px !important; left: 150px" type="text" class="text-input small-input" id="appId" name="appId" value="<?= (isset($this->appId) && $this->appId != 'all') ? $this->appId : '' ?>" />
                        </div>
                        <div style="float:left; width:200px; position: relative; left: 10px">
                            <input style="margin-top: 22px;" type="submit" value="Filter" name="btnSubmit" id="btnSubmit" class="button" />
                        </div>
            </form>
        </div>
        <div class="clear"></div>
        <br /><br />
        <?php if($this->showResults == 'true' ) { ?>
            <table style="width:60%; margin-left: 15px;" border="0">
                <thead>
                <tr>
                    <th>User</th>
                    <th>Phone Number</th>
                    <th>Date</th>
                </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->downloadUsers as $downloadUser){ ?>
                        <tr>
                            <td valign="top"><?php echo $downloadUser->username;?></td>
                            <td valign="top"><?php echo $downloadUser->mobile_no;?></td>
                            <td valign="top"><?php echo $downloadUser->date;?></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
            <br />
            <?php
                $data = array(
                    "appId" => ($this->appId) ? $this->appId : '',
                    "fromDate" => ($this->fromDate) ? $this->fromDate : '',
                    "toDate" => ($this->toDate) ? $this->toDate : ''
                );
            ?>
            <div style ="width : 60%">
                <?= $this->paginationControl($this->downloadUsers, 'Sliding', 'partials/pagination-downloaded-users.phtml',$data); ?>
            </div>
            <br />
        <?php } else { ?>
            <p>No Records Found. </p>
            <br /><br />
        <?php } ?>
    </div>
</div>
<script type="text/javascript">
    $('#7').addClass('current');
    $('#73').addClass('current');
</script>