<?php $this->headLink()->appendStylesheet($this->Cdn('site_assets') . '/cp/assets/css/analytics.css'); ?>
<?php $this->headLink()->appendStylesheet(PROJECT_BASEPATH.'/admin/assets/css/smoothness/jquery-ui.css'); ?>
<?php $this->headScript()->appendFile($this->cdn('site_assets') . '/cp/assets/js/analytics/excanvas.min.js'); ?>
<?php $this->headScript()->appendFile($this->cdn('site_assets') . '/cp/assets/js/analytics/jquery.flot.js'); ?>
<?php $this->headScript()->appendFile($this->cdn('site_assets') . '/cp/assets/js/analytics/jquery.flot.pie.js'); ?>
<?php $this->headScript()->appendFile($this->cdn('site_assets') . '/cp/assets/js/analytics/jquery.flot.stack.js'); ?>

<?php $this->headScript()->captureStart(); ?>

var __DATA_DATE = eval(<?= $this->appViewDateJson; ?>); //app views by date
var __DATA_DOWNLOADS = eval(<?= $this->appDownloadDateJson; ?>); //downloads 

<?php $this->headScript()->captureEnd(); ?>
<?php $this->headScript()->appendFile($this->cdn('site_assets') . '/pbo/js/analytics/appview.js'); ?>
<script type="text/javascript"><!--
    
  
   $(document).ready(function() 
       {

	    $("#from").datepicker({ dateFormat: 'yy-mm-dd'});
    	$("#to").datepicker({ dateFormat: 'yy-mm-dd'});
    	
    	
    	var freePremiumViewRatiodata = [];

    	var pieSliceColors = [];
    	pieSliceColors['free'] = '#D07FF6';
    	pieSliceColors['premium'] = '#98c359';


        <?if($this->freePremiumViewsRatio): ?>
    	
    	jsonFreePremiumViewRatio = <?=$this->freePremiumViewsRatio;?>;
    	
    	k = 0;
	    $.each(jsonFreePremiumViewRatio, function(i, item) {
	    	freePremiumViewRatiodata.push({ label: i, data: item, color: pieSliceColors[i]});
	
	      });


	    $.plot($("#views_free_premium"), freePremiumViewRatiodata,
	    		{
	    		        series: {
	    		            pie: {
	    		                show: true,
	    		                radius: 1,
	    		                label: {
	    		                    show: true,
	    		                    radius: 1,
	    		                    formatter: function(label, series){
	    		                        return '<div style="font-size:8pt;text-align:center;padding:2px;color:white;">'+label+'<br/>'+Math.round(series.percent)+'%</div>';
	    		                    },
	    		                    background: { opacity: 0.8 }
	    		                },
	    		            }
	    		        },
	    		        legend: {
	    		            show: false
	    		        }
	    		});

     <?endif;?>  

     <?if($this->freePremiumDownloadRatio): ?>
	    
    	jsonFreePremiumDownloadRatio = <?=$this->freePremiumDownloadRatio;?>;

    	var freePremiumDownloadRatiodata = [];
    	
	    $.each(jsonFreePremiumDownloadRatio, function(i, item) {
	    	freePremiumDownloadRatiodata.push({ label: i, data: item, color: pieSliceColors[i] });
	      });
   
    $.plot($("#downloads_free_premium"), freePremiumDownloadRatiodata,
    		{
    		        series: {
    		            pie: {
    		                show: true,
    		                radius: 1,
    		                label: {
    		                    show: true,
    		                    radius: 1,
    		                    formatter: function(label, series){
    		                        return '<div style="font-size:8pt;text-align:center;padding:2px;color:white;">'+label+'<br/>'+Math.round(series.percent)+'%</div>';
    		                    },
    		                    background: { opacity: 0.8 }
    		                }
    		            }
    		        },
    		        legend: {
    		            show: false
    		        }
    		});
    <?endif;?>  
});

</script>




<div class="content-box">
    <div class="content-box-header">
        <h3 style="cursor: s-resize;"><?= $this->title; ?>   
            Ecarrot Paid Users
        </h3>
    </div> 

    <div class="content-box-content">

        <form id="regUserForm" style='width:auto;' name="regUserForm" action="/statistic/ecarrot-paid-user" method="post">


            <p style="text-align: center;"> 

                <input type="text" class="text-input date" id="from" name="from" value="<?= $this->startDate ?>" />
                <input type="text" class="text-input date" id="to" name="to" value="<?= $this->endDate ?>" />
                <input type="submit" value="Filter" name="submit" class="button" />
            </p>               

        </form>


        <div class="content-box-content">
            <div style="">

                <table cellspacing="0" cellpadding="0" style="width:100%; margin-left: 15px;">
                    <thead>
                        <tr>
                            <th>Email</th>
                            <th>Mobile Number</th>
                            <th>Started Date</th>
                            <th>Varification Date</th>
                            <th>End Date</th>
                            <th>Payment Start Date</th>
                            <th>Final Payment Date</th>
                            <th>Profile Status</th>
                        </tr>
                    </thead>
                   
                    <?php if (count($this->earrotUser) > 0) { ?>
                        <?php foreach ($this->earrotUser as $eUser) { ?>                    
                            <?= $this->partial('partials/ecarrot_paid_user.phtml', array("ecarrotUser" => $eUser)); ?>
                        <?php } ?>
                    <?php } else { ?>
                        <tr>
                            <td colspan = "8"  style="text-align: center;">No Sales </td>           
                        </tr>
                    <?php } ?>

                </table>


            </div>





            <div style="clear: both;"></div>
        </div>


    </div>

</div>



<script type="text/javascript">
     $('#7').addClass('current');                                             
    $('#88').addClass('current');
</script>