<script type="text/javascript" >
        $(document).ready(function() 
        {
            $("#fromDate").datepicker({ dateFormat: 'yy-mm-dd'});
            $("#toDate").datepicker({ dateFormat: 'yy-mm-dd'});
        });
</script>
<div class="content-box"><!-- Start Content Box -->
    <div class="content-box-header">
        <h3 style="cursor: s-resize;"><?= $this->title; ?></h3>

        <div id="icon_wrapper">

        </div>

    </div> <!-- End .content-box-header -->

    <div class="content-box-content">
<!--        <p>Developer</p>
        <p>Teloc</p>        
        <p>CCA</p>
        <p>neXva</p>-->
        
        <div id="wrapper_main">
            
            <div style="width:90%;float: left;">
                <form id="frmPayotus" name="frmPayotus" action="<?php echo PBO_PROJECT_BASEPATH;?>statistic/payout" method="post">
                    
                    <div style="float:left; width:50px; position: relative; left: 10px">
                        <label style="position: relative; top: 30px">Filter:</label>
                    </div>
                        
                    <div style="float:left; width:140px; position: relative; left: 10px">
                        <label style="position: relative; left: 10px; width: 60px">From :</label>
                        <input style="width: 120px !important; left: 50px" type="text" class="text-input small-input" id="fromDate" name="fromDate" value="<?= (isset($this->fromDate) && $this->fromDate != 'all') ? $this->fromDate : '' ?>" />
                   </div>  
                        
                    <div style="float:left; width:140px; position: relative; left: 10px">
                        <label style="position: relative; left: 10px; width: 60px">To :</label>
                        <input style="width: 120px !important; left: 150px" type="text" class="text-input small-input" id="toDate" name="toDate" value="<?= (isset($this->toDate) && $this->toDate != 'all') ? $this->toDate : '' ?>" />
                    </div> 
                        
                    <div style="float:left; width:200px; position: relative; left: 10px">
                        
                        <input style="margin-top: 22px;" type="submit" value="Filter" name="btnSubmit" id="btnSubmit" class="button" />
                        <a href="/statistic/payout/view/all">View Grand Total</a>
                    </div>           
                                                                    
                </form>
            </div>
            <div class="clear"></div>
            <br/><br/>
            <h3 style="padding-left: 5px"><?= $this->payoutTitle; ?></h3>
            <table class="no-style medium" style="width: 60%">
            <tbody>
                <tr>
                   
                    <td>Developer <a href="<?= $this->detailsUrl.'/payout/'.isset($this->payoutDetails->payout_cp)?$this->payoutDetails->payout_cp:"";?>">(View Details)</a></td>
                    <td style="text-align: right">(<?= isset($this->payoutDetails->payout_cp)?$this->payoutDetails->payout_cp:"";; ?> %)</td>
                    <td class="ta-right">$ <?= number_format(round((($this->totalAllSales * isset($this->payoutDetails->payout_cp)?$this->payoutDetails->payout_cp:"") /100),2),2) ?> <?=$this->CurrencyConvert(($this->totalAllSales * isset($this->payoutDetails->payout_cp)?$this->payoutDetails->payout_cp:"") /100);?></td>
                   
                </tr>
                <tr>
                    <td><?= strtoupper(Zend_Auth::getInstance()->getIdentity()->username); ?></td>
                    <td style="text-align: right">(<?= isset($this->payoutDetails->payout_chap)?$this->payoutDetails->payout_chap:"";; ?> %)</td>
                    <td class="ta-right">$ <?= number_format(round((($this->totalAllSales * isset($this->payoutDetails->payout_chap)?$this->payoutDetails->payout_chap:"") /100),2),2) ?> <?=$this->CurrencyConvert(($this->totalAllSales * isset($this->payoutDetails->payout_chap)?$this->payoutDetails->payout_chap:"") /100);?></td>
                   
                </tr>
                <?php if(($this->payoutDetails->payout_super_chap != 0) && !is_null($this->payoutDetails->payout_super_chap) && !empty($this->payoutDetails->payout_super_chap)): ?>
                <tr>
                    <td>CCA</td>
                    <td style="text-align: right">(<?= $this->payoutDetails->payout_super_chap; ?> %)</td>
                    <td class="ta-right">$ <?= number_format(round((($this->totalAllSales * $this->payoutDetails->payout_super_chap) /100),2),2) ?><?=$this->CurrencyConvert(($this->totalAllSales * $this->payoutDetails->payout_super_chap) /100);?></td>                   
                </tr>
                <?php endif; ?>
                <tr>
                    <td>neXva</td>
                    <td style="text-align: right">(<?= isset($this->payoutDetails->payout_nexva)?$this->payoutDetails->payout_nexva:""; ?> %)</td>
                    <td class="ta-right">$ <?= number_format(round((($this->totalAllSales * isset($this->payoutDetails->payout_nexva)?$this->payoutDetails->payout_nexva:"") /100),2),2) ?> <?=$this->CurrencyConvert(($this->totalAllSales * isset($this->payoutDetails->payout_nexva)?$this->payoutDetails->payout_nexva:"") /100)?></td>
                    
                </tr>
                
                <tr>
                    <td><span style="font-weight: bold; font-size: 13px">Total</span></td>
                    <td></td>
                     <td class="ta-right"><span style="font-weight: bold; font-size: 13px">$ <?php echo $this->totalAllSales ?>  <?=$this->CurrencyConvert($this->totalAllSales)?></span></td>                   
                </tr>
            </tbody>
        </table>
        </div>
    </div>
<br />
</div>

<script type="text/javascript">        
   $('#7').addClass('current');  
   $('#78').addClass('current'); 
</script>