<script type="text/javascript" language="javascript">



function load_poup_box(contentId)
{   
    
      $("#apps_"+contentId).fancybox({            
                'titleShow'     : false,
                'padding'	: 0,
                'transitionIn'	: 'elastic',
                'transitionOut'	: 'elastic',
                'autoDimensions': false, 
                'width'		: 300, 
                'height'	: 550,
                'showCloseButton' : true,
                'hideOnOverlayClick' : false            
            });
}
</script>


<!-- Pop-up window for displaying apps downloaded by the users -->
<?=$this->partial('partials/downloaded_apps_device.phtml')?>

<div class="content-box"><!-- Start Content Box -->
    <div class="content-box-header">
        <h3 style="cursor: s-resize;"><?= $this->title; ?></h3>
        
         <div id="icon_wrapper">
            
        </div>

    </div> <!-- End .content-box-header -->

<div class="content-box-content">
    
    <div style="width:99%;float: right;">

    <form method="post" action="<?php echo PBO_PROJECT_BASEPATH;?>statistic/user-wise/" id="frmManageApps" name="frmManageApps" class="pbo-admin-form">
        <div class="form-block-2">
            <label>Phone Number:</label>
            <input type="text" class="text-input" id="txtSearchKey" name="txtSearchKey" value="<?= isset($this->txtSearchKey) ? $this->txtSearchKey : '' ?>" />
            <input style="margin-top:10px !important; " type="submit" value="Search" name="btnSubmit" id="btnSubmit" class="button" />  <?php  if(Zend_Auth::getInstance()->getIdentity()->id == 81449 ) { echo 'e.g.2348022123456'; }  ?>
        </div>
    </form>

</div>

<div class="clear"></div>
<br /><br />

        <? if($this->showResults == 'true' ) : ?>
    
    
        <table style="width: 97% !important; margin-left: 15px;" border="0">
            <thead>
                <tr>                    
                    <th>Mobile Number</th>
                    <th style="text-align: center;">Downloads</th>
                    <th style="text-align: center;">Total Price</th>
                </tr>
            </thead>
            <tbody>

                <? foreach ($this->downloads as $download): ?>
                    <tr>                        
                        <td valign="top"><?= $download['mobile_no']; ?></td>
                        <td style="text-align: center;" valign="top"><?= $download['download_count']; ?>
                            
                            <?php if($download['download_count']>0) : ?>
                           
                                 <!--<a title="View Apps" href="#app_view" id="apps_<?/*= $download['id'] */?>">
                                    <img alt="View Apps" style="position: relative; top: 4px" src="/pbo/images/icons/view-details.png" onClick="get_device_apps(<?/*= $download['id'] */?>);load_poup_box(<?/*= $download['id'] */?>)"/>
                                 </a>-->

                                <a title="View Apps" href="/statistic/user-wise-details/id/<?php echo $download['user_id'];?>" >
                                    <img alt="View Apps" style="position: relative; top: 4px" src="/pbo/images/icons/view-details.png" />
                                 </a>


                            <?php endif; ?>
                            
                        </td> 
                        <td valign="top" class="align-right"><?php echo $this->CurrencyConvertPricePoints($download['total']); ?></td>
                    </tr>
                <? endforeach; ?>
            </tbody>
        </table>
            
    <br />
    <div style ="width: 97% !important;">
        <?= $this->paginationControl($this->downloads, 'Sliding', 'partials/pagination-stats-device.phtml'); ?>
    </div>
    <br />
    
    <? else : ?>
        
        <p>No Records Found. </p>
        <br /><br />
          
   <? endif ; ?>
</div>
</div>


<script type="text/javascript">        
   $('#7').addClass('current');  
   $('#79').addClass('current'); 
</script>