<?php echo $this->translate("Please enter First Name");?>
<?php echo $this->translate("Please enter Last Name");?>
<?php echo $this->translate("Please enter your Email address");?>
<?php echo $this->translate("Please enter a valid Email address for your Email");?>
<?php echo $this->translate("Please enter your Phone Number");?>
<?php echo $this->translate("Mobile Number cannot be less than 10 digits");?>
<?php echo $this->translate("Please enter your Password");?>
<?php echo $this->translate("Please confirm your Password");?>
<?php echo $this->translate("Password not Matching");?>
<?php echo $this->translate("This Email already exists");?>
<?php echo $this->translate("You have completed your registration successfully");?>
<?php echo $this->translate("This Phone Number already exists");?>
<?php echo $this->translate("A verification SMS has been sent to your mobile. Please use the given verification code to complete your registration");?>
<?php echo $this->translate("Verification failed. verification code is incorrect");?>
<?php echo $this->translate("You successfully completed the registration process");?>
<?php echo $this->translate("Already Verified User");?>
<?php echo $this->translate("The username or password you entered is incorrect");?>
<?php echo $this->translate('You have not verified your account. A verification SMS has been sent to your mobile . Please use the given verification code or get it resent by clicking below "Resend verification code" to verify your account');?>
<?php echo $this->translate("Please enter a valid username");?>
<?php echo $this->translate("Please enter your username and password");?>
<?php echo $this->translate("Please enter your Mobile Number");?>
<?php echo $this->translate("Mobile Number not Matching");?>
<?php echo $this->translate("This number has already been used. Please try another");?>
<?php echo $this->translate("Mobile number changed successfully");?>
<?php echo $this->translate("Please confirm your Mobile Number");?>
<?php echo $this->translate("Password reset successfully");?>
<?php echo $this->translate("Please enter your Email");?>
<?php echo $this->translate("User not found registered with this email");?>
<?php echo $this->translate("Mobile number not registered");?>
<?php echo $this->translate("You have requested to change password. A verification SMS has been sent to your mobile. Please use the given verification code to verify");?>
<?php echo $this->translate("Please enter your Verification Code");?>
<?php echo $this->translate("Verification code is incorrect");?>
<?php echo $this->translate("Verification code is incorrect.");?>
<?php echo $this->translate("Mobile Number not found for this user");?>
<?php echo $this->translate("Email not found for this user");?>
<?php echo $this->translate("You have requested to resend verification code. A verification SMS has been sent to your mobile. Please use the given verification code to verify your account");?>
<?php echo $this->translate("Newest");?>
<?php echo $this->translate("Top Free");?>
<?php echo $this->translate("Top Paid");?>
<?php echo $this->translate("Top Downloads");?>
<?php echo $this->translate("Free");?>
<?php echo $this->translate("Download");?>
<?php echo $this->translate("Description");?>
<?php echo $this->translate("Screenshots");?>
<?php echo $this->translate("Account");?>
<?php echo $this->translate("Updates");?>
<?php echo $this->translate("Help");?>
<?php echo $this->translate("Home");?>
<?php echo $this->translate("Premium");?>
<?php echo $this->translate("Login");?>
<?php echo $this->translate("Email");?>
<?php echo $this->translate("Password");?>
<?php echo $this->translate("Sign Up");?>
<?php echo $this->translate("Sign In");?>
<?php echo $this->translate("Forgot Password?");?>
<?php echo $this->translate("Downloaded Apps");?>
<?php echo $this->translate("Reset Password");?>
<?php echo $this->translate("Change Mobile");?>
<?php echo $this->translate("Terms & Conditions");?>
<?php echo $this->translate("Mobile Number");?>
<?php echo $this->translate("New Password");?>
<?php echo $this->translate("Confirm Password");?>
<?php echo $this->translate("Confirm Mobile Number");?>
<?php echo $this->translate("Staff Picks");?>
<?php echo $this->translate("Staff Picks");?>
<?php echo $this->translate("Top Premium");?>
<?php echo $this->translate("Buy");?>
<?php echo $this->translate("Download Started");?>
<?php echo $this->translate("Later");?>
<?php echo $this->translate("Updates are apps that have a newer version. This is either added functionalities, bug fixes or improvements");?>
<?php echo $this->translate('Please use this verification code 888555 to complete your registration. "MTN CONGO APP STORE"');?>
<?php echo $this->translate('Please use this verification code 888666 to verify your mobile number. "MTN CONGO APP STORE"');?>
<?php echo $this->translate('Please use this verification code 8886656 to complete the password resetting process. "MTN CONGO APP STORE"');?>
<?php echo $this->translate('Please use this verification code 7878778 as you requested. "MTN CONGO APP STORE"');?>
<?php echo $this->translate("Next");?>
<?php echo $this->translate("Previous");?>
<?php echo $this->translate("For any customer service issues, bugs in the app downloaded, difficulty downloading or purchases made by mistake please contact us at this email :");?>
<?php echo $this->translate("We will get back to you within 48 hours.");?>
<?php echo $this->translate("Verify");?>
<?php echo $this->translate("Resend Verification Code");?>
<?php echo $this->translate("First Name");?>
<?php echo $this->translate("Last Name");?>
<?php echo $this->translate("Phone Number");?>
<?php echo $this->translate("Register");?>
<?php echo $this->translate("Verification Code");?>
<?php echo $this->translate("Change Mobile Number");?>
<?php echo $this->translate("Forgot Password");?>
<?php echo $this->translate("Request");?>
<?php echo $this->translate("Please use this verification code");?>
<?php echo $this->translate("to complete your registration.");?>
<?php echo $this->translate("to verify your mobile number.");?>
<?php echo $this->translate("to complete the password resetting process.");?>
<?php echo $this->translate("as you requested.");?>
<?php echo $this->translate("Please enter your username");?>
<?php echo $this->translate("Please enter your password");?>
<?php echo $this->translate("The username or password you entered is incorrect");?>
<?php echo $this->translate("Please enter a valid username");?>
<?php echo $this->translate("Please enter your username and password");?>
<?php echo $this->translate("Account");?>
<?php echo $this->translate("Updates");?>
<?php echo $this->translate("Help");?>
<?php echo $this->translate("Premium");?>
<?php echo $this->translate("Downloaded Apps");?>
<?php echo $this->translate("Change Mobile");?>
<?php echo $this->translate("Terms & Conditions");?>
<?php echo $this->translate("Download Started");?>
<?php echo $this->translate("Later");?>
<?php echo $this->translate("Updates are apps that have a newer version. This is either added functionalities, bug fixes or improvements");?>
<?php echo $this->translate("For any customer service issues, bugs in the app downloaded, difficulty downloading or purchases made by mistake please contact us at this email :");?>
<?php echo $this->translate("We will get back to you within 48 hours.");?>
<?php echo $this->translate("Payment was unsuccessful");?>
<?php echo $this->translate("Paid");?>
<?php echo $this->translate("Required infromation");?>
<?php echo $this->translate("Info");?>
<?php echo $this->translate("Feature");?>
<?php echo $this->translate("Please download the");?>
<?php echo $this->translate("App store app using the following methods.");?>
<?php echo $this->translate("FEEDBACK");?>
<?php echo $this->translate("LOGIN HERE");?>
<?php echo $this->translate("To download this app you need to visit the following URL");?>
<?php echo $this->translate("App Store All Rights Reserved.");?>
<?php echo $this->translate("See all results for");?>
<?php echo $this->translate("No results found");?>
<?php echo $this->translate("Sorry! Couldn't find Apps matching your search criteria");?>
<?php echo $this->translate("Have an Issue?");?>
<?php echo $this->translate("You are not signed in yet");?>
<?php echo $this->translate("No Match Found");?>
<?php echo $this->translate("Ok");?>
<?php echo $this->translate("You haven't log in yet ? Please log in.");?>
<?php echo $this->translate("No Data Found");?>
<?php echo $this->translate("Downloading");?>
<?php echo $this->translate("Login to add a ticket");?>
<?php echo $this->translate("Search Results for");?>
<?php echo $this->translate("Powered by");?>
<?php echo $this->translate("The security key wasn't entered correctly");?>
<?php echo $this->translate("Please try again");?>
<?php echo $this->translate("Add a ticket");?>
<?php echo $this->translate("View my ticket");?>
<?php echo $this->translate("Subject");?>
<?php echo $this->translate("Type");?>
<?php echo $this->translate("Priority");?>
<?php echo $this->translate("Select Type");?>
<?php echo $this->translate("Question");?>
<?php echo $this->translate("Incident");?>
<?php echo $this->translate("Problem");?>
<?php echo $this->translate("Select Priority");?>
<?php echo $this->translate("Low");?>
<?php echo $this->translate("Medium");?>
<?php echo $this->translate("High");?>
<?php echo $this->translate("Urgent");?>
<?php echo $this->translate("Your ticket submitted successfully");?>
<?php echo $this->translate("Your response submitted successfully");?>
<?php echo $this->translate("Responces");?>
<?php echo $this->translate("No Response found");?>
<?php echo $this->translate("Reply");?>
<?php echo $this->translate("Submit");?>
<?php echo $this->translate("Platforms");?>
<?php echo $this->translate("Please add your Commenst with more than 10 letters");?>
<?php echo $this->translate("No apps found under this category");?>
<?php echo $this->translate("For any customer service issues, bugs in the app downloaded, difficulty downloading or purchases made by mistake please add a ticket. We will get back to you within 48 hours.");?>
<?php echo $this->translate("This app is only available in the following languages");?>
<?php echo $this->translate("This app-store will be supported for subscribers only");?>
<?php echo $this->translate("To download this app you need to install");?>
<?php echo $this->translate("on your Android device and sign in.");?>
<?php echo $this->translate("If you want to install");?>
<?php echo $this->translate("on your phone use following methods.");?>
<?php echo $this->translate("Do not have a QR code reader? Get one free");?>
<?php echo $this->translate("We're sorry, the keyword/s you searched for did not return any results");?>
<?php echo $this->translate("Please fill the Name");?>
<?php echo $this->translate("Page not found. (404 - Not Found)");?>
<?php echo $this->translate("Please select a type");?>
<?php echo $this->translate("ticket");?>
<?php echo $this->translate("open");?>
<?php echo $this->translate("Dashboard");?>
<?php echo $this->translate("Please select a priority");?>
<?php echo $this->translate("Please add a subject");?>
<?php echo $this->translate("Login here");?>
<?php echo $this->translate("Login type");?>
<?php echo $this->translate("Sign in as parents or university students");?>
<?php echo $this->translate("Sign in as students");?>
<?php echo $this->translate("Pin");?>
<?php echo $this->translate("Student account not found");?>
<?php echo $this->translate("Pin you entered is incorrect");?>
<?php echo $this->translate("The student id or password you entered is incorrect");?>
<?php echo $this->translate("The user name or password you entered is incorrect");?>
<?php echo $this->translate("Privacy");?>
<?php echo $this->translate("The mobile number or password you entered is incorrect");?>
<?php echo $this->translate("Featured Apps");?>
<?php echo $this->translate("Please enter a valid mobile number");?>
<?php echo $this->translate("Please enter your mobile number and password");?> 
<?php echo $this->translate("Please enter a valid number");?>
<?php echo $this->translate("User not found registered with this phone number");?>
<?php echo $this->translate("This field is required");?>
<?php echo $this->translate("Please enter at least 5 characters");?>
<?php echo $this->translate("This Phone Number already exists. Please try using forgot password");?>
<?php echo $this->translate("Please enter at least");?>
<?php echo $this->translate("characters");?>
<?php echo $this->translate("Update Profile");?>
<?php echo $this->translate("Update");?>
<?php echo $this->translate("Please fill all the required fields");?>
<?php echo $this->translate("Open");?>
<?php echo $this->translate("My Tickets");?>
<?php echo $this->translate("Responses");?>
<?php echo $this->translate("Response");?>
<?php echo $this->translate("18 Years or Older");?>
<?php echo $this->translate("Content Warning");?>
<?php echo $this->translate("Yes");?>
<?php echo $this->translate("No");?>
<?php echo $this->translate("Sign Out");?>
<?php echo $this->translate("To download this app you need to install MTS Appstore on your Android device and sign in.");?>