<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="en-us" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

        <?php if ($this->headTitle() != '<title></title>') : ?>
            <?= $this->headTitle($this->title); ?>
        <?php else : ?>
            <title>neXva.com - mobile reloaded - CHAP Back Office</title>
        <?php endif; ?>
        

        <!-- Core Stylesheet -->
        <link href="/chap/assets/css/core.css" media="screen" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" type="text/css" href="/chap/assets/css/red.css" title="styles2" media="screen" />
        <link rel="stylesheet" type="text/css" href="/chap/assets/css/chap.css" title="styles2" media="screen" />
        <link rel="stylesheet" type="text/css" href="/chap/assets/css/smoothness/jquery-ui.css" media="screen" />
        <!-- Javascript Files -->
        <script type="text/javascript" src="<?=$this->cdn('jquiry')?>"></script> 
        <script type="text/javascript" src="<?=$this->cdn('jquiryui')?>"></script>
        <script type="text/javascript" src="/chap/assets/js/hoverIntent.js"></script>
        <script type="text/javascript" src="/chap/assets/js/superfish.js"></script>
        <script type="text/javascript" src="/chap/assets/js/jquery.wysiwyg.js"></script>
        <script type="text/javascript" src="/chap/assets/js/jquery-stylesheetToggle.js"></script>
        <script type="text/javascript" src="/chap/assets/js/forestcp.js"></script>

        <!-- Adding dynamic libs and CSS Meta to the layout view -->
        <?php
        echo $this->headMeta();
        echo $this->headScript();
        echo $this->headStyle();
        echo $this->headLink();
        ?>
        <!--[if IE 6]>
        <link href="/chap/assets/css/ie6.css" media="screen" rel="stylesheet" type="text/css" />
        <script src="/chap/assets/js/DD_belatedPNG_0.0.8a-min.js"></script>
        <script>
          /* EXAMPLE */
          DD_belatedPNG.fix('.logo img, .message, table img');

          /* string argument can be any CSS selector */
        </script>
        <![endif]-->
        <script type='text/javascript'>
        $(document).ready(function(){
            $('a.del_conf').click(function(){
                return confirm('Are you sure you want to delete this item?');
            })
        });
        </script>
    </head>
    <body>
        <!-- Dialogs -->
        <div id="welcome" style="display: none" title="Welcome to ForestCP">
            <p>ForestCP is an great and easy to customize backend administration user interface.</p>
        </div>


        <?php echo $this->render('parts/chap/header.phtml'); ?>
        <?php echo $this->render('parts/chap/menu.phtml'); ?>

        <!-- Start Wrap -->
        <div id="wrap" class="fixed">
            <div id="content">


                <noscript>
                    <!-- Show message when javascript is not enabled -->
                    <div class="message error">
                        <p>Javascript is needed for this template to work properly. <br />Please <a href="http://browsehappy.com/" title="Upgrade to a better browser">upgrade</a> your browser or <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Enable Javascript in your browser">enable</a> Javascript to navigate the interface properly.</p>
                    </div>
                </noscript>
                <?php echo $this->layout()->content ?>
            </div>

        </div>
        <!-- End Wrap -->

        <!-- Footer -->
        <?= $this->render('/parts/chap/footer.phtml'); ?>
        <!-- Footer -->
       <?php echo $this->partial('/parts/analytics.phtml')?>   
    </body>
</html><!-- 