<?php echo $this->translate("Attach a file from your computer");?>
<?php echo $this->translate("File size");?>
<?php echo $this->translate("Add a Reply");?>
<?php echo $this->translate("Click Here");?>
<?php echo $this->translate("Apps");?>
<?php echo $this->translate("Categories");?>
<?php echo $this->translate("collection");?>
<?php echo $this->translate("Featured");?>
<?php echo $this->translate("Free Collection");?>
<?php echo $this->translate("Most");?>
<?php echo $this->translate("Need Help?");?>
<?php echo $this->translate("Premium Collection");?>
<?php echo $this->translate("Top");?>
<?php echo $this->translate("Top Collection");?>
<?php echo $this->translate("viewed collection");?>
<?php echo $this->translate("Search");?>
<?php echo $this->translate("Select Your Device");?>
<?php echo $this->translate("Selecting a device helps us filter apps that are compatible with your handset.");?>
<?php echo $this->translate("Start typing the name of your device");?>
<?php echo $this->translate("No Device Selected");?>
<?php echo $this->translate("Click To Select A Mobile Device");?>
<?php echo $this->translate("Click on thumbnail to zoom");?>
<?php echo $this->translate("Screenshots");?>
<?php echo $this->translate("Nexva All Rights Reserved.");?>
<?php echo $this->translate("Mobile Number or password is incorrect");?>
<?php echo $this->translate("Mobile");?>
<?php echo $this->translate("Products, Logos and Companies mentioned herein are trademarks or trade names of their respective owners and therefore copyrighted.");?>
<?php echo $this->translate("Register");?>
<?php echo $this->translate("Sign In");?>
<?php echo $this->translate("IRR");?>
<?php echo $this->translate("Welcome");?>
<?php echo $this->translate("You Are Here");?>
<?php echo $this->translate("Buy ");?>
<?php echo $this->translate("Buy");?>
<?php echo $this->translate("Buy : ");?>
<?php echo $this->translate("Description");?>
<?php echo $this->translate("Free");?>
<?php echo $this->translate("Free Download");?>
<?php echo $this->translate("Price : ");?>
<?php echo $this->translate("Price");?>
<?php echo $this->translate("Rate");?>
<?php echo $this->translate("Rate ");?>
<?php echo $this->translate("Rate : ");?>
<?php echo $this->translate("Vendor");?>
<?php echo $this->translate("Vendor : ");?>
<?php echo $this->translate("Whats new");?>
<?php echo $this->translate("Free Stuff");?>
<?php echo $this->translate("Logout");?>
<?php echo $this->translate("Most Viewed");?>
<?php echo $this->translate("Newest");?>
<?php echo $this->translate("SEARCH");?>
<?php echo $this->translate("Staff Picks");?>
<?php echo $this->translate("Rating");?>
<?php echo $this->translate("Supported Formats");?>
<?php echo $this->translate("Latest Reviews");?>
<?php echo $this->translate("No user reviews yet..");?>
<?php echo $this->translate("Please login to post a review.");?>
<?php echo $this->translate("Name");?>
<?php echo $this->translate("Title");?>
<?php echo $this->translate("Review");?>
<?php echo $this->translate("Home");?>
<?php echo $this->translate("To download this app you need to install");?>
<?php echo $this->translate("on your Android device and sign in.");?>
<?php echo $this->translate("To register you need to install");?>
<?php echo $this->translate("on your Android device. Registration happens on your device.");?>
<?php echo $this->translate("Please download the App store app using the following methods.");?>
<?php echo $this->translate("The app you have selected has been pushed directly to your device. Be sure to have the");?>
<?php echo $this->translate("installed on your phone first.");?>
<?php echo $this->translate("If you don't have");?>
<?php echo $this->translate("installed on your phone here is how to get it");?>
<?php echo $this->translate("If you want to install");?>
<?php echo $this->translate("on your phone use following methods.");?>
<?php echo $this->translate("Type in your email address and we will email it to you");?>
<?php echo $this->translate("your email");?>
<?php echo $this->translate("send email");?>
<?php echo $this->translate("Point your mobile browser to the following link:");?>
<?php echo $this->translate("Scan the QR code using your phone to be directly taken to the app page");?>
<?php echo $this->translate("Do not have a QR code reader?");?>
<?php echo $this->translate("Get one free");?>
<?php echo $this->translate("Download");?>
<?php echo $this->translate("More Details");?>
<?php echo $this->translate("Login");?>
<?php echo $this->translate("Required infromation");?>
<?php echo $this->translate("User name");?>
<?php echo $this->translate("Password");?>
<?php echo $this->translate("Forgot your password");?>
<?php echo $this->translate("Please enter First Name");?>
<?php echo $this->translate("Top Downloads");?>
<?php echo $this->translate("Top Free");?>
<?php echo $this->translate("Featured Apps");?>
<?php echo $this->translate("Top Premium");?>
<?php echo $this->translate("Top Paid");?>
<?php echo $this->translate("Your Device");?>
<?php echo $this->translate("Sign Up");?>
<?php echo $this->translate("Next");?>
<?php echo $this->translate("Previous");?>
<?php echo $this->translate("Most viewed collection");?>
<?php echo $this->translate("Contact Us");?>
<?php echo $this->translate("Email");?>
<?php echo $this->translate("Message");?>
<?php echo $this->translate("SEND");?>
<?php echo $this->translate("RESET");?>
<?php echo $this->translate("NO DEVICE SELECTED");?>
<?php echo $this->translate("Feedback");?>
<?php echo $this->translate("SUPPORTED FORMATS");?>
<?php echo $this->translate("ADD YOUR OWN REVIEW");?>
<?php echo $this->translate("App");?>
<?php echo $this->translate("Category");?>
<?php echo $this->translate("Newest Apps");?>
<?php echo $this->translate("Free Apps");?>
<?php echo $this->translate("Premium Apps");?>
<?php echo $this->translate("Top Downloaded Apps");?>
<?php echo $this->translate("Most Viewed Apps");?>
<?php echo $this->translate("BOOKS & REFERENCE");?>
<?php echo $this->translate("eBooks");?>
<?php echo $this->translate("Audio books");?>
<?php echo $this->translate("Reference/Dictionaries");?>
<?php echo $this->translate("Religion");?>
<?php echo $this->translate("Comics/Manga");?>
<?php echo $this->translate("GAMES");?>
<?php echo $this->translate("Arcade");?>
<?php echo $this->translate("Cards");?>
<?php echo $this->translate("Action/Strategy");?>
<?php echo $this->translate("Role Playing/Multiplayer");?>
<?php echo $this->translate("Logic/Puzzle/Trivia");?>
<?php echo $this->translate("Casino/Cards/Betting");?>
<?php echo $this->translate("Sports");?>
<?php echo $this->translate("TOOLS & PRODUCTIVITY");?>
<?php echo $this->translate("Utilities/Synchronization");?>
<?php echo $this->translate("Organizers/Clocks/Desktop");?>
<?php echo $this->translate("Internet/WAP");?>
<?php echo $this->translate("Device Tools");?>
<?php echo $this->translate("Security/Backup");?>
<?php echo $this->translate("Developers/DB");?>
<?php echo $this->translate("Office Productivity");?>
<?php echo $this->translate("Graphic Tools");?>
<?php echo $this->translate("BUSINESS & FINANCE");?>
<?php echo $this->translate("Accounts/Tax");?>
<?php echo $this->translate("Stocks/Finance");?>
<?php echo $this->translate("Inventory/Sales");?>
<?php echo $this->translate("Currency/Convertors");?>
<?php echo $this->translate("TRAVEL & GPS");?>
<?php echo $this->translate("GPS/Maps");?>
<?php echo $this->translate("Weather");?>
<?php echo $this->translate("Search");?>
<?php echo $this->translate("Translation/Language");?>
<?php echo $this->translate("NEWS & SPORTS");?>
<?php echo $this->translate("News/Magazines");?>
<?php echo $this->translate("Sports/Teams");?>
<?php echo $this->translate("RSS");?>
<?php echo $this->translate("SOCIAL NETWORKS & MESSAGING");?>
<?php echo $this->translate("IM/SMS/Email/VOIP");?>
<?php echo $this->translate("Social Networks");?>
<?php echo $this->translate("Dating");?>
<?php echo $this->translate("Blogs/Images");?>
<?php echo $this->translate("MUSIC & AUDIO");?>
<?php echo $this->translate("Podcasts");?>
<?php echo $this->translate("MP3/Music");?>
<?php echo $this->translate("Radios/Players");?>
<?php echo $this->translate("Lyrics/Bands");?>
<?php echo $this->translate("VIDEO & TV");?>
<?php echo $this->translate("TV/Shows");?>
<?php echo $this->translate("Movies/Trailers");?>
<?php echo $this->translate("players/Converters");?>
<?php echo $this->translate("LIFESTYLE & WELLNESS");?>
<?php echo $this->translate("Astro");?>
<?php echo $this->translate("Food/Recipes");?>
<?php echo $this->translate("Art/Fashion");?>
<?php echo $this->translate("Hobbies/Pets");?>
<?php echo $this->translate("Health/Diet/Fitness");?>
<?php echo $this->translate("Shopping/Brands");?>
<?php echo $this->translate("EDUCATION & ELEARNING");?>
<?php echo $this->translate("Medical");?>
<?php echo $this->translate("Language");?>
<?php echo $this->translate("Kids/Early learning");?>
<?php echo $this->translate("University");?>
<?php echo $this->translate("Law");?>
<?php echo $this->translate("GOODIES & ENTERTAINMENT");?>
<?php echo $this->translate("Wallpaper/Screensavers");?>
<?php echo $this->translate("Personlization/Skins");?>
<?php echo $this->translate("Humor/Jokes");?>
<?php echo $this->translate("Ringtones");?>
<?php echo $this->translate("THEMES");?>
<?php echo $this->translate("Techno");?>
<?php echo $this->translate("Rock");?>
<?php echo $this->translate("Calm");?>
<?php echo $this->translate("Arts & Crafts");?>
<?php echo $this->translate("Animation");?>
<?php echo $this->translate("Category  Not Found");?>
<?php echo $this->translate("You are not signed in yet");?>
<?php echo $this->translate("No Match Found");?>
<?php echo $this->translate("Ok");?>
<?php echo $this->translate("You haven't log in yet ? Please log in.");?>
<?php echo $this->translate("Apps");?>
<?php echo $this->translate("No Data Found");?>
<?php echo $this->translate("Downloading");?>
<?php echo $this->translate("You are here");?>
<?php echo $this->translate("Have an Issue?");?>
<?php echo $this->translate("Login to add a ticket");?>
<?php echo $this->translate("Please add a valid email");?>
<?php echo $this->translate("Please add a valid password");?>
<?php echo $this->translate("Click here to reset it");?>
<?php echo $this->translate(" HOME");?>
<?php echo $this->translate(" HOME ");?>
<?php echo $this->translate("HOME");?>
<?php echo $this->translate(".Products, Logos and Companies mentioned herein are trademarks or trade names of their respective owners and therefore copyrighted");?>
<?php echo $this->translate("Add your own review");?>
<?php echo $this->translate("MTN Iran App Store");?>
<?php echo $this->translate(" APP ");?>
<?php echo $this->translate("Required Information");?>
<?php echo $this->translate(" FEEDBACK ");?>
<?php echo $this->translate(" INFO ");?>
<?php echo $this->translate(" LOGIN HERE ");?>
<?php echo $this->translate("Login here");?>
<?php echo $this->translate(" APP");?>
<?php echo $this->translate("APP");?>
<?php echo $this->translate("FEEDBACK");?>
<?php echo $this->translate("INFO");?>
<?php echo $this->translate("Feedback");?>
<?php echo $this->translate("To download this app you need to visit the following URL");?>
<?php echo $this->translate("MTN Iran App Store All Rights Reserved.");?>
<?php echo $this->translate("See all results for");?>
<?php echo $this->translate("COPYRIGHT_TXT");?>
<?php echo $this->translate("Mobile Number or password is incorrect");?>
<?php echo $this->translate("Mobile");?>
<?php echo $this->translate("No results found");?>
<?php echo $this->translate("Books & Reference");?>
<?php echo $this->translate("Games");?>
<?php echo $this->translate("Tools & Productivity");?>
<?php echo $this->translate("Business & Finance ");?>
<?php echo $this->translate("Travel & GPS");?>
<?php echo $this->translate("News & Sports");?>
<?php echo $this->translate("Social Networks & Messaging");?>
<?php echo $this->translate("Music & Audio");?>
<?php echo $this->translate("Video & TV");?>
<?php echo $this->translate("Lifestyle & Wellness");?>
<?php echo $this->translate("Education & eLearning");?>
<?php echo $this->translate("Goodies & Entertainment");?>
<?php echo $this->translate("Themes");?>
<?php echo $this->translate("Search Results for");?>
<?php echo $this->translate("Enter the email address you signed up with and we'll email you a link to reset your password");?>
<?php echo $this->translate("Reset your password");?>
<?php echo $this->translate("Required infromation");?>
<?php echo $this->translate("Enter Captcha");?>
<?php echo $this->translate("Powered by");?>
<?php echo $this->translate("The security key wasn't entered correctly");?>
<?php echo $this->translate("Please try again");?>
<?php echo $this->translate("Reset");?>
<?php echo $this->translate("Info");?>
<?php echo $this->translate("The email you supplied was not found");?>
<?php echo $this->translate("Username or password is incorrect");?>
<?php echo $this->translate("Add a Ticket");?>
<?php echo $this->translate("Add a ticket");?>
<?php echo $this->translate("View my Ticket");?>
<?php echo $this->translate("View my ticket");?>
<?php echo $this->translate("Subject");?>
<?php echo $this->translate("Type");?>
<?php echo $this->translate("Priority");?>
<?php echo $this->translate("Select Type");?>
<?php echo $this->translate("Question");?>
<?php echo $this->translate("Incident");?>
<?php echo $this->translate("Problem");?>
<?php echo $this->translate("Feature");?>
<?php echo $this->translate("Select Priority");?>
<?php echo $this->translate("Low");?>
<?php echo $this->translate("Medium");?>
<?php echo $this->translate("High");?>
<?php echo $this->translate("Urgent");?>
<?php echo $this->translate("Your ticket submitted successfully");?>
<?php echo $this->translate("Your response submitted successfully");?>
<?php echo $this->translate("Responses");?>
<?php echo $this->translate("No Response found");?>
<?php echo $this->translate("Reply");?>
<?php echo $this->translate("Submit");?>
<?php echo $this->translate("Platforms");?>
<?php echo $this->translate("PLEASE SELECT YOUR PLATFORM");?>
<?php echo $this->translate("Register on");?>
<?php echo $this->translate("PLEASE SELECT");?>
<?php echo $this->translate("Android App");?>
<?php echo $this->translate("Mobile Web");?>
<?php echo $this->translate("app");?>
<?php echo $this->translate("info");?>
<?php echo $this->translate("feedback");?>
<?php echo $this->translate("Dashboard");?>
<?php echo $this->translate("Open");?>
<?php echo $this->translate("View my Tickets");?>
<?php echo $this->translate("ticket");?>
<?php echo $this->translate("Please add a subject");?>
<?php echo $this->translate("Please select a type");?>
<?php echo $this->translate("Please select a priority");?>
<?php echo $this->translate("dashboard");?>
<?php echo $this->translate("TICKET_SYS");?>
<?php echo $this->translate("FEEDBACK_SYS");?>
<?php echo $this->translate("FEATURED_APPS");?>
<?php echo $this->translate("MOSTVIEWED_APPS");?>
<?php echo $this->translate("NEWEST_APPS");?>
<?php echo $this->translate("Please add your Commenst with more than 10 letters");?>
<?php echo $this->translate("Page not found. (404 - Not Found)");?>
<?php echo $this->translate("No apps found under this category");?>
<?php echo $this->translate("For any customer service issues, bugs in the app downloaded, difficulty downloading or purchases made by mistake please add a ticket. We will get back to you within 48 hours.");?>
<?php echo $this->translate("Please enter your Mobile Number and password");?>
<?php echo $this->translate("This app is only available in the following languages ");?>
<?php echo $this->translate("This app-store will be supported for <<MTN Iran>> subscribers only ");?>
<?php echo $this->translate("The MTN Iran App Store has a rich selection of the best iranian and global apps just for you. Each app is tested for quality, malware and scams. For convenience, Paid apps can be purchased using your phone credit.");?>
<?php echo $this->translate("Selected Device");?>
<?php echo $this->translate("NEXLINKER_TXT_1");?>
<?php echo $this->translate("NEXLINKER_TXT_2");?>
<?php echo $this->translate("NEXLINKER_TXT_3");?>
<?php echo $this->translate("Type in your email address and we will email it to you");?>
<?php echo $this->translate("Scan the QR code using your phone to be directly taken to the app page");?>
<?php echo $this->translate("To download this app you need to visit the following URL ");?>
<?php echo $this->translate("Please enter valid e-mail");?>
<?php echo $this->translate("Please fill the name");?>
<?php echo $this->translate("Please add your comments with more than 10 letters");?>
<?php echo $this->translate("User ID is blocked");?>
<?php echo $this->translate("User ID not found");?>
<?php echo $this->translate("User ID is blocked");?>
<?php echo $this->translate("Authentication failed");?>
<?php echo $this->translate("Failed to get MSISDN Status");?>
<?php echo $this->translate("Invalid MSISDN or password");?>
<?php echo $this->translate("SEARCH_KEYWORD");?>
<?php echo $this->translate("There are no apps matching your query");?>
<?php echo $this->translate("Add Review");?>
<?php echo $this->translate("FORGOT_PASSWORD_TXT");?>
<?php echo $this->translate("My Ticket");?>
<?php echo $this->translate("View Ticket");?>
<?php echo $this->translate("Thank you! Your feedback has bent sent to the admin.");?>
<?php echo $this->translate("App Store");?>
<?php echo $this->translate("Please enter a prepaid MSISDN");?>
<?php echo $this->translate("APP_STORE_DESC");?>
<?php echo $this->translate("Please select your platform");?>
<?php echo $this->translate("Click or Touch here to Download this Application");?>
<?php echo $this->translate("You requested information on how to download the");?>
<?php echo $this->translate("application");?>
<?php echo $this->translate("Download options for");?>
<?php echo $this->translate("Hello");?>
<?php echo $this->translate("Popular applications");?>