<div id="main_right_pane">
    <div class="inr_tabs_wrapper">
        <div class="inr_tab_bar"><?php if(!mtnIran): ?><span class="inr_brdcrtxt_pur">+</span> <?php endif; ?>
            <span class="inr_brdcrtxt_grey"><?php echo $this->translate("View my ticket"); ?></span>
            <!--span class="dashboard-username">Welcome, <?= $this->UserMeta($this->userId,'FIRST_NAME'); ?> | <a href="/info/logout"><?php echo $this->translate("Logout");?></a></span-->
        </div>
        </br>
            <div class="inrtab_selection_top inner_content" >
                
<!-- Displays Success Message/s -->
<?php if (count($this->successMessages)) : ?>

    <div class="notification success png_bg">
        <div>

            <?php foreach ($this->successMessages as $message) : ?>

                <?php echo $this->escape($message); ?>

            <?php endforeach; ?>

        </div>
    </div>

<?php endif; ?>


<!-- Displays Error Message/s -->
<?php if (count($this->errorMessages)) : ?>

    <div class="notification error png_bg">
        <div>

            <?php foreach ($this->errorMessages as $message) : ?>

                <?php echo $this->escape($message); ?>

            <?php endforeach; ?>

        </div>
    </div>

<?php endif; ?>

                <?=$this->paginationControl($this->paginator, 'Sliding', 'partials/ticket_pagination.phtml', array('baseUrl' => $this->baseUrl)); ?>
                <div id="form_wrapper">
                    <?php
                    foreach ($this->paginator as $ticket):
                        ?>
                        <div class="ticket-row curve">
                            <div class="span2">
                                <span class="ticket-date">    
                               <?= date("M jS Y", strtotime($ticket->created_date)); ?></span>
                                <span class="ticket-days-ago">         
                                <?php 
                                    echo $this->DateTimeDiff($ticket->created_date);
                                ?>                                    
                                </span>
                                </br>
                                <span class="ticket-id curve">#<?= $ticket->id; ?></span></br>
                                 
                                <span class="ticket-response-count"><?= $ticket->response_count; ?></span></br><span class="grey"><?= $this->translate('Responses')?></span>
                            </div>
                            <div class="span8">
                                <div class="ticket-title"><?= $ticket->subject; ?></div>
                                <div class="ticket-description curve"><?= (str_word_count($ticket->description) > 60) ? $this->LimitWords(strip_tags($ticket->description,'<strong><u><p>'),60).' ...' : strip_tags($ticket->description,'<strong><u><p>'); ?></div>
                                <div class="misc">
                                    <div class="misc-left">
                                        <span class="attachment"><a href="<?= $this->attachmentPath.$ticket->attachment_name;?>" target="_blank"><?= $ticket->attachment_name; ?></a></span>
                                        </br>
                                        <span class="status stat-<?= strtolower($ticket->status); ?>"><?= $this->translate($ticket->status); ?></span>
                                        <span class="type <?= strtolower($ticket->type); ?>"><?= $this->translate($ticket->type); ?></span>  
                                        <span class="priority <?= strtolower($ticket->priority); ?>"><?= $this->translate($ticket->priority); ?></span>
                                   
                                    </div>
                                    <div class="misc-right">
                                        <a class="ticket-more" href="<?php echo PROJECT_BASEPATH;?>ticket/view-single-ticket/id/<?= $ticket->id; ?>"><?= $this->translate('Description'); ?></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php
                    endforeach;
                    ?>
                </div>
                
                <?=$this->paginationControl($this->paginator, 'Sliding', 'partials/ticket_pagination.phtml', array('baseUrl' => $this->baseUrl)); ?>
                
            </div>
      
    </div>
    <!-- box one-->
    <div style="clear: both;"></div>

</div>

