<!-- Start Content Box #1 -->

<div class="title">

    <h3>Countries</h3>


</div>
<div class="box">
    <div class="txt">
<?=$this->render('partials/message.phtml'); ?>
        <div id="content_box">
            <div class="tab-login">

                <table cellpadding="0" cellspacing="0">
                    <thead>
                        <tr>

                            <th >Name</th>
                            <th>Printable Name</th>

                            <th>ISO</th>
                            <th>Code</th>
                            <th>Currency</th>
                            <th style="width:5%">Opperation</th>
                        </tr>
                    </thead>
                    <tbody>

                        <? foreach($this->countries as $country): ?>
                            <tr>
                                <td><?=$country['name']; ?></td>
                                <td><?=$country['printable_name']; ?></td>
                                <td><?=$country['iso'];?></td>
                                <td><?=$country['numcode'];?></td>
                                <td><?=(isset($this->currencies[$country['currency_id']])) ? $this->currencies[$country['currency_id']] : 'N/A' ;?></td>
                                
                                <td>
                                    
                                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>country/edit/id/<?=$country['id']; ?>" ><img alt="Edit" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/edit.png" title="Edit"></a>
                                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>country/delete/id/<?=$country['id']; ?>" ><img src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/delete.png" alt="Delete"  title="Delete" onClick="return confirm('Are you sure?')"></a>

                                </td>
                            </tr>
                        <?endforeach; ?>
                    </tbody>
                </table>
                 <?= $this->paginationControl($this->countries,'Sliding','partials/paginator.phtml',array("page_name" => 'page')); ?>
            </div>

        </div>

    </div>
</div>
<!-- End Content Box #1 -->


