<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 5/27/13
 * Time: 10:39 AM
 * To change this template use File | Settings | File Templates.
 */
?>
<?php /*echo 'fgsgheiug',$this->baseUrl;*/?>
<div class="blkCenter innerPage containerGap">
    <!-- product list page start -->
    <div class="prodListPage">
        <div class="container">
            <div class="contContent">
                <div class="blockContent">
                    <div class="blkHead">
                        <h2 id="pageTitle">Newest Collection</h2>
                        <ul id="breadcrumbs">
                            <li><a href="/">Home</a></li>
                            <li><a href="<?php echo PROJECT_BASEPATH;?>items/newest/">Newest</a><?php echo $this->translate("menu") ;?></li>
                        </ul>
                        <div style='text-align: center'>
                            <?php echo $this->paginationControl($this->products, 'Sliding', 'partials/items_pagination.phtml'); ?>
                        </div>
                    </div>
                    <ul id="selectTabs">

                    </ul>
                    <?php /*echo $this->render('items/products.phtml'); */?>
                    <?php echo $this->render('partials/product_block.phtml'); ?>
                </div>
                <div style='text-align: center'>
                    <?php echo $this->paginationControl($this->products, 'Sliding', 'partials/items_pagination.phtml'); ?>
                </div>
            </div>
        </div>
    </div>
    <!-- product list page end -->
</div>

<!--, array('baseUrl' => $this->baseUrl)-->