        <div class="title">
                <h3><?php echo $this->translate("All Promotion Codes");?></h3>
        </div>
        <div class="box">
    <div class="txt">
        <table cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th><?php echo $this->translate("ID");?></th>
                    <th><?php echo $this->translate("Product");?></th>
                    <th><?php echo $this->translate("Code");?></th>
                    <th><?php echo $this->translate("Enabled");?></th>
                    <th><?php echo $this->translate("Usage Type");?></th>
                    <th><?php echo $this->translate("Discount");?></th>
                    <th><?php echo $this->translate("From");?></th>
                    <th><?php echo $this->translate("To");?></th>
                    <th># <?php echo $this->translate("used");?></th>
                    <th>&nbsp</th>
                </tr>
            </thead>
        <?php if (count($this->promoCodes)): $class = '';?>
            <tbody>
        <?php foreach ($this->promoCodes as $item): $class = ($class == 'alt') ? '' : 'alt' ; $item = (object) $item; ?>
            <tr>
                <td class='<?=$class?>'><?=$item->id?></td>
                <td class='<?=$class?>'><?= $item->products[0]->name;?></td>
                <td class='<?=$class?>' title="<?=htmlspecialchars($item->description)?>"><?=$item->code?></td>
                <td class='<?=$class?>'><?=($item->enabled) ? 'Yes' : 'No'?></td>
                <td class='<?=$class?>'><?=$item->use_type?></td>
                <td class='<?=$class?>'><?=(int)$item->amount?> <?php echo ($item->discount_type == 'PERCENT') ? "%" : "$"?></td>
                <td class='<?=$class?>'><?=date('d-m-Y', strtotime($item->valid_from))?></td>
                <td class='<?=$class?>'><?=date('d-m-Y', strtotime($item->valid_to))?></td>
                <td class='<?=$class?>'><?=(int)$item->current_use?></td>
                <td class='<?=$class?>'>
                    <a href='/promotion-code/share/code/<?php echo $item->code ?>'>Share</a>
                    <a href='/promotion-code/delete/id/<?php echo $item->id ?>' class='del_conf'>Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
            </tbody>
        <?php endif; ?>
        </table>
    </div>