<script type="text/javascript">

    function getCategoriesTranslations(languageId){
        $.ajax({
            type: "POST",
            url: "categories-translations-list",
            data: "languageId="+languageId,
            success: function(result){
                $("#results").html(result);
            },
            error: function(){
                //console.log('error');
            },
            complete: function(){
                //console.log('complete');
            }
        });
    }
    
    function submitForm()
    {
        $('#languages').submit();
    }

</script>
<div class="title">
    <h3 style="cursor: s-resize;">Translations - Categories <?php //echo $this->user[0]->username;?> | neXva.com</h3>
</div>
<div class="box">
    <div class="txt">
        <?php if(count($this->messages) > 0 ){?>
            <div class="message info">
                <p><?php foreach($this->messages as $message)
                    {
                        echo $this->escape($message);
                    } ?>
                </p>
            </div>
        <?php } ?>
        <div class="content_box">
            <form id="languages" name="languages" onchange="submitForm()" class="" method="post" accept-charset="UTF-8" action="list-languages">
                <p>
                    <label for='title'>Language</label>
                    <select id="language" name="language" class="txt-input small validate(required)">
                        <option value="">Select Language to translate</option>
                        <?php foreach($this->languages as $language)
                        { ?>
                            <option value="<?php if(!empty($language['id'])) {echo $language['id'];}?>" <?php if((!empty($this->languageUser[0])) && ($this->languageUser[0]['language_id'] == $language['id'])) { echo 'selected="selected"';} ?>><?php echo $language['name']?></option>
                        <?php } ?>
                    </select>
                </p>
            </form>
        </div>
    </div>
    <div id="results"></div>
</div>