<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 10/21/13
 * Time: 3:51 PM
 * To change this template use File | Settings | File Templates.
 */
?>
<?php $temp=Zend_Registry::get('browserLocale'); ?>
<?php $t = $this->t();?>
<?php
/**
 * This page needs to be CHAPS (whitelabel) ready.
 *
 * Right now, we're only taking the URL so the URL needs to be specific to the
 * chap and not nexva's
 *
 * @todo Things that need to change according to chaps
 * 1. URLs
 * 2. Colors
 * 3. ?
 */

$chapInfo   = $this->chapInfo;
?>
<?php $this->headLink()->appendStylesheet('/web/css/ui-lightness/jquery-ui-1.8.7.tab-blue.css'); ?>
<?php //$this->headScript()->appendFile('/web/js/jquery-1.4.4.min.js'); //in layout now?>
<?php $this->headScript()->appendFile('/web/nexlinker/script.js');?>
<?php $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/tabs/jquery-ui-1.8.7.tabs.min.js');?>
<?php
// if (isset($chapInfo->WHITELABLE_NEXLINKER_STYLE) && !empty($chapInfo->WHITELABLE_NEXLINKER_STYLE)) {
//     $this->headLink()->appendStylesheet('/mobile/whitelables/' . $chapInfo->WHITELABLE_THEME_NAME . '/' . $chapInfo->WHITELABLE_NEXLINKER_STYLE);
//  }
?>

<?php $this->headScript()->captureStart();?>
$(function() {
$("#tabs").tabs();
$("#tabs-2").show();
});
var __CHAP_ID   = <?=($this->isChap) ? $this->chapId : 0; ?>;
<?php $this->headScript()->captureEnd();?>

<?php
$ns = new Zend_Session_Namespace('translation'); //include this only if the translation utility is enabled
if (isset($ns->translatorEnabled) && $ns->translatorEnabled === true) : ?>
    <link type="text/css" rel="stylesheet" href="<?=$this->cdn('site_assets')?>/web/jquery-ui.nexva.css">
    <link type="text/css" rel="stylesheet" href="<?=$this->cdn('site_assets')?>/web/css/translator.css">
    <script type="text/javascript" src="<?=$this->cdn('jquiryui')?>"></script>
    <script type="text/javascript">
        var __SECTION = '<?php echo $t->getSection()?>';
    </script>
    <script type="text/javascript" src="<?=$this->cdn('site_assets')?>/web/js/translateutil.js"></script>

<?php endif; ?>

<style>
    <!--

    body {
        background: none repeat scroll 0 0 #ffffff;
        font-family: Verdana,Arial,Tahoma;
        font-size: 12px;
        line-height: 1;
        text-align: center;
    }

    #nl_window_close {
        float:right;
        margin : 3px 8px 0 0;
    }

    img {
        border: 1px solid #6879aa;
    }


    #email_field {width: 95%;}

    -->
</style>
<div id='nex-container'>
    dg;swglejr
</div>