<?php 
    $this->headLink()->appendStylesheet( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/css/jquery.ketchup.css');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.js');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.messages.js');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.validations.basic.js');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'admin/assets/js/admin.js');
    
    $this->headLink()->appendStylesheet( PROJECT_BASEPATH.'common/js/jquery/plugins/markitup/skins/markitup/style.css');
    $this->headLink()->appendStylesheet( PROJECT_BASEPATH.'common/js/jquery/plugins/markitup/sets/wiki/style.css');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/markitup/jquery.markitup.js');
    $this->headScript()->appendFile( PROJECT_BASEPATH.'common/js/jquery/plugins/markitup/sets/wiki/set.js');
?>

<script type='text/javascript'>
$(document).ready(function(){
	$('#body').markItUp(mySettings);
});
</script>

<!-- Start Content Box #1 -->
<?php if(isset($this->errors)) : ?>
    <div class="message error">
        <?php foreach ($this->errors as $key=>$value): ?>
            <p><?=$value?></p>
        <?endforeach;?>
    </div>
<?endif;?>
<?php $review   = $this->review?>

    <div class="title">
        <h3>Save Review for <?=$this->product['name']?></h3>
    </div>
    <div class="box">
        <div class="txt">
    
            <div id="content_box">
                <form class='form_validate' method="post" action="/review/save/pid/<?=$this->product['id']?>">
                    <fieldset>
                        <p><label for='title'>Title (*)</label>
                            <input type="text" id="title" name="title" class="txt-input large validate(required, rangelength(1,100))" value="<?=$review->title?>"/>
                        </p>
                        
                        <p><label for='title'>Review (*) - This field is wikimarkup enabled. 
                            <a href='http://trac.nexva.com/wiki/WikiFormatting'>Please read this document for help</a>  </label>
                            <textarea rows='10' id="body" name="body" class="txt-input large validate(required)" ><?=$review->review?></textarea>
                        </p>
                        
                        <p>
                            <label for='rating'>Rating</label>
                            <select class="select-input small" name="rating" id="rating"  >
                                <?foreach(range(0, 5) as $rate): ?>
                                <option value="<?=$rate;?>" <?=($rate == $review->rating) ? 'selected="selected"' : ''?>><?=$rate;?></option>
                                <?endforeach;?>
                            </select>
                        </p>
                        
                        <p>
                            <label for='status'>Status</label>
                            <select class="select-input small" name="status" id="status"  >
                                <option <?=($review->status == 'NOT_APPROVED') ? 'selected="selected"' : ''?> value='NOT_APPROVED'>Not Approved</option>
                                <option <?=($review->status == 'APPROVED') ? 'selected="selected"' : ''?>  value='APPROVED'>Approved</option>
                            </select>
                        </p>
                        
                        <input type='hidden' value='<?=$review->id?>' name='review_id'>
                        <p style="float:left;">
                            <input type="submit" class="button" name="submit" value="Save" />
                            <input type="button" class="button" name="button" value="Cancel" onClick="location.href='/review/list'"/>
                        </p>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
