<?php
class Cpbo_DynamicRegistrationController extends Nexva_Controller_Action_Cp_MasterController {
    
    function testAction() { 
        $productModel   = new Model_Product();
        $query          = $productModel->select(false)->setIntegrityCheck(false);
        $query->from('products', array('id', 'name'))
            ->joinLeft('product_keys', 'products.id = product_keys.product_id', array('key'))
            ->where('registration_model = ?', 'DYNAMIC')
            ->where('user_id = ?', $this->_getCp()->id);  
        $products   = $query->query()->fetchAll();
        $this->view->products   = $products;
        
        $callback   = $this->_getParam('callback', '');;
        $imei       = $this->_getParam('product', '');
        
        if ($this->_request->isPost()) {
            
            $proId      = $this->_getParam('product', false);
            $product    = $productModel->getProductDetailsById($proId, true);
            
             
            if (!$product || empty($callback)) {
                $this->view->message    = "Nothing to test. Please fill all fields";          
                return;      
            }
            
            $userMeta   = new Model_UserMeta();
            $userMeta->setEntityId($this->_getCp()->id);
            
            /**
                id : The id of the app (this would be specific to neXva)
                email : The email address of the user who purchased the item
                app_name: The name of the app
                transaction_id: The transaction id generated by the payment gateway that processed the payment.
                IMEI: The IMEI of the device (will be the same as PIN if the device is Blackberry)
                PIN: The Blackberry PIN (will be the same as IMEI if the device is a not a Blackberry)
                nonce : A random 32 digit hexadecimal numbers
                secret : A MD5 hash of your unique neXva account secret concatenated with a nonce (described above).
                test : 1 or 0
             */
            $hash       = md5(time() . rand(1, 9520));
            $payload    = array(
                'id'        => $proId,
                'email'     => 'testuser@nexva.com',
                'app_name'  => $product['name'],
                'transaction_id'    => 'THIS_IS_A_TEST_ID_1234',
                'IMEI'      => $imei,
                'PIN'       => $imei,
                'nonce'     => $hash,
                'secret'    => md5($userMeta->ACCOUNT_ID . $hash),
                'test'      => 1
            );
            
            $post   = '';
            foreach ($payload as $key => $value) {
                $post   .= $key . '=' . urlencode($value) . '&';
            }
            
            $server  = $callback; // URL to server.php 
            $options = array ( 
                CURLOPT_URL            => $server, 
                CURLOPT_POST           => true, 
                CURLOPT_POSTFIELDS     => $post, 
                CURLOPT_RETURNTRANSFER => true ,
            ); 
            
            $curl           = curl_init(); 
            curl_setopt_array($curl, $options); 
            $response       = curl_exec($curl);
            $httpStatus     = curl_getinfo($curl, CURLINFO_HTTP_CODE); 
            curl_close($curl); 
            
            
            $this->view->request    = print_r($payload, true);
            $this->view->response   = $response;
            $this->view->status     = $httpStatus;
        }

        $this->view->callback   = $callback;
        $this->view->imei       = $imei;
    }
}