   <table width="580" border="0" cellspacing="20" cellpadding="0">

                     <tr>
                        <td width="580" align="left" valign="top" class="mainbar">

                           <h2>Un nouveau développeur s'est inscrit</h2>
                           <p>
                               <br/><br/> Bonjour les admins <br /> <br/><br/>

                               Cet email pour vous informer qu'un nouveau développeur s'est inscrit sur neXva <br/><br/>

                               Identifiant développeur: <?=$this->id?> <br/>
                               E-mail développeur: <?=$this->email?> <br/>

                               <br/><br/>

                               <?
                                $config  = Zend_Registry::get('config');
                               ?>
                               Pour voir plus de détails à propos de ce développeur, cliquez sur: 
                                http://<?=$config->nexva->application->admin->url?>/user/edit/id/<?=$this->id?>

                                <br/><br/>
                             
                               Merci <br/><br/>

                              neXva Mailer Agent.
                           </p>


                        </td>
                     </tr>
   </table>
