<table cellspacing="0" cellpadding="0" border="0" align="center">
  <tbody><tr>
      <td valign="top" align="left">
        <table cellspacing="0" cellpadding="0" border="0">
          <tbody>
            <tr>
              <td valign="top" align="left">
                <table width="500" cellspacing="0" cellpadding="0" border="0">
                  <tbody>
                    <tr>
                      <td colspan="3"><img width="100%" height="1" border="0" src="http://ax.phobos.apple.com.edgesuite.net/email/images_shared/spacer_999999.gif"></td>
                    </tr>
                    <tr height="30">
                      <td width="100" valign="middle" height="30" align="left"><font color="#000000" size="2"><b>#</b></font></td>
                      <td width="235" valign="middle" height="30" align="left"><font color="#000000" size="2"><b>Application</b></font></td>
                      <td width="165" valign="middle" height="30" align="right"><font color="#000000" size="2"><b>New Devices</b></font></td>
                    </tr>
                    <tr>
                      <td colspan="3"><img width="100%" height="1" border="0" src="http://ax.phobos.apple.com.edgesuite.net/email/images_shared/spacer_999999.gif"></td>
                    </tr>
                    <tr height="15">
                      <td height="15" nowrap="" colspan="3"></td>
                    </tr>
                    <?
                    $i = 1;
                    foreach ($this->products as $product):
                    ?>
                      <tr height="20">
                        <td width="100" valign="top" height="20" align="left">
                          <font color="#000000" size="2">
                          <?= $i++ ?>
                        </font>
                      </td>
                      <td width="335" valign="top" height="20" align="left">
                        <font color="#000000" size="2">
                          <?
                          $config = Zend_Registry::get("config");
                          ?>
                          <?= $product['name'] . " <a href='" . $config->nexva->application->cpbo->url . "/build/show/id/" . $product['id'] . "'>[edit]</a>" ?>
                          <br/>
                          <font color="#333333" size="1">
                            <?= substr($product['desc'],0 , 150) . " ..." ?>
                          </font>
                        </font>
                      </td>
                      <td width="65" valign="top" height="20" align="right">
                        <font color="#000000" size="1">
                          <?= implode(',', $this->devices->$product['id']->device->name) ?>
                          </font>
                        </td>
                      </tr>
                    <? endforeach; ?>
                    <tr height="10">
                      <td height="10" nowrap="" colspan="3"></td>
                    </tr>
                    <tr height="15">
                      <td height="15" nowrap="" colspan="3"></td>
                    </tr>
                    <tr height="5">
                      <td height="5" nowrap="" colspan="2"></td>
                    </tr>
                    <tr>
                      <td colspan="3">
                        <img width="100%" height="1" border="0" src="http://ax.phobos.apple.com.edgesuite.net/email/images_shared/spacer_999999.gif">
                      </td>
                    </tr>

                    <tr>
                      <td>
                      </td>
                    </tr>
                    <tr>
                      <td colspan="3" align="center">
                        <br/>
                        <font color="#000000" size="2">
                          We are interested in your feedback on user experience, mobile site and content. Contact us at <a target="_blank" href="mailto:feedback@nexva.com"><span class="il">feedback@nexva.com</span></a><br>
                        </font>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>

            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>