<table width="580" border="0" cellspacing="20" cellpadding="0">

                     <tr>
                        <td width="580" align="left" valign="top" class="mainbar">

                           <h2>"Password Reset Request"</h2>
                           <p>
                               <br/><br/> Hello <?=$this->name?> <br /> <br/><br/>

                               A request to reset your password was recently requested. Please click the link below to verify your account and securely
                               reset password. Please note that this link would only be valid for 1 hour for security reasons <br/><br/>

                               <a href="<?=$this->resetlink ?>"> <?=$this->resetlink ?></a> <br/><br/><br/><br/>

                               If you did not make this request, you can safely ignore this email and no further action is required from you.<br/><br/><br/>

                               Thank you <br/><br/>

                               neXva
                           </p>


                        </td>
                     </tr>
   </table>
