
<table width="580" border="0" cellspacing="20" cellpadding="0">

                     <tr>
                        <td width="580" align="left" valign="top" class="mainbar">

                           <h2>"Demande de réinitialisation de mot de passe"</h2>
                           <p>
                               <br/><br/> Bonjour <?=$this->name?> <br /> <br/><br/>

                               Une demande de changement de mot de passe a été effectuée.  Pour se faire, veuillez cliquer sur le lien ci-dessous.
                               Pour des raisons de sécurité, le lien sera valide 1 heure. <br/><br/>
 

                               <a href="<?=$this->resetlink ?>"> <?=$this->resetlink ?></a> <br/><br/><br/><br/>

                               Si vous n'êtes pas auteur de cette requête, ignorez ce mail en toute sécurité. Plus aucune autre action ne vous sera demandée.<br/><br/><br/>

                               Merci <br/><br/>

                               neXva
                           </p>


                        </td>
                     </tr>
   </table>
