Hello <?= $this->name; ?>,<br/><br />

<div class='content_left'  style='width:980px;'>
    <div class='intro'> 
        <h2 class='green'>neXva Galaxy S8 Developer Giveaway</h2>
        <img  src='http://<?=Zend_Registry::get('config')->nexva->application->base->url ?>/cp/assets/img/image-name1.jpg'/><br></br>
    <b><a href='https://docs.google.com/forms/d/e/1FAIpQLSeKUSZxJJtqXydBSpNo08jxM53dIsdoXrymNytC_ka4f8xWmw/viewform?embedded=true' style="font-size: 15px;" >Register here</a></b>    
        <a href='http://cp.nexva.com/user/login' style="font-size: 15px;" >more info..</a>
        If you don't register you will not be entitled for this.
    </div>
</div>
