<br><br>
<div style="font-size:20px;">Hello <?= $this->name; ?>,</div> <br>
<div style="font-size:17px;text-align: justify; font-family:Andale Mono, monospace !important;">
Congratulations !. The <?=$this->app_name?> has been selected for <strong>Samsung Galaxy S8 Giveaway!</strong> by Nexva Inc. You can get a chance to win  Samsung Galaxy S8  smartphone. Please <a href='https://docs.google.com/forms/d/e/1FAIpQLSeKUSZxJJtqXydBSpNo08jxM53dIsdoXrymNytC_ka4f8xWmw/viewform?embedded=true' style="font-size: 15px;" >register</a> with this to confirm your participation. Please visit our site for <a href='http://cp.nexva.com/user/login' style="font-size: 15px;" >more info..</a> 
</div>