Dear Rooban,

We would like to acknowledge that we have received your request and a ticket has been created with Ticket ID - 2.
A support representative will be reviewing your request and will send you a personal response.(usually within 24 hours).

To view the status of the ticket or add comments, please visit 
http://nexvasl.freshdesk.com/helpdesk/tickets/2

Thank you for your patience.

Sincerely,
neXvasl Support Team
