<?php
    $bgColor    = '#FFAA00';
    $fgColor    = '#FFFFFF';
    $fontColor  = '#FFAA00'; 
?>
<br/><br/>
<p style='font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px;  font-weight: bold;'>
Hello Support Team,
</p>

<p>
    <table border="0" bgcolor="eeeeee">
        <tr>
            <td colspan="5">&nbsp;</td>
        </tr>
        <tr>
            <td width='2%'>&nbsp;</td>
            <td colspan='4'>
                The user has submitted the following comment. Please login to the PBO backend to leave a reply.
                <br/>
            </td>
        </tr>
    </table>
</p>

<p style='font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px;'>
Thank you,<br/>
neXva
</p>