<?php
    $bgColor    = '#FFAA00';
    $fgColor    = '#FFFFFF';
    $fontColor  = '#FFAA00'; 
?>
<br><br>
<p style='font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px;  font-weight: bold;'>
Hello <?=$this->email?>
</p>

<p>
    <table border="0" bgcolor="eeeeee">
        <tr>
            <td colspan="5">&nbsp;</td>
        </tr>
        <tr>
            <td width='2%'>&nbsp;</td>
            <td colspan='4'>
                <p style='font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px;'>
                Nous tenons à souligner que nous avons reçu votre demande et un ticket a été créé avec Ticket <span style='font-family: Verdana, Arial, Helvetica, sans-serif; color: <?=$fontColor?>; text-decoration:none;'><strong>ID - #<?= $this->ticketId; ?></strong></span>.<br/>
                Un représentant de soutien examinera votre demande et vous enverra une réponse personnelle. (Habituellement, dans les 48 heures).
                </p>

                <p style='font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px;'>
                Pour afficher l'état du billet ou ajouter des commentaires, s'il vous plaît visitez l'adresse suivante.<br/><br/>
                <a style='text-align:center;display:block;font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px;background: <?=$bgColor?>;color: <?=$fgColor?>;margin-right: 2px; padding: 10px 6px; text-decoration: none;' href="<?= $this->ticketUrl; ?>" class="button"><strong><?= $this->ticketUrl; ?></strong></a>
                </p>
                <br/>
            </td>
        </tr>
    </table>
</p>

 <p style='font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px;'>Thank you for your patience.</p>
 <p style='font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px;'>
sincèrement,<br/>
<?= utf8_decode($this->siteName); ?> Support Team.
</p>