   <table width="580" border="0" cellspacing="20" cellpadding="0">

                     <tr>
                        <td width="580" align="left" valign="top" class="mainbar">

                           <h2>Bienvenue sur neXva</h2>
                           <p>
                               <br/><br/> Salut <?=$this->name; ?>, <br /> <br/>

                               Votre compte a été vérifié, il est maintenant disponible 
                               Pour télécharger des contenus, <a href="http://<?=$this->cpboUrl; ?>/product/create">Cliquez ici.</a>

                               <br/><br />
                               Si vous n'avez pas créé ce compte, écrivez-nous à abuse@nexva.com

                               <br/><br/>


                              Merci <br/><br/>

                              Team neXva
                           </p>


                        </td>
                     </tr>
   </table>