   <table width="580" border="0" cellspacing="20" cellpadding="0">

                     <tr>
                        <td width="580" align="left" valign="top" class="mainbar">

                           <h2>Welcome to neXva</h2>
                           <p>
                               <br/><br/> Hi <?=$this->name; ?>, <br /> <br/>

                               Your account is now verified and is ready to be used.
                               To get started uploading content, <a href="http://<?=$this->cpboUrl; ?>/product/create">Click here.</a>

                               <br/><br />
                               If you were not the one who created this account, please write to us at abuse@nexva.com.

                               <br/><br/>


                              Thank you <br/><br/>

                              Team neXva
                           </p>


                        </td>
                     </tr>
   </table>