   <table width="580" border="0" cellspacing="20" cellpadding="0">

                     <tr>
                        <td width="580" align="left" valign="top" class="mainbar">

                           <h2>Welcome to neXva</h2>
                           <p>
                               <br/><br/> Hi <?=$this->name; ?> <br /> <br/>

                               Your neXva account is now activated and is ready to be used.
                               <br/><br />
                               Your username is <?=$this->email?>

                               <br/><br />
                               If you were not the one who created this account, please write to us at abuse@nexva.com.

                               <br/><br/>
                                                           

                              Thank you <br/><br/>

                              Team neXva
                           </p>


                        </td>
                     </tr>
   </table>






