   <table width="580" border="0" cellspacing="20" cellpadding="0">

                     <tr>
                        <td width="580" align="left" valign="top" class="mainbar">

                           <h2>Claim your account at neXva.com </h2>
                                              <p>
                               <br/><br/> Hello <?=$this->name?> <br /> <br/><br/>
                
                              With regard to your purchase that was made at neXva.com, we have created an account for you. You might want to claim the account now by clicking the link below.
                              
                              <br/><br/>

                               <a href="<?=$this->resetlink ?>"> <?=$this->resetlink ?></a> <br/><br/><br/>
                               
                               You can continue to purchase from neXva using <?=$this->email?> in future if you don't want to claim it right away - we'll remind you how to claim it when you do.
                               <br/><br/>
                               We hope to see you soon!<br/><br/>

                               Team neXva <br/><br/>

                              </p>


                        </td>
                     </tr>
   </table>
