   <table width="580" border="0" cellspacing="20" cellpadding="0">

                     <tr>
                        <td width="580" align="left" valign="top" class="mainbar">

                            <h2>Complete your account registration at cp.neXva.com</h2>
                                              <p>
                               <br/><br/> Hello <?=$this->name?> <br /> <br/><br/>
                
                              We recently recieved a new registration request from this account. To complete your registration request, please click the link below:
                              
                              <br/><br/>

                               <a href="<?=$this->resetlink ?>"> <?=$this->resetlink ?></a> <br/><br/>
                                                                                           

                               We hope to see you soon!<br/><br/>

                               Team neXva <br/><br/>

                              </p>


                        </td>
                     </tr>
   </table>
