   <table width="580" border="0" cellspacing="20" cellpadding="0">

                     <tr>
                        <td width="580" align="left" valign="top" class="mainbar">

                           <h2>Complétez votre inscription en compte au cp.neXva.com</h2>
                                              <p>
                               <br/><br/> Bonjour <?=$this->name?> <br /> <br/><br/>
                
                             Nous avons récemment avons reçu une nouvelle demande d'enregistrement de ce compte. Pour compléter votre demande d'inscription, s'il vous plaît 
                             cliquez sur le lien ci-dessous:
                              
                              <br/><br/>

                               <a href="<?=$this->resetlink ?>"> <?=$this->resetlink ?></a> <br/><br/>
                                                                                           

                               Nous espérons vous voir bientôt!!<br/><br/>

                               Team neXva <br/><br/>

                              </p>


                        </td>
                     </tr>
   </table>
