<!-- Start Content Box #2 -->
<div class="title">

    <a name="activity" id="activity"></a><h3>Content activities</h3>


</div>
<div class="box">
    <div class="txt">

        <div id="content_box">
            <div class="tab-table">



                <!-- Start Table -->
                <table cellpadding="0" cellspacing="0">
                    <thead>
                        <tr> 
                            <th>Content </th>
                            <th>Date</th>
                            <th>Log message</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                      
                        

                        <? foreach($this->logs as $log): ?>
                        
                        <tr>
                            
                            <td><?=$log->name; ?></td>
                            <td><?=$log->date; ?></td>
                            <td><?=$log->log; ?></td>
                            
                            <td><a href="/activities/more/log/<?= $log->product_id; ?>"><img src="/cp/assets/img/global/icons/info.png" alt="Info"/></a></td>
                        </tr>
                        <? endforeach; ?>
                        <tr>
                            <td colspan="6">
                                <?= $this->paginationControl($this->logs, 'Sliding', 'partials/paginator.phtml'); ?>
                            </td>
                        </tr>
                         <?if($this->empty_msg != ''):?>
                        <tr><td colspan="4"><small><i><?= $this->empty_msg; ?></i></small></td></tr>
                         <?endif; ?>
                    </tbody>
                </table>
                <!-- End Table -->

            </div>
        </div>
    </div>
</div>
<!-- End Content Box #2 -->
