<!-- Start Content Box #2 -->
<div class="title">

    <a name="activity" id="activity"></a><h3>Products activity by product</h3>


</div>
<div class="box">
    <div class="txt">

        <div id="content_box">
            <div class="tab-table">



                <!-- Start Table -->
                <table cellpadding="0" cellspacing="0">
                    
                    <thead>
                         <tr><td style="font-size:17px;padding:5px;"><?=$this->log_product; ?> </td></tr>
                        <tr> 
                            
                            <th>Date</th>
                            <th>Log message</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                       
                        <? foreach($this->logs as $log): ?>
                        
                        <tr>
                            
                            
                            <td><?=$log->date; ?></td>
                            <td><?=$log->log; ?></td>
                            
                            <td>&nbsp;</td>
                        </tr>
                        <? endforeach; ?>
                        <tr>
                            <td colspan="6">
                                <?= $this->paginationControl($this->logs, 'Sliding', 'partials/paginator.phtml'); ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <!-- End Table -->

            </div>
        </div>
    </div>
</div>
<!-- End Content Box #2 -->
