        <div class="title">
            <h3>All Campaigns</h3>
        </div>
        <div class="box">
    <div class="txt">
        <table cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>&nbsp</th>
                </tr>
            </thead>
        
            <tbody>
        <?php if (count($this->campaigns)): $class = 'alt';?>    
            <?php foreach ($this->campaigns as $item): $class = ($class == 'alt') ? '' : 'alt' ;?>
                <tr>
                    <td class='<?=$class?>'><?=$item->id?></td>
                    <td class='<?=$class?>'><?=$item->title?></td>
                    <td class='<?=$class?>'><?=$item->description?></td>
                    <td class='<?=$class?>'>
                        <a href='/promo-code/view-by-campaign/id/<?php echo $item->id ?>'>View Promotion Codes</a>
                         | <a target="_blank" href='http://<?=Zend_Registry::get('config')->nexva->application->base->url?>/promotion-code/view-codes-by-campaign/id/<?php echo $item->id ?>'>Print</a>
                         | <a href='/promo-code/csv/id/<?php echo $item->id ?>'>Download CSV</a>
                        &nbsp;&nbsp;&nbsp; 
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
            </tbody>
        
        </table>
    </div>
</div>


