<script type="text/javascript">
//Form Validation
$(document).ready(function() {
	$("#frmAddPage").validate();
});

//Tinymice Editor
$().ready(function() {
        $('textarea.tinymce').tinymce({
            // Location of TinyMCE script
            script_url : '/pbo/js/tiny_mce.js',
            
            // General options
            theme : "advanced",
            plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",
            
            // Theme options
            theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,formatselect,fontsizeselect",
            theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            //theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : true

        });
});
 //End Tinymice Editor      
</script>

<style>    
#main-content table td, #main-content table th {
    line-height: 1.3em;
    padding: 0px;
}
</style>

<?php 
    $product        = (object)$this->product; 
    $translation    = $this->translation;
?>

<div class="content-box"><!-- Start Content Box -->
    <div class="content-box-header">
        <h3 style="cursor: s-resize;"><?= $this->title; ?> - <?= $product->name?></h3>

        <!--div id="icon_wrapper">
            <a href="/page" alt="Manage Pages"> <img style="border: none" src="/pbo/images/icons/manage-pages-small.png" alt="Manage Pages" /><br />
            Add Translations</a>
        </div-->
    </div> <!-- End .content-box-header -->


    <div class="content-box-content">


        <!-- Displays Message/s -->
        <?php if (count($this->pageMessages)) : ?>

        <div class="notification success png_bg">                
                <div>

                    <?php foreach ($this->pageMessages as $message) : ?>

                        <li><?php echo $this->escape($message); ?></li>

                    <?php endforeach; ?>

                </div>
            </div>

        <?php endif; ?>


        <form method="post" action="/app/addtranslation/" id="frmAddPage" name="frmAddPage">
            <!--p>
                <label>App Name <span class="mendatory_fileds"></span></label>
                <?= $product->name?>
            </p-->

            <p>
                <label>Language</label>
                <select id="lang_id" name="langId">
                            <?php foreach ($this->languages as $lang) : ?>
                            <option <?php if($lang->id == $translation->language_id):?>selected='selected'<?php endif;?> value='<?php echo $lang->id?>'>
                                <?=$lang->common_name ?> <?=(!empty($lang->common_name)) ?  ' &mdash; ' . $lang->name : $lang->name?>
                            </option>
                            <?php endforeach;?>
                 </select>                
            </p>

            <p>
                <label>Content Name <span class="mendatory_fileds">*</span></label>
                <input id="small-input" <?= ($this->chapId == 23045) ? 'dir="rtl"' : ''; ?> class="text-input small-input required" type="text" name="name" id="txtTitle" value="<?= $translation->PRODUCT_NAME ?>" />
            </p>
            

            <p>
                <label>Content Summary</label>
                <textarea <?= ($this->chapId == 23045) ? 'dir="rtl"' : ''; ?> rows="8" cols="50" name="summary" style="width:300px;"><?= html_entity_decode($translation->PRODUCT_SUMMARY) ?></textarea>
            </p>

            <p>
                <label>Content Description</label>
                <textarea <?= ($this->chapId == 23045) ? 'dir="rtl"' : ''; ?> rows="15" cols="50" name="desc" style="width:150px;"><?= $translation->PRODUCT_DESCRIPTION ?></textarea>
            </p>
            
            <!--p>
                <label>Status</label>
                <select name="chkStatus" id="chkStatus" class="chkbox">
                    <option value="publish" <?= (isset($this->pageDetails->status) && $this->pageDetails->status == 'publish') ? 'selected= "selected"' : '' ?> >Publish</option>
                    <option value="unpublish" <?= (isset($this->pageDetails->status) && $this->pageDetails->status == 'unpublish') ? 'selected= "selected"' : '' ?> >Un Publish</option>       
                </select>  
            </p-->

            <p>
                
                
                <input id="pageId" name="pageId" class="button" type="hidden" value="<?= isset($this->pageId) ? $this->pageId : '' ?>">
                <input id="appid" name="id" type="hidden" value="<?php echo $this->proid ?>">
                <input id="appid" name="filterVal" type="hidden" value="<?php echo $this->filterVal ?>">
                <input id="appid" name="searchKey" type="hidden" value="<?php echo $this->searchKey ?>">
                <input id="appid" name="platform" type="hidden" value="<?php echo $this->platform ?>">
                <input id="appid" name="txtSearchId" type="hidden" value="<?php echo $this->txtSearchId ?>">
                <input id="appid" name="language" type="hidden" value="<?php echo $this->language ?>">
                <input id="appid" name="category" type="hidden" value="<?php echo $this->category ?>">
                <input id="appid" name="grade" type="hidden" value="<?php echo $this->grade ?>">
                <input id="appid" name="pageNo" type="hidden" value="<?php echo $this->page ?>">
                <input id="appid" name="curLangId" type="hidden" value="<?php echo $this->curLangId ?>">
                
                <input id="btnSubmit" name="btnSubmit" class="button" type="submit" value="Save">
                <!--input id="btnReset" name="btnReset" class="button" type="reset" value="Reset"-->
                <input id="btnSubmit" name="btnSubmit" class="button" type="button" onclick="goBack();" value="Close">
                <input id="btnDelete" name="btnReset" class="button" type="button" onclick="removeTranslation();" value="Remove Translations">
                
            </p>
        </form>
        <br />
    </div>

</div>

<script type="text/javascript">
    
    function goBack(){
        window.location.replace("/app/index/id/<?=$this->proid?>/page/<?=$this->page?>/filterVal/<?=$this->filterVal?>/searchKey/<?=$this->searchKey?>/platform/<?=$this->platform?>/txtSearchId/<?=$this->txtSearchId?>/language/<?=$this->language?>/category/<?=$this->category?>/grade/<?=$this->grade?>");
    }
    
    function removeTranslation(){
        window.location.replace("/app/removetranslation/id/<?=$this->proid?>/langId/<?=$this->curLangId?>");
    }
    
    $('#2').addClass('current');
    $('#21').addClass('current');
</script>