                    <!-- Start Content Box #1 -->
                    <div class="title">

                        <h3>Back Office Admin profile</h3>

                        
                    </div>
                    <div class="box">
                        <div class="txt">

                            <div id="content_box">
                                <div class="tab-login">

                                    

                                    <? if( $this->error != '') //prob would be better to render a view partial here
                                    {
                                    ?>
                                        <div class="message error">
                                            <p><?=$this->error?></p>
                                        </div>

                                    <?
                                    }
                                    ?>

                                    <? if( $this->message != '') //prob would be better to render a view partial here
                                    {
                                    ?>
                                       <div class="message info">
                                            <p><?=$this->message?></p>
                                        </div>

                                    <?
                                    }else if('' ==$this->error){
                                    ?>

                                        <div class="message info">
                                            <p>Changing your profile information is not supported as of yet.
                                              If you wish to change your password, please login to Trac using your existing username and password
                                              and change your password from there.
                                            </p>
                                        </div>
                                    <?
                                    }
                                    ?>


                                </div>
                                
                            </div>

                        </div>
                    </div>
                    <!-- End Content Box #1 -->


