<?=$this->partial('/partials/tabs.phtml', array("item" => 'premium', 'themeMeta' => $this->themeMeta))?>
<hr class="t" />
<br clear="all" />
<?
if(count($this->products) == 0) {
    ?>
<div class="app">
    <span class="mini-description">
        Sorry, we couldn't find any premium apps for this device.
    </span>
</div>
    <?
}
foreach($this->products as $product): ?>
    <?=$this->partial('/partials/app.phtml', array("item" => $product))?>
<?php endforeach; ?>
<?=$this->partial('/partials/paginator_simple.phtml', array("baseUrlfo" => $this->baseUrlfo, 'products' => $this->products, 'pageNum' => $this->pageNum))?>