<?php
    $breadcrumbs    = $this->breadcrumbs;
    $mode       = isset($this->mode) ? $this->mode : 'all';  
    if (isset($this->category['parent_id']) && $this->category['parent_id'] == 0) {
        $url    = "/app/";
    } else {
        $url    = "/app/cat/category/{$this->category['parent_id']}";
    }
?>

    <div class='breadcrumb'>
        <a href='/app'>All Categories</a> 
        <span>&raquo;</span>
        <?php foreach ($breadcrumbs AS $crumb) : ?>
            <a href='/app/cat/category/<?php echo $crumb['id']?>'><?php echo $crumb['name']?></a>
            <span>&raquo;</span>
        <?php endforeach; ?>
        
        <span class='last'><?= $this->product['name'] ?></span>
    </div>
     
    <?php 
        /**
         *|-----------------------------------------|
         *|----------------READ THIS!---------------|
         *|-----------------------------------------|
         * Due to various legacy coding decisions, the whole build/language system is a bit of a mess
         * There's no easy way to even show the buy/download butt. What I want to do is NOT show the 
         * button if the 'Build avaialble in other languages option is available'. So I have a small
         * trigger inside the code to see whether we actually went there.
         * 
         * Change this code at your own peril and put a comment here explaining why/what you did
         * =John (July 2011)
         *|-----------------------------------------|
         *|----------------READ ABOVE!--------------|
         *|-----------------------------------------|
         */
    
    ?> 
    
    <?php 
        $hasOtherLanguageBuilds  = false; 
    ?> 
    <?php if ($this->warningMessage): ?>
        <?php if ($this->buildsInOtherLanguage) : ?>
                <div class="message_notice">
                This app is only available in the following languages <br><br>
                
                <?php foreach ($this->buildDetails as $buildInfo) : ?>
                    <?php $hasOtherLanguageBuilds  = true; ?>
                    <a href='/app/download/id/<?=$this->product['id'];?>/language_id/<?=$buildInfo['language_id'];?>'>
                        <?=($buildInfo['language_common_name'])? $buildInfo['language_common_name'] : $buildInfo['language_name']; ?>
                            <span>&raquo;</span>
                    </a>    
                <?php endforeach; ?>
                
                </div>
        <?php else : ?>
            <!-- here we hard coded the MTN id to hide the error message -->
            <?php if($this->user_id != '21677') {?>
            <div class="warning_message">
                This app is not compatible with your device / OS version <br>
                <?php if($this->buildVersionInfo): ?>
                    <?php foreach ($this->buildVersionInfo AS $buildVersionInfo) : ?>
                        Required OS version: <?=$buildVersionInfo['minOsVersion'];?> <?=($buildVersionInfo['or_better'])? 'or better' : ''; ?>  <br />
                    <?php endforeach; ?>
                    <br />Detected OS version: <?=$this->osVersion; ?>
                <?endif;?>
            </div>
            <?php } ?>
        <?php endif; ?>
    <?endif;?>
    
    

    <div class="padding-all">
        <h1><?= $this->product['name'] ?></h1>
    </div>
    
    <?php if (count($this->messages)) : ?>

    <div class="message_success">
        <p>
           <?php 
                foreach ($this->messageSuccess as $message) : 
                echo $this->escape($message); 
                endforeach; 
         ?>
        
        </p>       
    </div>

    <?php endif; ?>
    
    <div class="description">
        <span class="other">
            <span class="thumb">
            <?= $this->thumbnail($this->product['thumb'], array('w' => 80, 'h' => 80)); ?>
        </span>
    </span>
        <!-- here we hard code & check whether the user is MTN, if so we shows the download button -->
<?php if (($this->user_id== '21677')||(!$this->warningMessage || ($this->warningMessage && $this->buildsInOtherLanguage))) : ?>
    <!-- @TODO: Think a better way to do this -->
    <? if ($this->isUrl == true AND $this->product['cost'] != 0): ?>
            <a class='buy' href="<?= (count($this->product['file']) == 1) ? '/app/download/id/' . $this->product['id'] : '#sources' ?>">
                Buy
            </a>
    <? elseif ($this->isUrl): ?>
            <a class='download' href="<?= (count($this->product['file']) == 1) ? '/app/download/id/' . $this->product['id'] : '#sources' ?>">
                Download
            </a>
    <? elseif ($this->product['cost'] == 0): ?>
            <a class='download' href="<?php echo PROJECT_BASEPATH;?>app/download/id/<?= $this->product['id'] ?>">
                Download
            </a>
    <? elseif ($this->purchased): ?>
            <a class='download' href="<?php echo PROJECT_BASEPATH;?>app/download/id/<?= $this->product['id'] ?>">
                Download
            </a>
    <? elseif (empty(Zend_Auth::getInstance()->getIdentity()->id)): ?>
            <a class='buy' href="/user/login/?next=buy">
                Buy
            </a>
    <? elseif (!empty(Zend_Auth::getInstance()->getIdentity()->id) && !$hasOtherLanguageBuilds): ?>
            <a class='buy' href="<?php echo PROJECT_BASEPATH;?>download/id/<?= $this->product['id'] ?>">
                Buy
            </a>
    <? endif; ?>
<?php endif;?>
                                <br />
                                
                                
    <?= isset($this->product['user_meta']) ? $this->product['user_meta']->COMPANY_NAME : '' ?><? //= $this->trim($this->item['desc'], 200)  ?><br/>
                                <strong><?= ($this->product['cost'] == 0) ? 'FREE' : '$' . $this->product['cost'] ?></strong>
                                <br/>
                    
                                
                                
                                
                                <br clear="all">
                                <div class="space_div"></div>
                                
                                <!--   show  user rating   -->  
                                <div id="show_rating">
                                    
                                    <?php
                                                $starRating = 1;
                                                $numRatings = $this->totalRatings;
                                                $totalStars = 5;
                                                $ratingInt  = floor($this->avgRating);
                                                $ratingPart = $this->avgRating - $ratingInt;
                                                $productId = $this->productId;
                                                $ratedProducts = $this->ratedProducts;
                                                
                                                $productRated = $this->productRated;

                                    ?>
                                       
                                     <? for ($count = 0; $count < $ratingInt; $count++) 
                                        {
                                     ?>                                                                                                                
                                                        
                                                    <img src="<?=$this->Cdn('site_assets')?>/web/images/star_full.gif" alt="star" width="11" height="12" />
                                    <?  } ?>
                                            
                                    <?php 
                                                if ($ratingPart > 0) :
                                                    $totalStars = 4; //we're showing a halfstar already 
                                     ?>
                                              
                                            <img src="<?=$this->Cdn('site_assets')?>/web/images/star_half.gif" alt="star" width="11" height="12" />
                                               
                                     <?php endif; ?>
                                            
                                       <? for ($count = $ratingInt; $count < $totalStars; $count++) 
                                          {
                                       ?>                                                
                                               <img src="<?=$this->Cdn('site_assets')?>/web/images/star_empty.gif" alt="star" width="11" height="12" />
                                                
                                      <?  } ?>
                                    
                                    
                                    (<?php echo $numRatings; echo ($numRatings == 1) ? ' vote' : ' votes' ; ?>)
                                </div>
                                
                                <!--   allow for rate   -->  
                                <?php
                                   
                                   if($productRated === FALSE) 
                                   {
                                ?>          
                                            <div class="space_div"></div>
                                            <h2 id="reviews">Rate App</h2>
                                            <div id="user_rating">

                                                    <form class='smallInputForm' id="register" style='width:auto;' name="register" action="<?php echo PROJECT_BASEPATH;?>rating/rate/" method="post">

                                                            <select name="rating" id="rating" style="width: auto" >
                                                                <option value="1">Uninstalling it now (*)</option>
                                                                <option value="2">Meh, could do better (**)</option>
                                                                <option value="3">Nothing special (***)</option>
                                                                <option value="4">Pretty good (****)</option>
                                                                <option value="5">Awesome! (*****)</option>
                                                            </select>

                                                            <input type="submit" class="button" id="btnRating" name="btnRating" value="Rate Now" />
                                                            <input type="hidden" id="productId" name="productId" value="<?= $this->product['id'] ?>" /> 
                                                    </form>  

                                            </div>
                                 <?php 
                                   
                                   }
                                   else
                                   {
                                   }
                                   ?>

                                <?php
/*                           if($this->product['google_id']){
                                echo $this->AppStoreScore($this->product['google_id']);
                            }

                            if($this->product['apple_id']){
                                echo $this->AppStoreScore($this->product['apple_id']);
                            }

                            */?>

        <?php
        if($this->product['google_id']){
        echo '<div class="app-cracker-rate-wrap"><img title="Android" alt="Android" src="/partner/default/assets/img/platforms/12.png">&nbsp;&nbsp;<div class="app-cracker-rate">'.$this->AppStoreScore($this->product['google_id']).'</div></div>&nbsp;&nbsp;';
        }

        if($this->product['apple_id']){
        echo '<div class="app-cracker-rate-wrap"><img title="Android" alt="Android" src="/partner/default/assets/img/platforms/10.png">&nbsp;&nbsp;<div class="app-cracker-rate">'.$this->AppStoreScore($this->product['apple_id']).'</div></div>';
        }
        ?>
                                
                                
                                <div class="space_div"></div>
                                <div class="space_div"></div>
                             
                                    <?php 
                                        $opts   = array(
                                            'url'   => 'http://' . Zend_Registry::get('config')->nexva->application->base->url . "/{$this->product['id']}",
                                            'title' => $this->product['name'],
                                            'description'   => $this->product['desc_brief'] 
                                        );
                                        echo $this->partial('partials/addthis.phtml', $opts)
                                    ?>
                                
                                <?php 
                                    /**
                                     * Promotion code fragment
                                     */
                                ?> 
                                <?php if ($this->originialPrice  > 0) : ?>
                                <br clear="all"> 
                                
                                 
                                
                                <div class="promotion_input" style="font-size:120%">
                                    <?php if ($this->promocode && !$this->validCode) : ?>
                                        <div class="message_notice">
                                            The promotion code <strong><?=$this->promocode['code']?></strong> is not valid for this app
                                            &mdash; <a href='/app/remove-code/id/<?=$this->product['id']?>'>Remove Code</a>
                                        </div>
                                    <?php elseif (($this->promocode && $this->validCode)) : ?>
                                        <div class="message_success">
                                            Promotion code <strong><?=$this->promocode['code']?></strong> applied
                                            &mdash; <a href='/app/remove-code/id/<?=$this->product['id']?>'>Remove Code</a>
                                        </div>   
                                    <?php else : ?>
                                    <form method="post" action="/app/apply-code/id/<?=$this->product['id']?>">
                                        Got a promotion code? 
                                        <input style="padding: 5px 0;" type="text" name="code">
                                        <button type="submit" class="button" style="padding: 5px 0;">Apply</button>
                                    </form>
                                    <?php endif; ?>
                                </div>
                                <?php endif;?>
                                
                                <br clear="all">      
                               
                                <span class="mini-description">
                                    <?= $this->product['desc'] ?>
                                </span>
                        </div>
                        
                    

                        <div class="visuals">
    <? if ($this->isUrl && (count($this->product['file']) != 1)): ?>
    <?
                                    if (is_array($this->product['file']))
                                        foreach ($this->product['file'] as $url): ?>
    <? if (preg_match('/^(http|https|ftp):\/\/([A-Z0-9][A-Z0-9_-]*(?:\.[A-Z0-9][A-Z0-9_-]*)+):?(\d+)?\/?/i', $url)): ?>
                                                <a href="<?= $url ?>"><img src="<?=$this->cdn('site_assets')?>/mobile/images/link_go.png" /> <?= $url ?></a><br clear="all">
    <? else: ?>
                                                    <a href="<?= $this->S3Url($this->product['id'] . '/' . $url) ?>"><img src="<?=$this->cdn('site_assets')?>/mobile/images/link_go.png" /> <?= $url ?></a><br clear="all">
    <? endif; ?>
    <? endforeach; ?>
    <? else: ?>
    <?
                if (isset($this->product['screenshots']))
                    foreach ($this->product['screenshots'] as $file): ?>
                        <span class="thumb">
                            <?php
                                $imgHtml    = $this->thumbnail($file, array('w' => 100, 'h' => 160, 'far' => 1), array());
                                $linkUrl    = $this->thumbnail($file, array(), array(), $returnUrl = true);
                            ?>
                            <a href='<?=$linkUrl?>'>
                                <?=$imgHtml?>
                            </a>
                        </span>
                    <? endforeach; ?>
                <? endif; ?>
                                </div>
                    
          <!-- reviews -->                            
        <div class='reviews'>
            <h2 id='reviews'>Reviews</h2>
            
            <?php 
                if (isset($this->evaReview[0])) : //it's an array
                    $review = $this->evaReview[0]; 
            ?>
                <div class='review app eva'>
                    <h3><?=$review['title']?></h3>
                    <span class='reviewer'><?=$review['name']?> (<?=date('d-m-Y', strtotime($review['date']))?>)</span>
                    <span class='rating'>
                        <?php
                            $rating     = $review['rating']; 
                            while($rating > 0) : $rating--; 
                        ?>
                            <img src="<?=$this->Cdn('site_assets')?>/mobile/images/star_full.gif" alt="star" width="11" height="12" />
                        <?php endwhile;?>
                    </span>
                    <p>
                        <?php echo substr(strip_tags($this->Wikimarkup($review['review'])), 0, 300) . '...';?>
                    </p>
                    
                    <p class='more'>
                       <a class='button' href="/review/eva/id/<?=$review['id']?>">Continue reading Eva's review</a>
                     </p>
                     
                    <div class='info'>
                        <img width='80' height='80' src='<?=$this->Cdn('site_assets')?>/mobile/images/eva.jpg' class='logo'>
                        <h4>Eva's Reviews</h4>
                        <?=$this->partial('partials/eva_text.phtml')?>

                     </div>
                </div>
            <?php endif; unset($review); ?>
            
            <?php foreach($this->reviews as $review) : ?>
                <div class='review app'>
                    <span class='reviewer'><?=$review['name']?> (<?=date('d-m-Y', strtotime($review['date']))?>)</span>
                    <span class='rating'>
                        <?php
                            $rating     = $review['rating']; 
                            while($rating > 0) : $rating--; 
                        ?>
                            <img src="<?=$this->Cdn('site_assets')?>/mobile/images/star_full.gif" alt="star" width="11" height="12" />
                        <?php endwhile;?>
                        <?php
                            $rating     = $review['rating']; 
                            while($rating < 5) : $rating++; 
                        ?>
                            <img src="<?=$this->Cdn('site_assets')?>/mobile/images/star_empty.png" alt="star" width="11" height="12" />
                        <?php endwhile;?>
                        
                    </span>
                    <p>
                        <?=$review['review']?>
                    </p>
                </div>
            <?php endforeach;?>
            <?php if (empty($this->reviews)) :?>
                <a class='button' href='/review/add/pid/<?=$this->product['id']?>' class='add_review'>Be the first to review!</a>
            <?php else : ?>
                <a class='button' href='/review/all/pid/<?=$this->product['id']?>' class='add_review'>See all reviews</a> &nbsp;&nbsp;
                <a class='button' href='/review/add/pid/<?=$this->product['id']?>' class='add_review'>Add your own review</a>
            <?php endif;?>
              
        </div> 
                      
                        
                    
                                
                                                    <!-- Apps by smae dev -->
<? if ($this->appsByCp): ?>
                                                            <div class="recommendations">
                                                                <h1 class="padding-all">More apps by <?= $this->product['user_meta']->COMPANY_NAME ?></h1>
    <?
                                                            if (count($this->appsByCp) == 0) {
    ?>
                                                                <div class="app">
                                                                    <span class="mini-description">
                                                                        No more Apps by <?= $this->product['user_meta']->COMPANY_NAME ?>
                                                                    </span>
                                                                </div>
    <?
                                                            }
                                                            foreach ($this->appsByCp as $product): ?>
    <?= $this->partial('/partials/app.phtml', array("item" => $product)) ?>
    <?php endforeach; ?>
                                                            </div>
<? endif; ?>


                                                                <!-- Recomendations -->
                                                                <div class="recommendations padding-all">
                                                                    <img alt="Go to" src="<?=$this->cdn('site_assets')?>/mobile/images/arrow_skip.png"> <b><a href="<?php echo PROJECT_BASEPATH;?>cp/id/<?= $this->product['id'] ?>">More Apps by <?= $this->product['user_meta']->COMPANY_NAME ?></a></b><br/><br/>
                                                                    <img alt="Go to" src="<?=$this->cdn('site_assets')?>/mobile/images/arrow_skip.png"> <a href="<?php echo PROJECT_BASEPATH;?>recommended/id/<?= $this->product['id'] ?>">Discover More</a><br/><br/>
    <img alt="Go to" src="<?=$this->cdn('site_assets')?>/mobile/images/arrow_skip.png"> <a href="/app">All Compatible Apps</a>
</div>
