<!-- Start Content Box #1 -->
<div class="title">

    <h3>Edit | Create category details</h3>


</div>
<div class="box">
    <div class="txt">

        <div id="content_box">
            <div class="tab-login">
<?= $this->render('partials/message.phtml'); ?>
                <!-- Start pagecreate Form -->
                <form method="post" action="/category/save">
                    <fieldset>
                        <p><label>Parent category</label>
                            <select class="select-input small" name="parentCategoryId" id="parentCategoryId"  >
                                <option value="0">Parent Category</option> 
                                <?foreach($this->parentCategory as $pcategory): ?>
                                <option value="<?=$pcategory['id'];?>" <? if($pcategory['id'] == $this->category['parent_id']){echo 'selected=selected';} ?>><?=$pcategory['name'];?></option>
                                <?endforeach;?>
                            </select>
                        </p>
                        <p><label>Category name</label>
                            <input type="text" id="categoryName" name="categoryName" class="txt-input medium" value="<?=$this->category['name']; ?>"/>
                        </p>

                        <p><label>Status</label>
                            <select class="select-input small" name="categoryStatus" id="categoryStatus"  >
                                <option value="1">Yes</option>
                                <option value="0" <?if($this->category['status'] != 1 )echo 'selected=selected'; ?>>No</option>
                            </select>
                        </p>
                        
                        <p style="float:left;"><input type="submit" class="button" name="submit" value="Save" /><input type="button" class="button" name="button" value="Cancel" onClick="location.href='/category'"/>
                        </p>
                     <!--<p  class="remember"><input type="checkbox" /> Remember Me</p>-->
                    </fieldset>
                    <input type="hidden" name="id" id="id" value="<?=$this->category['id']; ?>" />
                </form>
                <!-- End Login Form -->

            </div>

        </div>

    </div>
</div>
<!-- End Content Box #1 -->


