<!-- Start Content Box #1 -->

<div class="title">

    <h3>Pages</h3>


</div>
<div class="box">
    <div class="txt">

        <div id="content_box">
            <div class="tab-login">
<?= $this->render('partials/message.phtml'); ?>
                <table cellpadding="0" cellspacing="0">
                    <thead>
                        <tr>

                            <th>Title</th>


                            <th style="width:5%">Operations</th>
                        </tr>
                    </thead>
                    <tbody>

                        <? foreach($this->formattedCategories  as $key => $category): ?>
                        
                            <tr>
                                <td><?=current($category); ?></td>

                                
                                <td>
                                    
                                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>category/edit/id/<?=$key;?>" ><img alt="Edit" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/edit.png" title="Edit"></a>
                                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>category/delete/id/<?=$key;?>" ><img src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/delete.png" alt="Delete"  title="Delete" onClick="return confirm('Are you sure?')"></a>

                                </td>
                            </tr>

                            <?php foreach($category as $skey=>$subcat): ?>

                                <? if($skey != 0): ?>
                                        <tr>
                                            <td style="padding-left:100px;">


                                                    <?= "<div> $subcat</div><br />"; ?>
                                                 

                                            </td>
                                            <td>
                                            
                                                <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>category/edit/id/<?=$skey;?>" ><img alt="Edit" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/edit.png" title="Edit"></a>
                                                <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>category/delete/id/<?=$skey;?>" ><img src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/delete.png" alt="Delete"  title="Delete" onClick="return confirm('Are you sure?')"></a>
                                            </td>

                                        </tr>
                                  <?endif;?>
                            <?endforeach; ?>
                        <?endforeach; ?>
                    </tbody>
                </table>

            </div>

        </div>

    </div>
</div>
<!-- End Content Box #1 -->


