<div class="prodListPage">

    <div class='container'>
        <div class='textBlock'>
                <h2 id="pageTitle">Forgot Password </h2>
               <form id="signup" name="signup" class='smallInputForm' action="<?= PROJECT_BASEPATH;?>user/forgot-password" method="post">
                  
                   <p>Enter your e-mail address to begin the password recovery process.</p><br>
                   
                    <?
                        $errors = $this->errors;
                        if(is_array($errors)) :?>
                            <div class='message-error'>
                                <p class='header'>Please correct the following problems</p>
                            <?php foreach ($errors as $error): ?>
                                <p><?=$error?></p>
                            <?endforeach;?>
                            </div>
                        <?endif;?>
                        
                     <?
                        $errors = $this->messages;
                        if(is_array($errors)) :?>
                            <div class='message-success'>
                            <?php foreach ($errors as $error): ?>
                                <p><?=$error?></p>
                            <?endforeach;?>
                            </div>
                        <?endif;?>   
                   <br>
                    <div class="input">
                       <label>E-Mail</label>
                       <input class="validate[required,custom[email]]"  name="email" id="email" type="text" value=""/>
                    </div>
                   
                    <div class="input submit">
                        <button id='submit' class='orangeButton' type='submit'>Recover Password</button>
                    </div>
                </form> 
        </div>
    </div>
</div>                    
 