<div class="prodListPage">
    <div class="container">
        <div class="contContent">


            <div class="blockContent">
                <div class="blkHead">
                    <h2 id="pageTitle">Reset Password </h2>
                </div>
                <div class="blkList">
                    <div class="prodListItem">
                        <div class="block">
                            <div class="blkContent">
                                <form id="signup" name="signup" action="<?= PROJECT_BASEPATH;?>user/reset-password" method="post">
                                    <ul>
                                        <?
                                        $error = $this->messages;
                                        if(is_array($error))
                                            foreach ($error as $key=>$value):
                                                ?>
                                        <li><?=$value?></li>
                                            <?
                                            endforeach;
                                        ?>
                                    </ul>
                                   <?php if($this->valid_request) {?>
                                   
                                    <div class="inputFld"><label>Password </label><input class="validate(required)" name="password" id="password" type="password" value=""/></div>
                                   <div class="inputFld"><label>Confirm</label><input class="validate(required)" name="confirm" id="confirm" type="password" value=""/></div>
                                    
                                    <?php $request = Zend_Controller_Front::getInstance()->getRequest();?>
                                    <input type="hidden" name ="otphash" value="<?=$request->otphash?>">
                                    <input type="hidden" name ="id" value="<?=$request->id?>">
                                    <input type="hidden" name="time" value="<?=$request->time?>">
                                    
                                    <ul class="btn">
                                    
                                    
                                        <li><a href="#" id="submit">change</a></li>
                                    </ul>
                                    
                                    <?php } ?>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
        <div class='clear'></div>
    </div>
</div>
<!-- product list page end -->