<?php if ($this->pageCount): ?>
    <div  class="paging">
        <ul class="right">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
        <li><a href="<?= $this->url(array('page' => $this->previous)); ?>"><<</a></li>
        <?php else: ?>
        <li> <a class="selected">&lt;&lt;</a></li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
        <li><a href="<?= $this->url(array('page' => $page)); ?>" ><?=$page?></a></li>
            <?php else: ?>
        <li>     <a class="selected"><?=$page?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
        <li><a href="<?= $this->url(array('page' => $this->next)); ?>">&gt;&gt;</a></li>
        <?php else: ?>
        <li><a class="selected">Next &gt;&gt;</a></li>
        <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>