<div class="box">
    <div class="txt">
        <ul class="icon_list">
            <li>
                <p>
                    <img alt="" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/content/icon_list/home_32.png">
                    <a href="/translate">Home</a>
                </p>
             </li>
            <li>
                <p>
                    <img alt="" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/content/icon_list/add_32.png">
                    <a href="http://nexva.com/np/4338.<?php echo $this->langCode?>">neXpage on Web</a>
                </p>
             </li>
             
             <li>   
                <p>
                    <?php 
                        $salt   = Zend_Registry::get('config')->nexva->translator->salt;
                        $base   = 'http://' . Zend_Registry::get('config')->nexva->application->mobile->url; 
                        $url    = $base . '/translate/enable/id/' . $this->langId . '/h/' . md5($salt . $this->langId) . '/noredirect/1';
                        $url    .= '/u/' . base64_encode('http://nexva.mobi/np/4338.' . $this->langCode);
                    ?>
                    <img alt="" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/content/icon_list/add_32.png">
                    <a href="<?=$url?>">neXpage on Mobile</a>
                </p>
             </li>
             <li>
                <p>
                    <img alt="" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/content/icon_list/add_32.png">
                    <a href="http://nexva.com/nl/7630.<?php echo $this->langCode?>/1">neXlinker on Web</a>
                </p>
             </li>
             <li>   
                <p>
                    <img alt="" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/content/icon_list/users.png">
                    <a href="/translate/disable">Logout</a>
                </p>
            </li>
        </ul>
        <div class="clear"></div>
    </div>
</div>