<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 9/3/13
 * Time: 1:47 PM
 * To change this template use File | Settings | File Templates.
 */
?>
<?php if ($this->pageCount): ?>

    <div id="paginationControl" class="pagination">
        <!-- Previous page link -->

        <?php if (isset($this->previous)): ?>

            <a href="<?php echo $this->url(array('page' => $this->previous, 'q'=> $this->keyword)); ?>"> &lt;&lt; Previous</a>

        <?php else: ?>

            <span class="disabled">&lt;&lt; Previous</span>

        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>

            <?php if ($page != $this->current): ?>

                <a class="number" href="<?php echo $this->url(array('page' => $page, 'q'=> $this->keyword)); ?>"><?php echo $page; ?></a>

            <?php else: ?>

                <a class="number current"><?php echo $page; ?></a>

            <?php endif; ?>

        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>

            <a href="<?php echo $this->url(array('page' => $this->next, 'q'=> $this->keyword)); ?>">Next &gt;&gt;</a>

        <?php else: ?>

            <span class="disabled">Next &gt;&gt;</span>

        <?php endif; ?>

    </div>
<?php endif; ?>