        <div class="title">
            <?php if (isset($this->campaignName)) : ?>
                <h3>All Promotion Codes for Campaign : <?=$this->campaignName?></h3>
            <?php else : ?>
                <h3>Unassigned Promotion Codes</h3>
            <?php endif;?>
        </div>
        <div class="box">
    <div class="txt">
        <table cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>User</th>
                    <th>Code</th>
                    <th>Enabled</th>
                    <th>Use Type</th>
                    <th>Discount</th>
                    <th>Amount</th>
                    <th>Type</th>
                    <th>From</th>
                    <th>To</th>
                    <th>&nbsp</th>
                </tr>
            </thead>
        <?php if (count($this->promoCodes)): $class = '';?>
            <tbody>
        <?php foreach ($this->promoCodes as $item): $class = ($class == 'alt') ? '' : 'alt' ; $item = (object) $item;?>
            <tr>
                <td class='<?=$class?>'><?=$item->id?></td>
                <td class='<?=$class?>'><?=$item->user->name?></td>
                <td class='<?=$class?>' title="<?=htmlspecialchars($item->description)?>"><?=$item->code?></td>
                <td class='<?=$class?>'><?=($item->enabled) ? 'Yes' : 'No'?></td>
                <td class='<?=$class?>'><?=$item->use_type?></td>
                <td class='<?=$class?>'><?=$item->discount_type?></td>
                <td class='<?=$class?>'><?=$item->amount?></td>
                <td class='<?=$class?>'><?=$item->promo_type?></td>
                <td class='<?=$class?>'><?=date('d-m-Y', strtotime($item->valid_from))?></td>
                <td class='<?=$class?>'><?=date('d-m-Y', strtotime($item->valid_to))?></td>
                <td class='<?=$class?>'>
                    <a href='/promotions/share/code/<?php echo $item->code ?>'>Share</a>
                    <a href='/promotions/view/id/<?php echo $item->id ?>'>View</a>
                    <a href='/promotions/delete/id/<?php echo $item->id ?>' class='del_conf'>Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
            </tbody>
        <?php endif; ?>
        </table>
    </div>