<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Maheel-Appmonkeyz
 * Date: 2/18/14
 * Time: 8:33 PM
 * To change this template use File | Settings | File Templates.
 */
?>
<ul class="shortcut-buttons-set">

    <li><a class="shortcut-button" href="<?php echo PBO_PROJECT_BASEPATH;?>campaign/add-email-campaign"><span>
                <img src="<?php echo PROJECT_BASEPATH;?>pbo/images/icons/mail-web-icon.png" width="50%" alt="icon" /><br />
                Add Email <br />Campaign
            </span></a>
    </li>

    <li><a class="shortcut-button" href="<?php echo PBO_PROJECT_BASEPATH;?>campaign/list-email-campaign"><span>
                <img src="<?php echo PROJECT_BASEPATH;?>pbo/images/icons/forms-icon.png" width="50%" alt="icon" /><br />
                List Email <br />Campaign
            </span></a>
    </li>
</ul>