<?php $currency = $this->ChangeCurrency($this->partnerId);?>
<div class="ui-grid-solo">
    <?php
    if($this->flashMessages)
    { ?>
        <div class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text" style="white-space: normal">
       
                <?php foreach($this->flashMessages as $message)
                {
                    echo $this->translate($this->escape($message));
                };?>
           </span></span></div>
    <?php }
    ?>
</div>
<?php if(!$this->isHeaderEnrichmentActive && $this->showRegisterLink) { ?>
<a id="terms" href="/user/update-profile" class="ui-btn ui-shadow ui-btn-icon-left ui-first-child ui-btn-up-d grey-color-bg"><span class="ui-btn-inner"><span class="ui-btn-text"><?php echo $this->translate("Update Profile");?></span><span class="ui-icon ui-icon-custom">&nbsp;</span></span></a>
<a id="resetpwd" href="/user/reset-password" class="ui-btn ui-shadow ui-btn-icon-left ui-first-child ui-btn-up-d grey-color-bg"><span class="ui-btn-inner"><span class="ui-btn-text"><?php echo $this->translate("Reset Password");?></span><span class="ui-icon ui-icon-custom">&nbsp;</span></span></a>
<a id="changemobile" href="/user/change-mobile" class="ui-btn ui-shadow ui-btn-icon-left ui-first-child ui-btn-up-d grey-color-bg"><span class="ui-btn-inner"><span class="ui-btn-text"><?php echo $this->translate("Change Mobile");?></span><span class="ui-icon ui-icon-custom">&nbsp;</span></span></a>
<?php } ?>
<a id="terms" href="/index/terms" class="ui-btn ui-shadow ui-btn-icon-left ui-first-child ui-btn-up-d grey-color-bg"><span class="ui-btn-inner"><span class="ui-btn-text"><?php echo $this->translate("Terms & Conditions");?></span><span class="ui-icon ui-icon-custom">&nbsp;</span></span></a>
<a id="aboutus" href="/index/aboutus" class="ui-btn ui-shadow ui-btn-icon-left ui-first-child ui-btn-up-d grey-color-bg"><span class="ui-btn-inner"><span class="ui-btn-text"><?php echo $this->translate("About Us");?></span><span class="ui-icon ui-icon-custom">&nbsp;</span></span></a>

<a id="view-ticket" href="<?php echo PROJECT_BASEPATH;?>ticket/view-tickets" class="ui-btn ui-shadow ui-btn-icon-left ui-first-child ui-btn-up-d grey-color-bg"><span class="ui-btn-inner"><span class="ui-btn-text"><?php echo $this->translate("View my ticket");?></span><span class="ui-icon ui-icon-custom">&nbsp;</span></span></a>
<a id="add-ticket" href="<?php echo PROJECT_BASEPATH;?>ticket/add-ticket" class="ui-btn ui-shadow ui-btn-icon-left ui-first-child ui-btn-up-d grey-color-bg"><span class="ui-btn-inner"><span class="ui-btn-text"><?php echo $this->translate("Add a ticket");?></span><span class="ui-icon ui-icon-custom">&nbsp;</span></span></a>

<?php //$currency = $this->ChangeCurrency($this->chap_id);?>
<div class="ui-content ui-body-d">
      <h2><?php echo $this->translate("Downloaded Apps");?></h2>
      <ul class="ui-icon-alt ui-listview">   

        <?php
        $x = 0;
        foreach($this->downloadedApps as $app) :  
            $x++;
            ?>
        <li class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-count ui-li-has-thumb ui-first-child ui-btn-up-d">
          <div class="ui-btn-inner ui-li">
            <div class="ui-btn-text"> <a class="ui-link-inherit" href="<?php echo PROJECT_BASEPATH;?>app/detail/id/<?=$app['product_id']?>"  rel="external"> <!--img src="<?= $this->productImages()."/vendors/phpThumb/phpThumb.php?src=/product_visuals/".APPLICATION_ENV."/".basename($app['thumbnail'])."&w=80&h=80&aoe=0&fltr[]=ric|0|0&q=100&f=png" ?>" /-->
                  <img class="ui-li-thumb" src="<?= $this->productImages()."/vendors/phpThumb/phpThumb.php?src=/product_visuals/".APPLICATION_ENV."/".basename($app['thumbnail'])."&w=80&h=80&aoe=0&fltr[]=ric|0|0&q=100&f=png" ?>">
             <p class="ui-li-aside"></p>
              <h3 class="ui-li-heading" style="white-space: normal"><?= $app['name'] ?></h3>
              <p class="ui-li-desc-ul-li" style="white-space: normal"><?= $this->trim($app['vendor'],18) ?></p>
              <div style="cursor: pointer; float: left;" id="rating">
                  
                  <span class="price-red-bg">
                      
                      
                <? if($app['price'] > 0) : ?>
                        
                      <?php if($this->mtnIran){ ?>
                                <?php echo (($app['price']) > 0) ? number_format($this->PricePoints(ceil($app['price']*$this->currencyDetails["rate"])),0, '.', ',').' '.$this->translate($currency[0]['symbol']) : $this->translate("Free") ;?>  
                            <?php } else { ?>
                                <?php echo (($app['price']) > 0) ? $this->currencyDetails["symbol_web"]. " ".number_format($this->PricePoints(ceil($app['price']*$this->currencyDetails["rate"])),2, '.', ',') : $this->translate("Free") ;?>  
                            <?php } ?>
            
                    <? else : ?>
                        
                        <?php echo $this->translate("Download");?>
                        
                    <? endif; ?>
                 </span>
                  
              </div>
              </a> </div>
            <span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div>
            <?= ($app['updates_available'] == 1) ? '<span class="update-available">!</span>' : ''; ?>
        </li>

        <? endforeach; ?>
    </ul>
</div>