<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 9/3/13
 * Time: 5:46 PM
 * To change this template use File | Settings | File Templates.
 */
?>
<script type="text/javascript">
    $().ready(function(){
        $("#change_mobile_form").validate();
    });
</script>
<div class="ui-content ui-body-d">
<h2><?php echo $this->translate("Change Mobile Number");?></h2>
<div class="ui-body ui-body-c bg-color-white">

<div class="ui-grid-solo">
    <?php
    if($this->success)
    { ?>
    <div class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text" style="white-space: normal">
    
            <?php echo $this->success;?>
        </span></span></div>
    <?php
    }
    if($this->ErrorMessages)
    { ?>
   <div class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text" style="white-space: normal">
    
        <?php foreach($this->ErrorMessages as $key=>$value)
        {
            if(is_array($value))
            {
                foreach($value as $one=>$two)
                {
                    echo $this->translate($two);
                }
                echo '<br/>';
            }
            else
            {
                echo $this->translate($value),'<br/>';
            }
        } ?>
       </span></span></div>
    <?php } ?>
</div>

    <form action="/user/change-mobile" method="post" id="change_mobile_form" data-ajax="false">
        <fieldset class="ui-field-contain ui-body ui-br">
            <label for="mobile_number" class="ui-input-text"><?php echo $this->translate("Mobile Number");?> :</label>
            <div class="ui-input-text ui-shadow-inset ui-corner-all ui-btn-shadow ui-body-c">
                <input type="text" name="mobile_number" id="mobile_number" class="required number ui-input-text ui-body-c" minlength="10" value="" >
            </div>
        </fieldset>

        <fieldset class="ui-field-contain ui-body ui-br">
            <label for="mobile_number_confirm" class="ui-input-text"><?php echo $this->translate("Confirm Mobile Number");?> :</label>
            <div class="ui-input-text ui-shadow-inset ui-corner-all ui-btn-shadow ui-body-c">
                <input type="text" name="mobile_number_confirm" id="mobile_number_confirm" class="required number ui-input-text ui-body-c" minlength="10" value="" >
            </div>
        </fieldset>

        <div id="changemobileno" class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text"><?php echo $this->translate("Change Mobile Number");?></span></span>
            <input type="submit" value="<?php echo $this->translate("Change Mobile Number"); ?>" class="ui-btn-hidden" id="btn_submit"></div>

    </form>
</div></div>