<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 9/6/13
 * Time: 4:12 PM
 * To change this template use File | Settings | File Templates.
 */
?>
<script type="text/javascript">
    $().ready(function(){
        $("#forgot_verification_form").validate();
        $("#resend_verification").click(function(){
            var resend = true;
            $.post("/user/resend-verification",{resend:resend},function(data) {
                window.location.href = '/user/forgot-verification';
              
            });
            
        });
    });
</script>

<div class="ui-grid-solo">
    <div id="jquery_message"></div>
    <?php
    if($this->flashMessages)
    { ?>
        <div class="ui-submit ui-btn ui-btn-up-b ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text" style="white-space: normal">
                <?php foreach($this->flashMessages as $message)
                {
                    echo $this->escape($message);
                }?>
            </span></span></div>
    <?php }

    if($this->ErrorMessages)
    { ?>
        <div class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text" style="white-space: normal">
                <?php foreach($this->ErrorMessages as $key=>$value)
                {
                    if(is_array($value))
                    {
                        foreach($value as $one=>$two)
                        {
                            echo $this->translate($two);
                        }
                        echo '<br/>';
                    }
                    else
                    {
                        echo $this->translate($value),'<br/>';
                    }
                } ?>
            </span></span></div>
    <?php }
    //$userId = Zend_Controller_Front::getInstance()->getRequest()->getParam('userId');
    ?>
</div>
<div class="ui-body ui-body-c">
    <form action="/user/forgot-verification" method="post" id="forgot_verification_form" data-ajax="false">
        <input type="hidden" name="userId" id="userId" value="">
        <fieldset data-role="fieldcontain" >
            <label for="verificationCode"><?php echo $this->translate("Verification Code");?> :</label>
            <input type="text" name="verificationCode" id="verificationCode" class="required" minlength="" value="" >
        </fieldset>

        <input type="submit" value="<?php echo $this->translate("Verify");?>">
    </form>
    <button id="resend_verification"><?php echo $this->translate("Resend Verification Code");?></button>
</div>