<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 9/6/13
 * Time: 10:12 AM
 * To change this template use File | Settings | File Templates.
 */
?>
<script type="text/javascript">
    $().ready(function(){
        $("#forgot_password_form").validate();
    });
</script>

<?php
//If airtel sl
$mobileNo = '';

if(isset($this->mobileNo) && !empty($this->mobileNo)){
    $mobileNo = $this->mobileNo;
}

elseif($this->chapId == 25022){
    $mobileNo = 9475;
}
elseif($this->chapId == 33644){
	$mobileNo = '24206xxxxxxx';
}
elseif($this->chapId == 80184){
    $mobileNo = 256;
}
elseif($this->chapId == 23045){
    $mobileNo = 98;
}
elseif($this->chapId == 114306){
    $mobileNo = '(e.g. 25073xxxxxxx)';
}
elseif($this->chapId == 81449){
    $mobileNo = '(e.g. 2348022222222)';
}
elseif($this->chapId == 110721){
    $mobileNo = '241xxxxxxxx';
}
elseif($this->chapId == 274515){
    $mobileNo = '22xxxxxxxxxxx';
}
elseif($this->chapId == 163302){
    $mobileNo = '(e.g. 265XXXXXXXXXX)';
}
elseif($this->chapId == 276531){
	$mobileNo = '(e.g. 225XXXXXXXX)';
}
elseif($this->chapId == 320345){
	$mobileNo = '(e.g. 229XXXXXXXX)';
}
else{
    
}
?>
<div class="ui-content ui-body-d">
<h2 class="font-size-16"><?php echo $this->translate("Forgot Password");?></h2>
<div class="ui-grid-solo">
    <?php
    if($this->success)
    { ?>
        <div class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text" style="white-space: normal">
                <?php echo $this->success;?>
            </span></span></div>
    <?php }
    if($this->ErrorMessages)
    { ?>
        <div class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text" style="white-space: normal">
                <?php foreach($this->ErrorMessages as $key=>$value)
                {
                    if(is_array($value))
                    {
                        foreach($value as $one=>$two)
                        {
                            echo $this->translate($two);
                        }
                        echo '<br/>';
                    }
                    else
                    {
                        echo $this->translate($value),'<br/>';
                    }
                } ?>
            </span></span></div>
    <?php } ?>
</div>
<div class="ui-body ui-body-c">
    <form action="/user/forgot-password" method="post" id="forgot_password_form" data-ajax="false">
        
       <fieldset class="ui-field-contain ui-body ui-br">
           
       
           <fieldset data-role="fieldcontain">
            <?php if($this->headerEnrichment): ?>
                <label for="email" class="ui-input-text"><?php echo $this->translate("Phone Number");?>  <span style="font-size: 10px;">   <?php  if($this->chapId == 280316) echo '(e.g. 243xxxxxxxxx)'; ?> </span>:</label>
           <div class="ui-input-text ui-shadow-inset ui-corner-all ui-btn-shadow ui-body-c">
               <input type="text" value="<?= $mobileNo ?>" minlength="5" class="required email ui-input-text ui-body-c" id="mobile_no" name="mobile_no">
           </div>
            <?php else: ?>
                <label for="email" class="ui-input-text"><?php echo $this->translate("Email");?> :</label>
           <div class="ui-input-text ui-shadow-inset ui-corner-all ui-btn-shadow ui-body-c">
               <input type="text" value="<?= $mobileNo ?>" minlength="5" class="required email ui-input-text ui-body-c" id="email" name="email">
           </div>
            <?php endif; ?>
        </fieldset>
       
       </fieldset>
        
        <div class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all"><span class="ui-btn-inner">
                <span class="ui-btn-text"><?php echo $this->translate("Request");?></span></span>
            <input type="submit" value="<?php echo $this->translate("Request");?>" class="ui-btn-hidden" data-disabled="false">
        </div>
        
    </form>
</div></div>