<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 9/3/13
 * Time: 5:59 PM
 * To change this template use File | Settings | File Templates.
 */
?>

<script type="text/javascript">
    $().ready(function(){
        $("#reset_password_form").validate();
    });
</script>
<div class="ui-content ui-body-d">
<h2 class="font-size-16"><?php echo $this->translate("Reset Password");?></h2>
<div class="ui-body ui-body-c bg-color-white">

<div class="ui-grid-solo">
    <?php
    if($this->success)
    { ?>
        <div class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text" style="white-space: normal">
    
                <?php echo $this->success;?>
            </span></span></div>
    <?php }
    if($this->ErrorMessages)
    { ?>
    <div class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text" style="white-space: normal">
    
        <?php foreach($this->ErrorMessages as $key=>$value)
        {
            if(is_array($value))
            {
                foreach($value as $one=>$two)
                {
                    echo $this->translate($two);
                }
                echo '<br/>';
            }
            else
            {
                echo $this->translate($value),'<br/>';
            }
        } ?>
        </span></span></div>
    <?php } ?>
</div>
    
    <form action="/user/reset-password" method="post" id="reset_password_form" data-ajax="false">    
        
        <fieldset class="ui-field-contain ui-body ui-br">
            <label for="email" class="ui-input-text"><?php echo $this->translate("Email");?> :</label>
            <div class="ui-input-text ui-shadow-inset ui-corner-all ui-btn-shadow ui-body-c">
                <input type="text" name="email" id="email" class="required email ui-input-text ui-body-c" minlength="5" readonly value="<?php if(!is_null($this->email)){ echo $this->email; }?>" >
            </div>
        </fieldset>

        <fieldset class="ui-field-contain ui-body ui-br">
            <label for="mobile_number" class="ui-input-text"><?php echo $this->translate("Mobile Number");?> :</label>
            <div class="ui-input-text ui-shadow-inset ui-corner-all ui-btn-shadow ui-body-c">
                <input type="text" name="mobile_number" id="mobile_number" class="required ui-input-text ui-body-c" readonly minlength="5" value="<?php if(!is_null($this->mobile_no)) { echo $this->mobile_no; }?>" >
            </div>
        </fieldset>

        <fieldset class="ui-field-contain ui-body ui-br">
            <label for="password" class="ui-input-text"><?php echo $this->translate("New Password");?> :</label>
            <div class="ui-input-text ui-shadow-inset ui-corner-all ui-btn-shadow ui-body-c">
                <input type="password" name="password" id="password" class="required ui-input-text ui-body-c" minlength="5" value="" >
            </div>
        </fieldset>

        <fieldset class="ui-field-contain ui-body ui-br">
            <label for="password2" class="ui-input-text"><?php echo $this->translate("Confirm Password");?> :</label>
            <div class="ui-input-text ui-shadow-inset ui-corner-all ui-btn-shadow ui-body-c">
                <input type="password" name="password2" id="password2" class="required ui-input-text ui-body-c" minlength="5" value="" >
            </div>
        </fieldset>
<div id="resetpwd" class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text">
            <?php echo $this->translate("Reset Password");?></span></span>
    <input type="submit" value="<?php echo $this->translate("Reset Password");?>" class="ui-btn-hidden" id="btn_submit"></div>

    </form>
</div></div>