<?php
/**
 * Created by JetBrains PhpStorm.
 * User: viraj
 * Date: 9/3/13
 * Time: 5:59 PM
 * To change this template use File | Settings | File Templates.
 */
?>

<script type="text/javascript">
    $().ready(function(){
        $("#reset_password_form").validate();
    });
</script>

<h2 class="font-size-16"><?php echo $this->translate("Reset Password");?></h2>
<div class="ui-grid-solo">
    <?php
    if($this->success)
    { ?>
        <div class="ui-submit ui-btn ui-btn-up-b ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text" style="white-space: normal">
                <?php echo $this->success;?>
           </span></span></div>
    <?php }
    if($this->ErrorMessages)
    { ?>
    <div class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all"><span class="ui-btn-inner"><span class="ui-btn-text" style="white-space: normal">
        <?php foreach($this->ErrorMessages as $key=>$value)
        {
            if(is_array($value))
            {
                foreach($value as $one=>$two)
                {
                    echo $this->translate($two);
                }
                echo '<br/>';
            }
            else
            {
                echo $this->translate($value),'<br/>';
            }
        } ?>
       </span></span></div>
    <?php } ?>
</div>
<div class="ui-body ui-body-c">
    <form action="/user/reset-password" method="post" id="reset_password_form" data-ajax="false">
        
        <?php if(!$this->headerEnrichment): ?>
        <fieldset data-role="fieldcontain">
            <label for="email"><?php echo $this->translate("Email");?> :</label>
            <input type="text" name="email" id="email" class="required email" minlength="5" readonly value="<?php if(!is_null($this->email)){ echo $this->email; }?>" >
        </fieldset>
        <?php endif; ?>
        <?php if($this->chapId != 935529){ ?>
        <fieldset data-role="fieldcontain">
            <label for="mobile_number"><?php echo $this->translate("Mobile Number");?> <span style="font-size: 10px;">  <?php  if($this->chapId == 280316) echo '(e.g. 243xxxxxxxxx)'; ?> </span> :</label>
            <input type="text" name="mobile_number" id="mobile_number" class="required" readonly minlength="5" value="<?php if(!is_null($this->mobile_no)) { echo $this->mobile_no; }?>" >
        </fieldset>
        <?php } ?>
        <?php if($this->chapId != 283006){ ?>
        <fieldset data-role="fieldcontain">
            <label for="password"><?php echo $this->translate("New Password");?> :</label>
            <input type="password" name="password" id="password" class="required" minlength="5" value="" >
        </fieldset>

        <fieldset data-role="fieldcontain">
            <label for="password2"><?php echo $this->translate("Confirm Password");?> :</label>
            <input type="password" name="password2" id="password2" class="required" minlength="5" value="" >
        </fieldset>
        <?php } ?>
        <input type="submit" value="<?php echo $this->translate("Reset Password");?>">
    </form>
</div>