<!-- Start Content Box #1 -->
<div class="title">

    <h3>Platforms.. Create | Edit</h3>


</div>
<div class="box">
    <div class="txt">

        <div id="content_box">
            <div class="tab-login">
<?= $this->render('partials/message.phtml'); ?>
                <!-- Start pagecreate Form -->
                <form method="post" action="/platform/save">
                    <fieldset>

                        <p><label>Name</label>
                            <input type="text" id="platformName" name="platformName" class="txt-input medium" value="<?=$this->platform['name']; ?>"/>
                        </p>

                        <p><label>Description</label>
                            <input type="text" id="platformDescription" name="platformDescription" class="txt-input medium" value="<?=$this->platform['description']; ?>"/>
                        </p>

                        
                        <p><label>Status</label>
                            <select class="select-input small" name="platformStatus" id="platformStatus"  >
                                <option value="1">Yes</option>
                                <option value="0" <?= (1 != $this->platform['status'])?"selected=selected":''; ?>>No</option>
                            </select>
                        </p>
                        <p style="float:left;"><input type="submit" class="button" name="submit" value="Save" /><input type="button" class="button" name="button" value="Cancel & Go to platform list" onClick="location.href='/platform'"/>
                        </p>
                     <!--<p  class="remember"><input type="checkbox" /> Remember Me</p>-->
                    </fieldset>
                    <input type="hidden" name="id" id="id" value="<?=$this->platform['id']; ?>" />
                </form>
                <!-- End Login Form -->

            </div>

        </div>

    </div>
</div>
<!-- End Content Box #1 -->