<div class="title">

    <h3>Platforms | Nexva.com</h3>

    
</div>
<div class="box">
    <div class="txt">
<?= $this->render('partials/message.phtml'); ?>
        <div id="content_box">
            <!-- Start tab tab-handsets -->

            <div class="tab-handsets">
                <!-- Start Table -->
                <table cellpadding="0" cellspacing="0">
                    <thead>
                        <tr>
                            <!--<th><input type="checkbox" name="check" /></th>-->
                            <th>Name</th>
                            <th>Description</th>
                            <th>&nbsp;</th>
                            <th>&nbsp;</th>
                            <th></th>

                        </tr>
                    </thead>
                    <tbody>

                        <? foreach($this->platforms as $platform): ?>
                        <tr>
                            <!--<td><input type="checkbox" name="check" /></td>-->
                            <td><?= $platform['name']; ?></td>
                            <td><?= $platform['description']; ?></td>
                            <td><?= $platform['icon']; ?></td>
                            <td><img src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/<?=($platform['status'])?'approved.gif':'pending.gif'; ?>" border="0"></td></td>
                            

                            <td>
                                    
                                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>platform/edit/id/<?=$platform['id'];?>" ><img alt="Edit" src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/edit.png" title="Edit"></a>
                                    <a href="<?php echo ADMIN_PROJECT_BASEPATH;?>platform/delete/id/<?=$platform['id'];?>" ><img src="<?php echo ADMIN_PROJECT_BASEPATH;?>assets/img/global/icons/delete.png" alt="Delete"  title="Delete" onClick="return confirm('Are you sure?')"></a>
                            </td>
                        </tr>
                        <?endforeach; ?>
                    </tbody>
                </table>
                 <!-- End Table -->
                 <?= $this->paginationControl($this->platforms, 'Sliding', 'partials/paginator.phtml'); ?>
            </div>
            <!-- End handsets -->
        </div>
    </div>
</div>