<div class="title"><h3>Featured contents</h3></div>
<div class="box">
    <div class="txt">

        
<div id="content_box">
            <div class="tab-all">
                <!-- Start Table -->
                <table cellpadding="0" cellspacing="0">
                    <thead>
                        <tr>
                            <!--<th><input type="checkbox" name="check" /></th>-->
                            <th>ID</th>
                            <th>Name</th>
                            <th>Price</th>
                            <th>Is New</th>
                            <th>Type</th>
                            <th>Content status</th>
                            <th>Created / Updated on</th>
                            <th>Operations</th>
                            <th>Status views / downloads</th>
                        </tr>
                    </thead>
                    <tbody>

                        <? foreach($this->featuredProducts as $product): ?>

                            <?= $this->partial('partials/product_simple.phtml',array("product" => $product)); ?>

                        <?endforeach; ?>
                    </tbody>
                </table>
                <? //= $this->paginationControl($this->products_all,'Sliding','partials/paginator.phtml',array("tab" => 'tab-all',"page_name" => 'page')); ?>
                 <!-- End Table -->
            </div>
</div>
    </div></div>