<?php $this->headScript()->captureStart();?>
    $(function() {
        $( "#tabs" ).tabs();
    });
<?php $this->headScript()->captureEnd();?>
<style>
<!--
<?php $this->headStyle()->captureStart() ?>
#content .ui-tabs .ui-tabs-nav.ui-widget-header {
    background:none;
    background-color: #000;
}   

#content .ui-tabs .ui-tabs-nav li {
    float:right;
    border: none;
} 

#content .ui-tabs .ui-tabs-nav li a {
    color : #fff;
    background: none;
    background-color: #000;
}

#content .ui-tabs .ui-tabs-nav li a:hover,  #content .ui-tabs .ui-tabs-nav li.ui-state-active a {
    -moz-border-radius: 4px; -webkit-border-radius: 4px; border-radius: 4px;
   color : #000;
   background-color: #fff;
}


<?php $this->headStyle()->captureEnd() ?>
-->
</style>

<div class="box">
 <div class="txt">
    <?php if('' != $this->update_res){ ?>
     <div class="message info">
        <p><?php echo $this->update_res; ?></p>
        </div>
    <?php } ?>
    <div id="content_box">
        <div id='tabs'>
             <ul>
                <li><a href="#admin">Admin User information</a></li>
                <li><a href="#technical">Technical User information</a></li>

            </ul>

        
                 <!-- tab admin user -->
                 <div id="admin" class='ui-tabs-hide'>
                 		<?php
        if(is_array($this->flashMessenger->getMessages())):
            foreach ($this->flashMessenger->getMessages() as $class => $value):
                $key = key($value);
                ?>
        <div class="message <?=key($value)?>">
                    <?=$this->partial('partials/itemlist.phtml', array("item" => $value[$key]));?>
        </div>
            <?php
            endforeach;
        endif;
        ?>
                  <!-- Start Form -->
    
                  
                   <?=$this->adminUser;?>
                  
                  <!-- end Form -->
                  
                </div>
                <!-- tab admin user ends -->
                
                
                
            <!-- tab tehnical  user -->
            <div id="technical" class='ui-tabs-hide'>
            		<?php
        if(is_array($this->flashMessenger->getMessages())):
            foreach ($this->flashMessenger->getMessages() as $class => $value):
                $key = key($value);
                ?>
        <div class="message <?=key($value)?>">
                    <?=$this->partial('partials/itemlist.phtml', array("item" => $value[$key]));?>
        </div>
            <?php
            endforeach;
        endif;
        ?>
                  <!-- Start Form -->
                   
                 
                  
                  <?=$this->technicalUser;?>
                  
                  <!-- end Form -->
            </div>
                
            <!-- tab tehnical  user -->
                
        </div>
        
         <!-- tabs-->

                    </div>
                </div>
            </div>