<div class="title">
    <h3 style="cursor: s-resize;">Registered Users</h3>
</div>

<div class="box">
    <div class="txt">
        <div class="content_box">  
            
                   
      <?php if($this->isUsersEmpty === FALSE)
            {
                
            
            ?>
            <br />
            
            <table cellpadding="0" cellspacing="0" style="width: 70%">
                    
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Email</th>
                            <th>Date Registered</th>                        
                        </tr>
                    </thead>
                    <tbody>
                       
                        <?php foreach($this->registerdUsers as $users)
                        {
                        ?>                        
                        <tr>
                            <td><?php echo $users->id; ?></td>
                            <td><?php echo $users->email; ?></td>
                            <td><?php echo $users->created_date; ?></td>
                        </tr>
                        <?php
                        }
                        ?>
                    </tbody>
            </table>
            
            <?= $this->paginationControl($this->registerdUsers, 'Sliding', 'partials/paginator.phtml',array("page_name" =>"registered_users","search_caption" =>"search","search_value" => $this->search)); ?>
            <?php 
            }
            else
            {
                echo "No Registered users found";
            }
       ?>
        </div>
    </div>
</div>
