<link rel="stylesheet" type="text/css" media="screen" href="<?php echo PROJECT_BASEPATH;?>common/js/jquery/plugins/ketchup-plugin/css/jquery.ketchup.css" />
<script type="text/javascript" src="<?php echo PROJECT_BASEPATH;?>common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.basic.min.js"></script>

<script type="text/javascript" src="<?php echo PROJECT_BASEPATH;?>common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.messages.js"></script>
<script type="text/javascript" src="<?php echo PROJECT_BASEPATH;?>common/js/jquery/plugins/ketchup-plugin/js/jquery.ketchup.validations.basic.js"></script>



    <script>
    $(document).ready(function() {
      $('#frmresetpassword').ketchup();
    });
    </script>
    
    <div class="title">

        <h3>Reset Password</h3>

    </div>
    <div class="box">
        <div class="txt">

            <div id="content_box">
                <div class="tab-reset" id="resetpassword">

                    <?php if($this->error != '')
                    {
                    ?>
                        <div class="message error"><p><? echo $this->error?></p></div>
                    <?php
                    }
                    ?>

                    <? if ($this->valid_request)
                    {
                    ?>
                        <form method="post" id="frmresetpassword" action="/user/resetpassword">

                            <fieldset>
                                <p><label>New Password</label>
                                    <input name="password" id="password" type="password" class="txt-input large validate(required)" />
                                </p>


                                <p>
                                    <label>Confirm New Password</label>
                                    <input name="confirm" id="confirm" type="password" class="txt-input large" />
                                </p>

                                <p style="float:left;">
                                   <?php $request = Zend_Controller_Front::getInstance()->getRequest();?>
                                    <input type="submit" class="button" name="submit" value="Change Password" />
                                    <input type="hidden" name ="otphash" value="<?=$request->otphash?>">
                                    <input type="hidden" name ="id" value="<?=$request->id?>">
                                    <input type="hidden" name="time" value="<?=$request->time?>">


                                </p>


                            </fieldset>


                        </form>
                    <?
                    }
                    ?>

                              
                </div>


                
            </div>

        </div>
    </div>
