<div class="ui-content ui-body-d">
    <h2 class="font-size-16"><?= isset($this->pageDetails->title) ? $this->escape($this->pageDetails->title): ''; ?></h2> 

<!--p>
<?php /*echo $this->translate("For any customer service issues, bugs in the app downloaded, difficulty downloading or purchases made by mistake please contact us at this email :"). 
        $this->escape($this->chapHelp()).' '. $this->translate("We will get back to you within 48 hours.")*/?>
</p-->
      <?= isset($this->pageDetails->page_text) ?  $this->escape($this->pageDetails->page_text): ''; ?>
<?php if($this->ycoins) : ?>
        <a href="<?php echo PROJECT_BASEPATH;?>ticket/add-ticket" data-ajax="false"><?= $this->translate("For any customer service issues, bugs in the app downloaded, difficulty downloading or purchases made by mistake please add a ticket. We will get back to you within 48 hours") ?>.</a>
    <?php elseif($this->mtnIran) : ?>
        <a href="<?php echo PROJECT_BASEPATH;?>ticket/add-ticket" data-ajax="false"><?= $this->translate("For any customer service issues, bugs in the app downloaded, difficulty downloading or purchases made by mistake please add a ticket. We will get back to you within 48 hours.") ?></a>
    <?php else: ?>
        <?php echo $this->translate("For any customer service issues, bugs in the app downloaded, difficulty downloading or purchases made by mistake please "). 
        '<a href="<?php echo PROJECT_BASEPATH;?>ticket/add-ticket" data-ajax="false">'.$this->translate("add a ticket").'</a>.&nbsp;'. $this->translate("We will get back to you within 48 hours.")?>
    <?php endif; ?>
</div>