<div class="ui-content ui-body-d">
      <h2><?= $this->translate('Search'); ?></h2>
      
       <div class="ui-body ui-body-c bg-color-white">
           
           <form id="search_form" name="search_form" action="/index/search/">
               
               <div class="ui-input-search ui-shadow-inset ui-btn-corner-all ui-btn-shadow ui-icon-searchfield ui-body-c ui-mini">
                   <input type="text" class="search-header ui-input-text ui-body-c" id="search" name="q" value="" class="search-header">
                   <a class="ui-input-clear ui-btn ui-btn-up-b ui-shadow ui-btn-corner-all ui-mini ui-btn-icon-notext ui-input-clear-hidden" href="#" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-icon="delete" data-iconpos="notext" data-theme="b" data-mini="true"><span class="ui-btn-inner"><span class="ui-btn-text">clear text</span><span class="ui-icon ui-icon-delete ui-icon-shadow">&nbsp;</span></span></a></div>

<div class="ui-submit ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all">
    <span class="ui-btn-inner"><span class="ui-btn-text"><?= $this->translate('Search'); ?></span></span>
    <input type="submit" value="Search" class="ui-btn-hidden"></div>


                        
                    </form>

    </div>   </div>