<?php $this->headScript()->captureStart(); ?>
var __DATA_TOP_DOWNLOAD = eval(<?php echo $this->appDownloadJson; ?>); //most often downloaded
var __DATA_CHAPS        = eval(<?php echo $this->appDownloadsByChapJson ?>);//view breakdown by chap

<?php $this->headScript()->captureEnd(); ?>
<?php echo $this->partial('partials/analytics_includes.phtml'); ?>

<?php
$opts = array(
    'startTimeView' => $this->startTimeView,
    'endTimeView' => $this->endTimeView
);
echo $this->partial('partials/analytics_menu.phtml', $opts);
?>


<div id='visualizations'>    
    <div class='chart_box_full'>
        <div class="title">
            <h3>App Downloads by CHAP</h3>
        </div>
        <div class="box">
            <div class="txt">
                <div class='full_block' id='stats_apps_by_chap'>
                    We haven't collected enough data to display analytics for this app. Check back soon!
                </div>
            </div>
        </div>
    </div> 
</div>
