<?php echo $this->partial('partials/analytics_includes.phtml');?>

<?php $this->headScript()->captureStart();?>

    var __DATA_PLATFORMS       = eval(<?php echo $this->appBuildsJson?>); 
    
<?php $this->headScript()->captureEnd();?>
<?php               
    $chapId = Zend_Auth::getInstance()->getIdentity()->id;
    if(!in_array($chapId, array('585474','585480'))){ ?>
          <?php $this->headScript()->appendFile($this->cdn('site_assets').'/cp/assets/js/analytics/appview.js'); ?>
    <?php }else{?>
          <?php $this->headScript()->appendFile('/cp/assets/js/analytics/appview_fr.js'); ?>
    <?php } ?>

<?php 
    $totalViews     = 0; //array_sum($this->appView);
    $totalDownloads = 0; //array_sum($this->appDownloads);
?>

<?php 
    $opts   = array(
        'startTimeView' => $this->startTimeView, 
        'endTimeView' => $this->endTimeView,
        'queryString'   => $this->queryString
    );
    echo $this->partial('partials/analytics_menu.phtml', $opts);
?>

<div id='visualizations'>
    <?php 
        echo $this->partial('partials/analytics_product_info.phtml', $opts);
    ?>
    <div id='stats_view_by_device_cont' class='chart_box_full'>
        <div class="title">
            <h3><?php echo $this->translate("Revenue per Channel");?></h3>
            <div class='filter'>
                  
            </div>
        </div>
        <div class="box">
            <div class="txt">
                <div class='full_block' id='stats_view_by_platform'>
                    <?php echo $this->translate("We haven't collected enough data to display analytics for this app. Check back soon!");?>
                </div>
            </div>
        </div>
    </div>
    
    <div class="title">
            <h3><?php echo $this->translate("Revenue per Channel");?></h3>
    </div>
    <div class="box">
        <div class="txt">
            <table cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                        <th><?php echo $this->translate("Channel Partner");?> </th>
                        <th><?php echo $this->translate("Revenue");?></th>
                        <th>%</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                        $sum    = array_sum($this->appBuilds);
                        $class  = ''; 
                    ?>
                    <?php foreach ($this->appBuilds as $build => $hits) : ?>
                    <?php $class = ($class == 'class="alt"') ? '' : 'class="alt"';?>
                    <tr>
                        <td><?php echo $build;?></td>
                        <td>$ <?php echo round($hits,2) ?></td>
                        <td>  <?php echo round($hits / $sum * 100, 2) ?>%</td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    
     <div class="title">
            <h3><?php echo $this->translate("Sales");?></h3>
    </div>
    <div class="box">
        <div class="txt">
            <table cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                        <th><?php echo $this->translate("Date");?> </th>
                        <th><?php echo $this->translate("Iransaction Id");?> </th>
                        <th style="width: 45%"><?php echo $this->translate("Mobile Number");?></th>
                        <th><?php echo $this->translate("Channel Partner");?> </th>
                        <th><?php echo $this->translate("Credit");?></th>
                        <th><?php echo $this->translate("Nexva Earn");?></th>
                        <th><?php echo $this->translate("Cp Earn");?></th>
                        <th><?php echo $this->translate("Chap Earn");?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                        $class  = ''; 
                    ?>
                    <?php foreach ($this->paymentReceivedList as $paymentReceivedList) : ?>
                    <?php $class = ($class == 'class="alt"') ? '' : 'class="alt"';?>
                    <tr>
                        <td><?php echo $paymentReceivedList->date ?></td>
                        <td><?php echo $paymentReceivedList->trans_id ?></td>
                        <td><?php echo $paymentReceivedList->mobile_no ?></td>
                        <td><?php echo $paymentReceivedList->channel;?></td>
                        <td>$<?php echo $paymentReceivedList->credit ?></td>
                        <td>$<?php echo $paymentReceivedList->nexva_earn ?></td>
                        <td>$<?php echo $paymentReceivedList->cp_earn ?></td>
                        <td>$<?php echo $paymentReceivedList->chap_earn ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
             <?= $this->paginationControl($this->paymentReceivedList,'Sliding','partials/analytics_paginator.phtml',array('from_view' =>$this->startTimeView,'to_view'=>$this->endTimeView)); ?>
        </div>
    </div>
    
</div>
 