<!-- Start Content Box #2 -->
<div class="title">

    <h3>Agreement<small style="color:gray;"></small></h3>

</div>
<div class="box">
    <div class="txt">

        <div id="content_box">
            <div>
                <? if(isset($this->agreement_special)): ?>
                <object data="<?=$this->agreement_special;?>" type="<?=$this->content_type; ?>" width="100%" height="900">
                    alt : <a href="<?=$this->agreement_special;?>"><?=$this->agreement_special;?></a>
                </object>
                <?else:?>
                <div>
                        <?= $this->agreement_normal; ?>
                </div>
                <?endif; ?>
            </div>
        </div>

    </div>
</div>
<!-- End Content Box #2 -->
