<div id="content" style="background-image: url(/common/footer/images/back1.gif);padding-top:12px;background-repeat:repeat-x;text-align: center;margin:10px 0px;">
  <div id="logs" style="margin-bottom:0px;">
    <a title="3 Screens" href="http://www.3screens.tv/" target="_blank"><img src="<?php echo PROJECT_BASEPATH;?>common/footer/images/3screens_logo.jpg" /></a>
    <a title="Amazon webservices" href="http://aws.amazon.com/s3/" target="_blank"><img src="<?php echo PROJECT_BASEPATH;?>common/footer/images/amazonss3logo.gif" /></a>
    <a title="Paypal" href="http://www.paypal.com/" target="_blank"><img src="<?php echo PROJECT_BASEPATH;?>common/footer/images/btt_paypal.gif" /></a>
    <a title="Mobileopen" href="http://www.mobilopen.org/" target="_blank"><img src="<?php echo PROJECT_BASEPATH;?>common/footer/images/mobilopen_logo.gif" /></a>
    <a title="Paythru" href="http://www.paythru.com/" target="_blank"><img src="<?php echo PROJECT_BASEPATH;?>common/footer/images/paythru_logo.gif" /></a>
    <a title="Silk" href="http://www.silk-outsourcing.com/" target="_blank"><img src="<?php echo PROJECT_BASEPATH;?>common/footer/images/silk_logo.jpg" /></a>
  </div>
  <div class="content" style="margin-bottom:2px;">
    <p style="text-align: center;">
      <a href="http://www.facebook.com/pages/neXva-Inc/189510615951">
        <img width="40" height="40" class="imagefield imagefield-field_image" alt="Find Us on Facebook" title="Find Us on Facebook" src="http://corp.nexva.com/sites/default/files/f-icon.png?1281006745">
      </a>
      <a href="http://twitter.com/nexva">
        <img width="40" height="40" class="imagefield imagefield-field_image" alt="Follow Us on Twitter" title="Follow Us on Twitter" src="http://corp.nexva.com/sites/default/files/t-icon.png?1281006755">
      </a>
      <a href="http://www.linkedin.com/companies/940580/neXva?trk=pp_icon">
        <img width="40" height="40" class="imagefield imagefield-field_image" alt="LinkedIn" title="LinkedIn" src="http://corp.nexva.com/sites/default/files/in_icon.png?1281006769">
      </a>
    </p>
  </div>
  <div id="footer_links" style="font-weight:normal;">
    <a href="/" >Home</a> |
    <a href="http://www.nexva.com" >neXva</a> |
    <a href="<?php echo CP_PROJECT_BASEPATH;?>people" target="_blank">About Us</a> |
    <a href="<?php echo CP_PROJECT_BASEPATH;?>content-providers" target="_blank">Content/Application Developers</a> |

    <a href="<?php echo CP_PROJECT_BASEPATH;?>contact" target="_blank">Contact Us</a>
  </div>
  <div id="copyright" style="font-size: 10px;font-weight: lighter;padding-top:5px;color:graytext">
    <p> &copy;Copyright <?= date('Y'); ?> neXva . All rights reserved .
      Products, logos and companies mentioned herein are trademarks or trade names of their respective owners and therefore copyright. </p>
  </div>

</div>